import { json } from '@sveltejs/kit';
import { prisma } from '$lib/server/prisma';

export async function PUT({ params, locals }) {
	if (!locals.user || locals.user.role !== 'ADMIN') {
		return json({ error: 'Unauthorized' }, { status: 401 });
	}

	try {
		const vocab = await prisma.vocabulary.update({
			where: { id: params.id },
			data: { isAutoGenerated: false }
		});
		return json({ success: true, data: vocab });
	} catch (error) {
		console.error('Error approving vocabulary:', error);
		return json({ error: 'Failed to approve vocabulary' }, { status: 500 });
	}
}