import { json } from '@sveltejs/kit';
import { prisma } from '$lib/server/prisma';
import type { RequestEvent } from '@sveltejs/kit';

const CEFR_ORDER = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'];

export async function GET({ locals, url }: RequestEvent) {
  if (!locals.user) {
    return json({ error: 'Unauthorized' }, { status: 401 });
  }

  const limit = Math.min(parseInt(url.searchParams.get('limit') ?? '12'), 50);
  const userId = locals.user.id;
  const activeLanguageId = locals.user.activeLanguage?.id;

  if (!activeLanguageId) {
    return json({ words: [] });
  }

  // Get user's current CEFR level for this language
  const userProgress = await prisma.userProgress.findUnique({
    where: { userId_languageId: { userId, languageId: activeLanguageId } }
  });
  const userLevel = userProgress?.cefrLevel ?? 'A1';
  const userLevelIdx = CEFR_ORDER.indexOf(userLevel);

  // Include words at user's level and one level up
  const targetLevels = [
    CEFR_ORDER[userLevelIdx],
    CEFR_ORDER[Math.min(userLevelIdx + 1, CEFR_ORDER.length - 1)]
  ].filter(Boolean);

  // Get words user already has
  const userVocabIds = await prisma.userVocabulary.findMany({
    where: { userId },
    select: { vocabularyId: true }
  });
  const excludeIds = new Set(userVocabIds.map((v) => v.vocabularyId));

  // Find approved vocab words at the target levels, sorted by frequency rank (nulls last)
  const candidates = await prisma.vocabulary.findMany({
    where: {
      languageId: activeLanguageId,
      isAutoGenerated: false,
      cefrLevel: { in: targetLevels },
      ...(excludeIds.size > 0 ? { id: { notIn: Array.from(excludeIds) } } : {})
    },
    include: { meanings: { take: 1 } },
    orderBy: { frequency: { sort: 'asc', nulls: 'last' } },
    take: limit
  });

  let words = candidates;

  // Fallback: if we don't have enough results, fill with highest-frequency words from any CEFR level
  if (words.length < limit) {
    const primaryIds = new Set(words.map((w) => w.id));
    const fallbackExcludeIds = new Set([...excludeIds, ...primaryIds]);
    const fallback = await prisma.vocabulary.findMany({
      where: {
        languageId: activeLanguageId,
        isAutoGenerated: false,
        ...(fallbackExcludeIds.size > 0 ? { id: { notIn: Array.from(fallbackExcludeIds) } } : {})
      },
      include: { meanings: { take: 1 } },
      orderBy: { frequency: { sort: 'asc', nulls: 'last' } },
      take: limit - words.length
    });
    words = [...words, ...fallback];
  }

  return json({
    words: words.map((w) => ({
      id: w.id,
      lemma: w.lemma,
      cefrLevel: w.cefrLevel,
      frequency: w.frequency,
      partOfSpeech: w.partOfSpeech,
      meaning: w.meanings[0]?.value ?? ''
    })),
    userLevel
  });
}
