services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lingolearn
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql

  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    environment:
      - BODY_SIZE_LIMIT=52428800
    env_file:
      - .env

    depends_on:
      - db

volumes:
  pgdata:
