import { redirect, fail } from '@sveltejs/kit';
import type { PageServerLoad, Actions } from './$types';
import { prisma } from '$lib/server/prisma';
import { runSeed } from '../../../prisma/seed';
import { getSiteSettings, updateSiteSettings } from '$lib/server/settings';
import { todayUtc } from '$lib/server/dateUtils';
import { DAILY_TOKEN_QUOTA } from '$lib/server/aiQuota';

export const load: PageServerLoad = async ({ locals }) => {
  // Additional fallback check though hooks.server.ts handles it
  if (!locals.user || locals.user.role !== 'ADMIN') {
    throw redirect(303, '/');
  }

  const now = Date.now();
  const oneDayAgo = new Date(now - 24 * 60 * 60 * 1000);
  const sevenDaysAgo = new Date(now - 7 * 24 * 60 * 60 * 1000);
  const today = todayUtc();

  const [
    users,
    settings,
    languages,
    pendingVocab,
    totalUsers,
    activeUsers,
    totalClasses,
    totalVocabWords,
    // System Health queries
    activeUsers24h,
    activeUsers7d,
    totalGrammarRules,
    gamesPublished,
    todayAiUsage,
    usersOverQuota,
    userVocabularyCount,
    userVocabularyProgressCount,
    reviewLogCount,
    conversationSessionCount,
    messageCount
  ] = await Promise.all([
    prisma.user.findMany({
      orderBy: { createdAt: 'desc' },
      select: {
        id: true,
        username: true,
        email: true,
        role: true,
        createdAt: true,
        lastActive: true,
        activeLanguage: true,
        progress: {
          include: { language: true }
        }
      }
    }),
    getSiteSettings(),
    prisma.language.findMany({
      orderBy: { name: 'asc' },
      include: {
        _count: { select: { vocabularies: true, grammarRules: true } }
      }
    }),
    prisma.vocabulary.findMany({
      where: { isAutoGenerated: true },
      include: { language: true, meanings: true },
      orderBy: { createdAt: 'desc' }
    }),
    prisma.user.count(),
    prisma.user.count({
      where: {
        lastActive: { gte: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000) } // Active in last 30 days
      }
    }),
    prisma.class.count(),
    prisma.vocabulary.count(),
    // User Stats
    prisma.user.count({ where: { lastActive: { gte: oneDayAgo } } }),
    prisma.user.count({ where: { lastActive: { gte: sevenDaysAgo } } }),
    // Content Stats
    prisma.grammarRule.count(),
    prisma.game.count({ where: { isPublished: true } }),
    // AI Usage — aggregate tokens used today
    prisma.userAiUsage.aggregate({
      where: { date: today },
      _sum: { tokensUsed: true, goodWillTokens: true },
      _count: true
    }),
    // Users who exceeded quota today
    prisma.userAiUsage.count({
      where: {
        date: today,
        tokensUsed: { gte: DAILY_TOKEN_QUOTA }
      }
    }),
    // Database Size — key table counts
    prisma.userVocabulary.count(),
    prisma.userVocabularyProgress.count(),
    prisma.reviewLog.count(),
    prisma.conversationSession.count(),
    prisma.message.count()
  ]);

  const classes = await prisma.class.findMany({
    include: {
      _count: { select: { members: true, assignments: true } }
    },
    orderBy: { createdAt: 'desc' }
  });

  return {
    users,
    localLoginEnabled: settings.localLoginEnabled,
    llmEndpoint: settings.llmEndpoint || '',
    llmApiKey: settings.llmApiKey || '',
    llmModel: settings.llmModel || '',
    languages,
    pendingVocab,
    classes,
    stats: {
      totalUsers,
      activeUsers,
      totalClasses,
      totalVocabWords,
      pendingVocabWords: pendingVocab.length
    },
    systemHealth: {
      userStats: {
        total: totalUsers,
        active24h: activeUsers24h,
        active7d: activeUsers7d
      },
      contentStats: {
        vocabularyWords: totalVocabWords,
        grammarRules: totalGrammarRules,
        gamesPublished
      },
      aiUsage: {
        tokensUsedToday: todayAiUsage._sum.tokensUsed ?? 0,
        goodWillTokensToday: todayAiUsage._sum.goodWillTokens ?? 0,
        usersActiveToday: todayAiUsage._count,
        usersOverQuota,
        dailyQuotaLimit: DAILY_TOKEN_QUOTA
      },
      databaseSize: {
        userVocabulary: userVocabularyCount,
        userVocabularyProgress: userVocabularyProgressCount,
        reviewLog: reviewLogCount,
        conversationSession: conversationSessionCount,
        message: messageCount
      },
      systemConfig: {
        llmEndpoint: settings.llmEndpoint || 'Not configured',
        llmModel: settings.llmModel || 'Not configured',
        localLoginEnabled: settings.localLoginEnabled
      }
    }
  };
};

export const actions: Actions = {
  runSeed: async ({ locals }) => {
    if (!locals.user || locals.user.role !== 'ADMIN') {
      return fail(403, { message: 'Unauthorized' });
    }

    try {
      await runSeed(prisma, true);
      return { success: true, message: 'Seed script executed successfully.' };
    } catch (error) {
      console.error('Seed execution failed:', error);
      return fail(500, { message: 'Failed to run seed script.' });
    }
  },
  toggleLocalLogin: async ({ locals }) => {
    if (!locals.user || locals.user.role !== 'ADMIN') {
      return fail(403, { message: 'Unauthorized' });
    }

    try {
      const current = await getSiteSettings();
      await updateSiteSettings({ localLoginEnabled: !current.localLoginEnabled });
      const status = !current.localLoginEnabled ? 'enabled' : 'disabled';
      return { success: true, message: `Local login ${status}.` };
    } catch (error) {
      console.error('Toggle local login failed:', error);
      return fail(500, { message: 'Failed to toggle local login.' });
    }
  },
  updateLLMSettings: async ({ request, locals }) => {
    if (!locals.user || locals.user.role !== 'ADMIN') {
      return fail(403, { message: 'Unauthorized' });
    }

    const data = await request.formData();
    const llmEndpoint = data.get('llmEndpoint')?.toString() || '';
    const llmApiKey = data.get('llmApiKey')?.toString() || '';
    const llmModel = data.get('llmModel')?.toString() || '';

    try {
      await updateSiteSettings({
        llmEndpoint: llmEndpoint || null,
        llmApiKey: llmApiKey || null,
        llmModel: llmModel || null
      });
      return { success: true, message: 'LLM settings updated.' };
    } catch (error) {
      console.error('Update LLM settings failed:', error);
      return fail(500, { message: 'Failed to update LLM settings.' });
    }
  }
};
