import { redirect, fail } from '@sveltejs/kit';
import type { PageServerLoad, Actions } from './$types';
import { prisma } from '$lib/server/prisma';
import { runSeed } from '../../../prisma/seed';
import { getSiteSettings, updateSiteSettings } from '$lib/server/settings';

export const load: PageServerLoad = async ({ locals }) => {
	// Additional fallback check though hooks.server.ts handles it
	if (!locals.user || locals.user.role !== 'ADMIN') {
		throw redirect(303, '/');
	}

	const [users, settings, languages, pendingVocab, totalUsers, activeUsers, totalClasses, totalVocabWords] = await Promise.all([
		prisma.user.findMany({
			orderBy: { createdAt: 'desc' },
			select: {
				id: true,
				username: true,
				email: true,
				role: true,
				createdAt: true,
				lastActive: true,
				activeLanguage: true,
				progress: {
					include: { language: true }
				}
			}
		}),
		getSiteSettings(),
		prisma.language.findMany({
			orderBy: { name: 'asc' },
			include: {
				_count: { select: { vocabularies: true, grammarRules: true } }
			}
		}),
		prisma.vocabulary.findMany({
			where: { isAutoGenerated: true },
			include: { language: true },
			orderBy: { createdAt: 'desc' }
		}),
		prisma.user.count(),
		prisma.user.count({
			where: {
				lastActive: { gte: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000) } // Active in last 30 days
			}
		}),
		prisma.class.count(),
		prisma.vocabulary.count()
	]);

	const classes = await prisma.class.findMany({
		include: {
			_count: { select: { members: true, assignments: true } }
		},
		orderBy: { createdAt: 'desc' }
	});

	return {
		users,
		localLoginEnabled: settings.localLoginEnabled,
		llmEndpoint: settings.llmEndpoint || '',
		llmModel: settings.llmModel || '',
		languages,
		pendingVocab,
		classes,
		stats: {
			totalUsers,
			activeUsers,
			totalClasses,
			totalVocabWords,
			pendingVocabWords: pendingVocab.length
		}
	};
};

export const actions: Actions = {
	runSeed: async ({ locals }) => {
		if (!locals.user || locals.user.role !== 'ADMIN') {
			return fail(403, { message: 'Unauthorized' });
		}

		try {
			await runSeed(prisma, true);
			return { success: true, message: 'Seed script executed successfully.' };
		} catch (error) {
			console.error('Seed execution failed:', error);
			return fail(500, { message: 'Failed to run seed script.' });
		}
	},
	toggleLocalLogin: async ({ locals }) => {
		if (!locals.user || locals.user.role !== 'ADMIN') {
			return fail(403, { message: 'Unauthorized' });
		}

		try {
			const current = await getSiteSettings();
			await updateSiteSettings({ localLoginEnabled: !current.localLoginEnabled });
			const status = !current.localLoginEnabled ? 'enabled' : 'disabled';
			return { success: true, message: `Local login ${status}.` };
		} catch (error) {
			console.error('Toggle local login failed:', error);
			return fail(500, { message: 'Failed to toggle local login.' });
		}
	},
	updateLLMSettings: async ({ request, locals }) => {
		if (!locals.user || locals.user.role !== 'ADMIN') {
			return fail(403, { message: 'Unauthorized' });
		}
		
		const data = await request.formData();
		const llmEndpoint = data.get('llmEndpoint')?.toString() || '';
		const llmModel = data.get('llmModel')?.toString() || '';
		
		try {
			await updateSiteSettings({ 
				llmEndpoint: llmEndpoint || null, 
				llmModel: llmModel || null 
			});
			return { success: true, message: 'LLM settings updated.' };
		} catch (error) {
			console.error('Update LLM settings failed:', error);
			return fail(500, { message: 'Failed to update LLM settings.' });
		}
	}
};