apiVersion: v1
kind: Secret
metadata:
  name: lingolearn-secrets
  namespace: lingolearn
type: Opaque
stringData:
  AUTH_SECRET: ""
  AUTH_GOOGLE_ID: ""
  AUTH_GOOGLE_SECRET: ""
  DEFAULT_LLM_BASE_URL: ""
  DEFAULT_LLM_API_KEY: ""
  DEFAULT_LLM_MODEL: ""
