import { json } from '@sveltejs/kit';
import { prisma } from '$lib/server/prisma';
import type { RequestEvent } from '@sveltejs/kit';

/**
 * Bookmark a vocabulary word by either vocabularyId or lemma+languageId.
 * If only lemma+languageId is provided and no matching Vocabulary record exists,
 * one is auto-created with isAutoGenerated=true.
 */
export const POST = async ({ request, locals }: RequestEvent) => {
  if (!locals.user) {
    return json({ error: 'Unauthorized' }, { status: 401 });
  }

  const body = await request.json();
  const { vocabularyId, lemma, languageId } = body;

  if (!vocabularyId && (!lemma || !languageId)) {
    return json({ error: 'Provide vocabularyId, or lemma and languageId' }, { status: 400 });
  }

  try {
    let resolvedVocabId = vocabularyId as string | undefined;

    if (!resolvedVocabId) {
      // Look up existing vocabulary by lemma + language
      const existing = await prisma.vocabulary.findFirst({
        where: {
          lemma: { equals: lemma, mode: 'insensitive' },
          languageId
        },
        select: { id: true }
      });

      if (existing) {
        resolvedVocabId = existing.id;
      } else {
        // Auto-create a minimal vocabulary record
        const created = await prisma.vocabulary.create({
          data: {
            lemma,
            languageId,
            isAutoGenerated: true,
            cefrLevel: 'A1'
          }
        });
        resolvedVocabId = created.id;
      }
    } else {
      // Verify the vocabulary exists
      const vocab = await prisma.vocabulary.findUnique({
        where: { id: resolvedVocabId },
        select: { id: true }
      });
      if (!vocab) {
        return json({ error: 'Vocabulary not found' }, { status: 404 });
      }
    }

    const result = await prisma.userVocabulary.upsert({
      where: {
        userId_vocabularyId: {
          userId: locals.user.id,
          vocabularyId: resolvedVocabId
        }
      },
      update: {},
      create: {
        userId: locals.user.id,
        vocabularyId: resolvedVocabId,
        srsState: 'UNSEEN',
        eloRating: 1000
      }
    });

    return json({ success: true, vocabularyId: resolvedVocabId, result });
  } catch (error) {
    console.error('Failed to bookmark vocabulary:', error);
    return json({ error: 'Failed to bookmark vocabulary' }, { status: 500 });
  }
};
