import { json } from '@sveltejs/kit';
import { prisma } from '$lib/server/prisma';
import { generateChatCompletion } from '$lib/server/llm';
import { recordTokenUsage } from '$lib/server/aiQuota';
import { FUNCTION_WORDS, upsertAiVocabEntry } from '$lib/server/vocabProcessor';
import type { RequestEvent } from '@sveltejs/kit';

export async function POST({ request, locals }: RequestEvent) {
  if (!locals.user || locals.user.role !== 'ADMIN') {
    return json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { text, languageId, languageName } = await request.json();

  if (!text || !languageId || !languageName) {
    return json({ error: 'Missing required fields' }, { status: 400 });
  }

  // 1. Extract unique words from text
  const rawWords = text
    .replace(/<[^>]+>/g, '') // strip HTML
    .split(/\s+/)
    .map((w: string) =>
      w
        .replace(/[.,!?;:'"()[\]{}\-\u2014\u2013¡¿«»]/g, '')
        .trim()
        .toLowerCase()
    )
    .filter((w: string) => w.length >= 2 && !FUNCTION_WORDS.has(w));
  const uniqueWords = [...new Set<string>(rawWords)];

  // 2. Check which words already exist in DB
  const existing = await prisma.vocabulary.findMany({
    where: { languageId, lemma: { in: uniqueWords, mode: 'insensitive' } },
    select: { lemma: true }
  });
  const existingLemmas = new Set(existing.map((v) => v.lemma.toLowerCase()));
  const unknownWords = uniqueWords.filter((w) => !existingLemmas.has(w));

  // 3. Process unknown words in batches of 20
  const BATCH_SIZE = 20;
  const newVocabIds: string[] = [];

  for (let i = 0; i < unknownWords.length; i += BATCH_SIZE) {
    const batch = unknownWords.slice(i, i + BATCH_SIZE);

    try {
      const aiRes = await generateChatCompletion({
        userId: locals.user.id,
        messages: [
          {
            role: 'user',
            content: `Provide vocabulary dictionary entries for these ${languageName} words: ${JSON.stringify(batch)}\n\nRespond with JSON:\n{"vocabulary":[{"lemma":"canonical base form in ${languageName}","meaning":"English meaning","partOfSpeech":"noun|verb|adjective|adverb|preposition|conjunction|pronoun|other","gender":"MASCULINE|FEMININE|NEUTER or null","plural":"plural or null"}]}`
          }
        ],
        systemPrompt: `You are an expert ${languageName} lexicographer. For each word, provide its canonical dictionary lemma and English meaning. Skip words that are not valid ${languageName} vocabulary (numbers, proper nouns, non-words). Output ONLY valid JSON.`,
        jsonMode: true,
        temperature: 0.1,
        onUsage: ({ totalTokens }) => recordTokenUsage(locals.user!.id, totalTokens, true)
      });

      const parsed = JSON.parse(aiRes.choices[0].message.content);

      for (const v of parsed.vocabulary ?? []) {
        const result = await upsertAiVocabEntry(v, languageName, languageId, false);
        if (result && result.isAutoGenerated) {
          newVocabIds.push(result.id);
        }
      }
    } catch (err) {
      console.error('Batch enrichment error for batch', i, err);
    }
  }

  // 4. Auto-review the newly created words
  let approvedCount = 0;
  let rejectedCount = 0;

  if (newVocabIds.length > 0) {
    const newVocab = await prisma.vocabulary.findMany({
      where: { id: { in: newVocabIds } },
      include: { language: true, meanings: true }
    });

    if (newVocab.length > 0) {
      const reviewPrompt = `You are a strict safety reviewer for an educational language learning app used by schools.
Your task is to review a list of submitted vocabulary words and approve or reject them.

Rules for approval:
1. The word MUST be a real, correctly spelled word in its respective language.
2. The word MUST be completely safe and appropriate to be broadcasted at a school assembly.
3. Reject any inappropriate slang, profanity, slurs, or suggestive content.
4. Actively look out for deceitful submissions, bypass attempts, or fake words designed to trick the system.
5. If you are unsure, reject it.

Please evaluate each word in the provided JSON array. Return a JSON object with a single key "results" mapping the ID of each word to a boolean (true for approve, false for reject).

Format: { "results": { "uuid1": true, "uuid2": false } }`;

      const wordsData = newVocab.map((w) => ({
        id: w.id,
        language: w.language?.name,
        lemma: w.lemma,
        meaning: (w as any).meanings?.[0]?.value || null
      }));

      try {
        const reviewRes = await generateChatCompletion({
          userId: locals.user.id,
          messages: [{ role: 'user', content: JSON.stringify(wordsData) }],
          systemPrompt: reviewPrompt,
          jsonMode: true,
          temperature: 0.1
        });

        const reviewParsed = JSON.parse(reviewRes.choices[0].message.content);
        const results = reviewParsed.results;

        if (results && typeof results === 'object') {
          for (const [id, isApproved] of Object.entries(results)) {
            if (isApproved === true) {
              await prisma.vocabulary.updateMany({
                where: { id },
                data: { isAutoGenerated: false }
              });
              approvedCount++;
            } else if (isApproved === false) {
              await prisma.vocabulary.deleteMany({ where: { id } });
              rejectedCount++;
            }
          }
        }
      } catch (err) {
        console.error('Auto-review error:', err);
      }
    }
  }

  return json({
    success: true,
    extracted: uniqueWords.length,
    alreadyInDb: existingLemmas.size,
    newWordsProcessed: unknownWords.length,
    enriched: newVocabIds.length,
    approved: approvedCount,
    rejected: rejectedCount
  });
}
