// ~40 common Italian adjectives
export const adjectives = [
  { lemma: 'grande', meaning: 'big', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'piccolo', meaning: 'small', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'buono', meaning: 'good', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'cattivo', meaning: 'bad', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'bello', meaning: 'beautiful', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'brutto', meaning: 'ugly', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'nuovo', meaning: 'new', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'vecchio', meaning: 'old', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'giovane', meaning: 'young', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'alto', meaning: 'tall', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'basso', meaning: 'short (height)', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'lungo', meaning: 'long', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'corto', meaning: 'short (length)', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'facile', meaning: 'easy', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'difficile', meaning: 'difficult', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'veloce', meaning: 'fast', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'lento', meaning: 'slow', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'caldo', meaning: 'hot', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'freddo', meaning: 'cold', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'aperto', meaning: 'open', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'chiuso', meaning: 'closed', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'caro', meaning: 'expensive, dear', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'economico', meaning: 'cheap', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'pulito', meaning: 'clean', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'sporco', meaning: 'dirty', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'simpatico', meaning: 'nice, friendly', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'antipatico', meaning: 'unpleasant', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'felice', meaning: 'happy', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'triste', meaning: 'sad', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'forte', meaning: 'strong', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'debole', meaning: 'weak', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'ricco', meaning: 'rich', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'povero', meaning: 'poor', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'chiaro', meaning: 'clear, light', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'scuro', meaning: 'dark', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'giusto', meaning: 'right, correct', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'sbagliato', meaning: 'wrong', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'libero', meaning: 'free', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'occupato', meaning: 'busy, occupied', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'pieno', meaning: 'full', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'vuoto', meaning: 'empty', partOfSpeech: 'adjective', isBeginner: true }
];
