// ~350 Italian adjectives
export const adjectives = [
  { lemma: 'grande', meaning: 'big', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'piccolo', meaning: 'small', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'buono', meaning: 'good', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'cattivo', meaning: 'bad', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'bello', meaning: 'beautiful', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'brutto', meaning: 'ugly', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'nuovo', meaning: 'new', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'vecchio', meaning: 'old', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'giovane', meaning: 'young', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'anziano', meaning: 'elderly', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'alto', meaning: 'tall', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'basso', meaning: 'short (height)', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'lungo', meaning: 'long', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'corto', meaning: 'short (length)', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'largo', meaning: 'wide', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'stretto', meaning: 'narrow, tight', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'facile', meaning: 'easy', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'difficile', meaning: 'difficult', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'veloce', meaning: 'fast', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'lento', meaning: 'slow', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'caldo', meaning: 'hot', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'freddo', meaning: 'cold', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'tiepido', meaning: 'lukewarm', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'fresco', meaning: 'cool, fresh', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'aperto', meaning: 'open', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'chiuso', meaning: 'closed', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'caro', meaning: 'expensive, dear', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'economico', meaning: 'cheap', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'pulito', meaning: 'clean', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'sporco', meaning: 'dirty', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'simpatico', meaning: 'nice, friendly', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'antipatico', meaning: 'unpleasant', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'felice', meaning: 'happy', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'triste', meaning: 'sad', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'forte', meaning: 'strong', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'debole', meaning: 'weak', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'ricco', meaning: 'rich', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'povero', meaning: 'poor', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'chiaro', meaning: 'clear, light', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'scuro', meaning: 'dark', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'giusto', meaning: 'right, correct', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'sbagliato', meaning: 'wrong', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'libero', meaning: 'free', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'occupato', meaning: 'busy, occupied', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'pieno', meaning: 'full', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'vuoto', meaning: 'empty', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'stanco', meaning: 'tired', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'riposato', meaning: 'rested', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'malato', meaning: 'sick', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'sano', meaning: 'healthy', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'intelligente', meaning: 'intelligent', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'stupido', meaning: 'stupid', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'interessante', meaning: 'interesting', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'noioso', meaning: 'boring', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'divertente', meaning: 'fun, funny', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'importante', meaning: 'important', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'utile', meaning: 'useful', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'inutile', meaning: 'useless', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'famoso', meaning: 'famous', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'sconosciuto', meaning: 'unknown', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'vero', meaning: 'true, real', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'falso', meaning: 'false', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'sicuro', meaning: 'safe, sure', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'pericoloso', meaning: 'dangerous', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'possibile', meaning: 'possible', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'impossibile', meaning: 'impossible', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'capace', meaning: 'capable', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'incapace', meaning: 'incapable', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'gentile', meaning: 'kind, gentle', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'cortese', meaning: 'polite', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'maleducato', meaning: 'rude', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'paziente', meaning: 'patient', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'impaziente', meaning: 'impatient', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'onesto', meaning: 'honest', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'disonesto', meaning: 'dishonest', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'generoso', meaning: 'generous', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'avaro', meaning: 'greedy, stingy', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'coraggioso', meaning: 'brave', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'pauroso', meaning: 'fearful', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'timido', meaning: 'shy', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'estroverso', meaning: 'extroverted', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'allegro', meaning: 'cheerful', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'arrabbiato', meaning: 'angry', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'nervoso', meaning: 'nervous', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'calmo', meaning: 'calm', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'tranquillo', meaning: 'quiet, calm', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'rumoroso', meaning: 'noisy', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'silenzioso', meaning: 'silent', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'pesante', meaning: 'heavy', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'leggero', meaning: 'light (weight)', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'duro', meaning: 'hard', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'morbido', meaning: 'soft', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'liscio', meaning: 'smooth', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'ruvido', meaning: 'rough', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'secco', meaning: 'dry', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'asciutto', meaning: 'dry', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'bagnato', meaning: 'wet', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'umido', meaning: 'humid', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'pulito', meaning: 'clean', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'sporco', meaning: 'dirty', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'profumato', meaning: 'scented', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'puzzolente', meaning: 'stinking', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'dolce', meaning: 'sweet', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'amaro', meaning: 'bitter', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'salato', meaning: 'salty', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'acido', meaning: 'acid, sour', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'piccante', meaning: 'spicy', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'squisito', meaning: 'exquisite, delicious', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'gustoso', meaning: 'tasty', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'insipido', meaning: 'tasteless', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'rosso', meaning: 'red', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'blu', meaning: 'blue', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'verde', meaning: 'green', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'giallo', meaning: 'yellow', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'nero', meaning: 'black', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'bianco', meaning: 'white', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'grigio', meaning: 'gray', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'marrone', meaning: 'brown', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'arancione', meaning: 'orange', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'rosa', meaning: 'pink', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'viola', meaning: 'purple', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'azzurro', meaning: 'light blue', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'tondo', meaning: 'round', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'quadrato', meaning: 'square', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'triangolare', meaning: 'triangular', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'rettangolare', meaning: 'rectangular', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'piatto', meaning: 'flat', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'profondo', meaning: 'deep', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'superficiale', meaning: 'superficial', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'vicino', meaning: 'near', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'lontano', meaning: 'far', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'prossimo', meaning: 'next', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'ultimo', meaning: 'last', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'primo', meaning: 'first', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'secondo', meaning: 'second', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'terzo', meaning: 'third', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'singolo', meaning: 'single', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'doppio', meaning: 'double', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'triplo', meaning: 'triple', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'intero', meaning: 'whole', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'mezzo', meaning: 'half', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'solo', meaning: 'alone, only', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'stesso', meaning: 'same', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'diverso', meaning: 'different', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'simile', meaning: 'similar', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'uguale', meaning: 'equal, same', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'comune', meaning: 'common', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'raro', meaning: 'rare', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'normale', meaning: 'normal', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'strano', meaning: 'strange', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'particolare', meaning: 'particular', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'speciale', meaning: 'special', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'pubblico', meaning: 'public', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'privato', meaning: 'private', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'nazionale', meaning: 'national', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'internazionale', meaning: 'international', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'locale', meaning: 'local', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'moderno', meaning: 'modern', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'antico', meaning: 'ancient', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'recente', meaning: 'recent', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'vecchio', meaning: 'old', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'giovane', meaning: 'young', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'nuovo', meaning: 'new', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'attuale', meaning: 'current', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'precedente', meaning: 'previous', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'successivo', meaning: 'next, subsequent', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'fisico', meaning: 'physical', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'mentale', meaning: 'mental', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'spirituale', meaning: 'spiritual', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'religioso', meaning: 'religious', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'politico', meaning: 'political', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'economico', meaning: 'economic, cheap', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'sociale', meaning: 'social', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'culturale', meaning: 'cultural', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'scientifico', meaning: 'scientific', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'tecnico', meaning: 'technical', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'artistico', meaning: 'artistic', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'storico', meaning: 'historical', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'geografico', meaning: 'geographical', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'naturale', meaning: 'natural', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'artificiale', meaning: 'artificial', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'libero', meaning: 'free', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'occupato', meaning: 'occupied', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'pieno', meaning: 'full', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'vuoto', meaning: 'empty', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'carico', meaning: 'loaded', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'scarico', meaning: 'unloaded, empty battery', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'acceso', meaning: 'on (light/device)', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'spento', meaning: 'off (light/device)', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'rotto', meaning: 'broken', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'guasto', meaning: 'broken, out of order', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'intero', meaning: 'whole', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'diviso', meaning: 'divided', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'unito', meaning: 'united', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'separato', meaning: 'separated', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'misto', meaning: 'mixed', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'puro', meaning: 'pure', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'semplice', meaning: 'simple', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'complesso', meaning: 'complex', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'complicato', meaning: 'complicated', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'chiaro', meaning: 'clear', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'confuso', meaning: 'confused', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'ordinato', meaning: 'ordered, tidy', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'disordinato', meaning: 'disordered, messy', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'preciso', meaning: 'precise', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'vago', meaning: 'vague', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'esatto', meaning: 'exact', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'sbagliato', meaning: 'wrong', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'perfetto', meaning: 'perfect', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'ottimo', meaning: 'excellent', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'pessimo', meaning: 'terrible', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'magnifico', meaning: 'magnificent', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'splendido', meaning: 'splendid', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'orribile', meaning: 'horrible', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'terribile', meaning: 'terrible', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'fantastico', meaning: 'fantastic', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'incredibile', meaning: 'incredible', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'meraviglioso', meaning: 'wonderful', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'stupendo', meaning: 'stupendous', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'carino', meaning: 'cute, nice', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'grazioso', meaning: 'graceful, pretty', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'elegante', meaning: 'elegant', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'volgare', meaning: 'vulgar', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'serio', meaning: 'serious', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'ironico', meaning: 'ironic', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'sarcastico', meaning: 'sarcastic', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'ridicolo', meaning: 'ridiculous', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'curioso', meaning: 'curious', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'indifferente', meaning: 'indifferent', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'attento', meaning: 'attentive, careful', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'distratto', meaning: 'distracted', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'sveglio', meaning: 'awake, smart', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'addormentato', meaning: 'asleep', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'vivo', meaning: 'alive', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'morto', meaning: 'dead', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'nudo', meaning: 'naked', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'vestito', meaning: 'dressed', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'ricco', meaning: 'rich', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'povero', meaning: 'poor', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'avaro', meaning: 'stingy', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'generoso', meaning: 'generous', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'egoista', meaning: 'selfish', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'altruista', meaning: 'altruistic', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'fedele', meaning: 'faithful', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'infedele', meaning: 'unfaithful', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'geloso', meaning: 'jealous', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'invidioso', meaning: 'envious', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'orgoglioso', meaning: 'proud', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'umile', meaning: 'humble', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'modesto', meaning: 'modest', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'arrogante', meaning: 'arrogant', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'presuntuoso', meaning: 'presumptuous', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'sicuro', meaning: 'confident, secure', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'insicuro', meaning: 'insecure', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'ottimista', meaning: 'optimistic', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'pessimista', meaning: 'pessimistic', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'attivo', meaning: 'active', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'passivo', meaning: 'passive', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'pigro', meaning: 'lazy', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'dinamico', meaning: 'dynamic', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'energetico', meaning: 'energetic', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'forte', meaning: 'strong', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'debole', meaning: 'weak', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'resistente', meaning: 'resistant', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'fragile', meaning: 'fragile', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'duro', meaning: 'hard', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'tenero', meaning: 'tender', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'morbido', meaning: 'soft', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'rigido', meaning: 'rigid', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'flessibile', meaning: 'flexible', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'elastico', meaning: 'elastic', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'stretto', meaning: 'narrow', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'largo', meaning: 'wide', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'ampio', meaning: 'ample, broad', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'vasto', meaning: 'vast', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'immenso', meaning: 'immense', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'enorme', meaning: 'enormous', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'gigante', meaning: 'giant', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'minuscolo', meaning: 'tiny', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'minimo', meaning: 'minimum', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'massimo', meaning: 'maximum', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'ottimo', meaning: 'best, excellent', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'pessimo', meaning: 'worst, terrible', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'migliore', meaning: 'better, best', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'peggiore', meaning: 'worse, worst', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'maggiore', meaning: 'greater, larger', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'minore', meaning: 'smaller, minor', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'superiore', meaning: 'superior, upper', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'inferiore', meaning: 'inferior, lower', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'esterno', meaning: 'external', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'interno', meaning: 'internal', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'centrale', meaning: 'central', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'laterale', meaning: 'lateral, side', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'frontale', meaning: 'frontal', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'posteriore', meaning: 'rear', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'destro', meaning: 'right', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'sinistro', meaning: 'left', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'italiano', meaning: 'Italian', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'americano', meaning: 'American', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'inglese', meaning: 'English', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'francese', meaning: 'French', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'tedesco', meaning: 'German', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'spagnolo', meaning: 'Spanish', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'cinese', meaning: 'Chinese', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'giapponese', meaning: 'Japanese', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'russo', meaning: 'Russian', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'europeo', meaning: 'European', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'africano', meaning: 'African', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'asiatico', meaning: 'Asian', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'solare', meaning: 'solar, cheerful', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'lunare', meaning: 'lunar, moody', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'estivo', meaning: 'summery', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'invernale', meaning: 'wintry', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'autunnale', meaning: 'autumnal', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'primaverile', meaning: 'spring-like', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'quotidiano', meaning: 'daily', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'settimanale', meaning: 'weekly', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'mensile', meaning: 'monthly', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'annuale', meaning: 'annual', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'temporaneo', meaning: 'temporary', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'permanente', meaning: 'permanent', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'eterno', meaning: 'eternal', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'infinito', meaning: 'infinite', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'limitato', meaning: 'limited', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'illimitato', meaning: 'unlimited', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'libero', meaning: 'free', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'gratuito', meaning: 'free of charge', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'costoso', meaning: 'expensive', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'prezioso', meaning: 'precious', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'raro', meaning: 'rare', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'comune', meaning: 'common', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'frequente', meaning: 'frequent', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'insolito', meaning: 'unusual', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'strano', meaning: 'strange', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'assurdo', meaning: 'absurd', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'logico', meaning: 'logical', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'illogico', meaning: 'illogical', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'ovvio', meaning: 'obvious', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'evidente', meaning: 'evident', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'nascosto', meaning: 'hidden', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'visibile', meaning: 'visible', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'invisibile', meaning: 'invisible', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'chiaro', meaning: 'clear', partOfSpeech: 'adjective', isBeginner: true },
  { lemma: 'oscuro', meaning: 'obscure, dark', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'trasparente', meaning: 'transparent', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'opaco', meaning: 'opaque', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'lucido', meaning: 'shiny', partOfSpeech: 'adjective', isBeginner: false },
  { lemma: 'opaco', meaning: 'matte', partOfSpeech: 'adjective', isBeginner: false }
];
