// ~30 common Italian adverbs
export const adverbs = [
  { lemma: 'sempre', meaning: 'always', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'mai', meaning: 'never', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'spesso', meaning: 'often', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'raramente', meaning: 'rarely', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'presto', meaning: 'early, soon', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'tardi', meaning: 'late', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'adesso', meaning: 'now', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'poi', meaning: 'then, later', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'già', meaning: 'already', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'ancora', meaning: 'still, yet', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'subito', meaning: 'immediately', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'lì', meaning: 'there', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'qui', meaning: 'here', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'lontano', meaning: 'far', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'vicino', meaning: 'near', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'bene', meaning: 'well', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'male', meaning: 'badly', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'così', meaning: 'so, thus', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'forse', meaning: 'maybe', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'anche', meaning: 'also, too', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'solo', meaning: 'only', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'insieme', meaning: 'together', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'davvero', meaning: 'really', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'circa', meaning: 'about, around', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'quasi', meaning: 'almost', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'semplicemente', meaning: 'simply', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'lentamente', meaning: 'slowly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'velocemente', meaning: 'quickly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'ovunque', meaning: 'everywhere', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'dappertutto', meaning: 'all over', partOfSpeech: 'adverb', isBeginner: false }
];
