// ~220 Italian adverbs
export const adverbs = [
  { lemma: 'sempre', meaning: 'always', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'mai', meaning: 'never', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'spesso', meaning: 'often', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'raramente', meaning: 'rarely', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'presto', meaning: 'early, soon', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'tardi', meaning: 'late', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'adesso', meaning: 'now', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'ora', meaning: 'now', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'poi', meaning: 'then, later', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'già', meaning: 'already', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'ancora', meaning: 'still, yet', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'subito', meaning: 'immediately', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'lì', meaning: 'there', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'là', meaning: 'there (further)', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'qui', meaning: 'here', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'qua', meaning: 'here (less precise)', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'lontano', meaning: 'far', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'vicino', meaning: 'near', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'bene', meaning: 'well', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'male', meaning: 'badly', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'così', meaning: 'so, thus', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'forse', meaning: 'maybe', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'anche', meaning: 'also, too', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'solo', meaning: 'only', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'solamente', meaning: 'only', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'insieme', meaning: 'together', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'davvero', meaning: 'really', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'circa', meaning: 'about, around', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'quasi', meaning: 'almost', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'molto', meaning: 'very, much', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'poco', meaning: 'little', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'troppo', meaning: 'too much', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'tanto', meaning: 'so much', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'abbastanza', meaning: 'enough, fairly', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'più', meaning: 'more', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'meno', meaning: 'less', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'appena', meaning: 'just, as soon as', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'magari', meaning: 'maybe, if only', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'ovunque', meaning: 'everywhere', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'dovunque', meaning: 'anywhere', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'altrove', meaning: 'elsewhere', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'dappertutto', meaning: 'all over', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'sopra', meaning: 'above', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'sotto', meaning: 'below', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'davanti', meaning: 'in front', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'dietro', meaning: 'behind', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'dentro', meaning: 'inside', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'fuori', meaning: 'outside', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'su', meaning: 'up', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'giù', meaning: 'down', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'ieri', meaning: 'yesterday', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'oggi', meaning: 'today', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'domani', meaning: 'tomorrow', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'dopodomani', meaning: 'day after tomorrow', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'l\'altro ieri', meaning: 'day before yesterday', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'stamattina', meaning: 'this morning', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'stasera', meaning: 'this evening', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'stanotte', meaning: 'tonight', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'finora', meaning: 'so far', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'ormai', meaning: 'by now', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'intanto', meaning: 'meanwhile', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'frattanto', meaning: 'meanwhile', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'attualmente', meaning: 'currently', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'recentemente', meaning: 'recently', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'ultimamente', meaning: 'lately', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'precedentemente', meaning: 'previously', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'successivamente', meaning: 'subsequently', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'finalmente', meaning: 'finally', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'alla fine', meaning: 'in the end', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'da poco', meaning: 'recently', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'da tanto', meaning: 'for a long time', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'di solito', meaning: 'usually', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'solitamente', meaning: 'usually', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'abitualmente', meaning: 'habitually', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'giornalmente', meaning: 'daily', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'settimanalmente', meaning: 'weekly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'mensilmente', meaning: 'monthly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'annualmente', meaning: 'annually', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'continuamente', meaning: 'continually', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'costantemente', meaning: 'constantly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'spesso', meaning: 'often', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'talvolta', meaning: 'sometimes', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'qualche volta', meaning: 'sometimes', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'alcune volte', meaning: 'some times', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'lentamente', meaning: 'slowly', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'velocemente', meaning: 'quickly', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'rapidamente', meaning: 'rapidly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'frettolosamente', meaning: 'hastily', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'chiaramente', meaning: 'clearly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'ovviamente', meaning: 'obviously', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'sicuramente', meaning: 'surely', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'certamente', meaning: 'certainly', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'probabilmente', meaning: 'probably', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'possibilmente', meaning: 'possibly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'eventualmente', meaning: 'possibly, if necessary', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'specialmente', meaning: 'especially', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'soprattutto', meaning: 'above all, especially', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'particolarmente', meaning: 'particularly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'esattamente', meaning: 'exactly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'precisamente', meaning: 'precisely', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'giustamente', meaning: 'rightly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'erroneamente', meaning: 'erroneously', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'completamente', meaning: 'completely', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'totalmente', meaning: 'totally', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'interamente', meaning: 'entirely', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'parzialmente', meaning: 'partially', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'assolutamente', meaning: 'absolutely', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'veramente', meaning: 'truly', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'realiamente', meaning: 'really', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'semplicemente', meaning: 'simply', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'facilmente', meaning: 'easily', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'difficilmente', meaning: 'hardly, with difficulty', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'fortemente', meaning: 'strongly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'debolmente', meaning: 'weakly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'gentilmente', meaning: 'kindly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'cortesemente', meaning: 'politely', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'maleducatamente', meaning: 'rudely', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'coraggiosamente', meaning: 'bravely', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'pairosamente', meaning: 'fearfully', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'tristemente', meaning: 'sadly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'felicemente', meaning: 'happily', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'allegremente', meaning: 'cheerfully', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'seriamente', meaning: 'seriously', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'duramente', meaning: 'hardly, harshly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'dolcemente', meaning: 'sweetly, gently', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'amaremente', meaning: 'bitterly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'frequentemente', meaning: 'frequently', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'raramente', meaning: 'rarely', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'improvvisamente', meaning: 'suddenly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'all\'improvviso', meaning: 'suddenly', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'invece', meaning: 'instead', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'però', meaning: 'however', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'eppure', meaning: 'yet', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'tuttavia', meaning: 'nevertheless', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'perciò', meaning: 'therefore', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'quindi', meaning: 'so, therefore', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'allora', meaning: 'then', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'dunque', meaning: 'so, then', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'pertanto', meaning: 'therefore', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'ossia', meaning: 'that is', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'cioè', meaning: 'that is, I mean', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'insomma', meaning: 'in short', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'appunto', meaning: 'exactly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'pure', meaning: 'also, even', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'neppure', meaning: 'not even', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'nemmeno', meaning: 'not even', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'neanche', meaning: 'not even', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'mica', meaning: 'not at all', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'affatto', meaning: 'at all', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'punto', meaning: 'at all (after negative)', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'già', meaning: 'already', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'non ancora', meaning: 'not yet', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'ancora', meaning: 'still, again', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'piuttosto', meaning: 'rather', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'abbastanza', meaning: 'enough', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'parecchio', meaning: 'a lot, quite a bit', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'assai', meaning: 'very, enough', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'altrettanto', meaning: 'likewise', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'perfino', meaning: 'even', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'persino', meaning: 'even', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'addirittura', meaning: 'even, directly', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'quasi', meaning: 'almost', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'forse', meaning: 'maybe', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'probabilmente', meaning: 'probably', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'certamente', meaning: 'certainly', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'sicuramente', meaning: 'surely', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'davvero', meaning: 'really', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'proprio', meaning: 'really, exactly', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'apposta', meaning: 'on purpose', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'volontieri', meaning: 'gladly', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'invano', meaning: 'in vain', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'insieme', meaning: 'together', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'separatamente', meaning: 'separately', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'ovunque', meaning: 'everywhere', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'dovunque', meaning: 'wherever', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'comunque', meaning: 'anyway, however', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'altrove', meaning: 'elsewhere', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'dove', meaning: 'where', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'come', meaning: 'how', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'quando', meaning: 'when', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'quanto', meaning: 'how much', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'perché', meaning: 'why', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'benissimo', meaning: 'very well', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'malissimo', meaning: 'very badly', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'pianissimo', meaning: 'very slowly/softly', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'fortissimo', meaning: 'very loudly/strongly', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'prestissimo', meaning: 'very early/soon', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'tardissimo', meaning: 'very late', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'pochissimo', meaning: 'very little', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'moltissimo', meaning: 'very much', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'almeno', meaning: 'at least', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'soltanto', meaning: 'only', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'anzi', meaning: 'on the contrary', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'nemmeno', meaning: 'neither', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'chiunque', meaning: 'whoever', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'qualunque', meaning: 'whatever', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'comunque', meaning: 'however', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'dunque', meaning: 'well, then', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'ebbene', meaning: 'well, then', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'già', meaning: 'already', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'ancora', meaning: 'again', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'spesso', meaning: 'often', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'di nuovo', meaning: 'again', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'per tempo', meaning: 'in time', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'a lungo', meaning: 'at length', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'd\'un tratto', meaning: 'all of a sudden', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'per caso', meaning: 'by chance', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'per fortuna', meaning: 'luckily', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'purtroppo', meaning: 'unfortunately', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'per forza', meaning: 'by necessity', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'invano', meaning: 'in vain', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'senza dubbio', meaning: 'without doubt', partOfSpeech: 'adverb', isBeginner: true },
  { lemma: 'all\'incirca', meaning: 'approximately', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'pressappoco', meaning: 'approximately', partOfSpeech: 'adverb', isBeginner: false },
  { lemma: 'quasi quasi', meaning: 'almost (indicating hesitation)', partOfSpeech: 'adverb', isBeginner: false }
];
