// ~20 common Italian conjunctions
export const conjunctions = [
	{ lemma: 'e', meaning: 'and', partOfSpeech: 'conjunction', isBeginner: true },
	{ lemma: 'ma', meaning: 'but', partOfSpeech: 'conjunction', isBeginner: true },
	{ lemma: 'o', meaning: 'or', partOfSpeech: 'conjunction', isBeginner: true },
	{ lemma: 'perché', meaning: 'because, why', partOfSpeech: 'conjunction', isBeginner: true },
	{ lemma: 'quando', meaning: 'when', partOfSpeech: 'conjunction', isBeginner: true },
	{ lemma: 'che', meaning: 'that, which', partOfSpeech: 'conjunction', isBeginner: true },
	{ lemma: 'se', meaning: 'if', partOfSpeech: 'conjunction', isBeginner: true },
	{ lemma: 'però', meaning: 'however, but', partOfSpeech: 'conjunction', isBeginner: true },
	{ lemma: 'quindi', meaning: 'so, therefore', partOfSpeech: 'conjunction', isBeginner: true },
	{ lemma: 'anche', meaning: 'also', partOfSpeech: 'conjunction', isBeginner: true },
	{ lemma: 'mentre', meaning: 'while', partOfSpeech: 'conjunction', isBeginner: true },
	{ lemma: 'dopo che', meaning: 'after', partOfSpeech: 'conjunction', isBeginner: true },
	{ lemma: 'prima che', meaning: 'before', partOfSpeech: 'conjunction', isBeginner: true },
	{ lemma: 'sebbene', meaning: 'although', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'finché', meaning: 'as long as', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'appena', meaning: 'as soon as', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'poiché', meaning: 'since, because', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'affinché', meaning: 'so that', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'né', meaning: 'neither, nor', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'oppure', meaning: 'or, otherwise', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'siccome', meaning: 'since', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'dato che', meaning: 'given that', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'visto che', meaning: 'since', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'nonostante', meaning: 'despite', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'benché', meaning: 'although', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'purché', meaning: 'provided that', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'a meno che', meaning: 'unless', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'tranne che', meaning: 'except that', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'oltre a', meaning: 'in addition to', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'invece', meaning: 'instead', partOfSpeech: 'conjunction', isBeginner: true },
	{ lemma: 'tuttavia', meaning: 'however', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'perciò', meaning: 'therefore', partOfSpeech: 'conjunction', isBeginner: false },
	{
		lemma: 'di conseguenza',
		meaning: 'consequently',
		partOfSpeech: 'conjunction',
		isBeginner: false
	},
	{ lemma: 'ossia', meaning: 'that is', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'ovvero', meaning: 'or, that is', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'sin da quando', meaning: 'ever since', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'eccetto', meaning: 'except', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'salvo', meaning: 'except', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'come', meaning: 'as', partOfSpeech: 'conjunction', isBeginner: true },
	{ lemma: 'come se', meaning: 'as if', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'malgrado', meaning: 'despite', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'sia... sia', meaning: 'both... and', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'mentre invece', meaning: 'whereas', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'senza che', meaning: 'without', partOfSpeech: 'conjunction', isBeginner: false },
	{ lemma: 'nel caso in cui', meaning: 'in case', partOfSpeech: 'conjunction', isBeginner: false }
];
