// Common Italian interjections
export const interjections = [
  { lemma: 'ciao', meaning: 'hello, hi, bye', partOfSpeech: 'interjection', isBeginner: true },
  { lemma: 'grazie', meaning: 'thank you', partOfSpeech: 'interjection', isBeginner: true },
  { lemma: 'prego', meaning: 'you’re welcome', partOfSpeech: 'interjection', isBeginner: true },
  { lemma: 'scusa', meaning: 'excuse me, sorry', partOfSpeech: 'interjection', isBeginner: true },
  { lemma: 'salve', meaning: 'hello', partOfSpeech: 'interjection', isBeginner: true },
  { lemma: 'arrivederci', meaning: 'goodbye', partOfSpeech: 'interjection', isBeginner: true },
  { lemma: 'addio', meaning: 'farewell', partOfSpeech: 'interjection', isBeginner: false },
  { lemma: 'auguri', meaning: 'congratulations, best wishes', partOfSpeech: 'interjection', isBeginner: true },
  { lemma: 'forza', meaning: 'come on!', partOfSpeech: 'interjection', isBeginner: true },
  { lemma: 'aiuto', meaning: 'help!', partOfSpeech: 'interjection', isBeginner: true },
  { lemma: 'attenzione', meaning: 'attention!', partOfSpeech: 'interjection', isBeginner: false },
  { lemma: 'basta', meaning: 'enough!', partOfSpeech: 'interjection', isBeginner: true },
  { lemma: 'dai', meaning: 'come on!', partOfSpeech: 'interjection', isBeginner: true },
  { lemma: 'evviva', meaning: 'hooray!', partOfSpeech: 'interjection', isBeginner: false },
  { lemma: 'mah', meaning: 'meh, who knows', partOfSpeech: 'interjection', isBeginner: false },
  { lemma: 'oh', meaning: 'oh', partOfSpeech: 'interjection', isBeginner: true },
  { lemma: 'uffa', meaning: 'phew, ugh', partOfSpeech: 'interjection', isBeginner: true },
  { lemma: 'peccato', meaning: 'too bad', partOfSpeech: 'interjection', isBeginner: true },
  { lemma: 'salute', meaning: 'bless you', partOfSpeech: 'interjection', isBeginner: true },
  { lemma: 'figurati', meaning: "don't mention it", partOfSpeech: 'interjection', isBeginner: false },
  { lemma: 'assolutamente', meaning: 'absolutely', partOfSpeech: 'interjection', isBeginner: false },
  { lemma: 'd\'accordo', meaning: 'agreed', partOfSpeech: 'interjection', isBeginner: true }
];
