// ~80 common Italian nouns with gender and plural
export const nouns = [
  { lemma: 'uomo', meaning: 'man', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'uomini', isBeginner: true },
  { lemma: 'donna', meaning: 'woman', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'donne', isBeginner: true },
  { lemma: 'ragazzo', meaning: 'boy', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'ragazzi', isBeginner: true },
  { lemma: 'ragazza', meaning: 'girl', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'ragazze', isBeginner: true },
  { lemma: 'bambino', meaning: 'child (boy)', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'bambini', isBeginner: true },
  { lemma: 'bambina', meaning: 'child (girl)', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'bambine', isBeginner: true },
  { lemma: 'amico', meaning: 'friend (male)', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'amici', isBeginner: true },
  { lemma: 'amica', meaning: 'friend (female)', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'amiche', isBeginner: true },
  { lemma: 'famiglia', meaning: 'family', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'famiglie', isBeginner: true },
  { lemma: 'madre', meaning: 'mother', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'madri', isBeginner: true },
  { lemma: 'padre', meaning: 'father', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'padri', isBeginner: true },
  { lemma: 'fratello', meaning: 'brother', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'fratelli', isBeginner: true },
  { lemma: 'sorella', meaning: 'sister', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'sorelle', isBeginner: true },
  { lemma: 'figlio', meaning: 'son', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'figli', isBeginner: true },
  { lemma: 'figlia', meaning: 'daughter', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'figlie', isBeginner: true },
  { lemma: 'marito', meaning: 'husband', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'mariti', isBeginner: true },
  { lemma: 'moglie', meaning: 'wife', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'mogli', isBeginner: true },
  { lemma: 'persona', meaning: 'person', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'persone', isBeginner: true },
  { lemma: 'amore', meaning: 'love', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'amori', isBeginner: true },
  { lemma: 'tempo', meaning: 'time, weather', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'tempi', isBeginner: true },
  { lemma: 'giorno', meaning: 'day', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'giorni', isBeginner: true },
  { lemma: 'notte', meaning: 'night', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'notti', isBeginner: true },
  { lemma: 'mattina', meaning: 'morning', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'mattine', isBeginner: true },
  { lemma: 'sera', meaning: 'evening', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'sere', isBeginner: true },
  { lemma: 'anno', meaning: 'year', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'anni', isBeginner: true },
  { lemma: 'mese', meaning: 'month', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'mesi', isBeginner: true },
  { lemma: 'settimana', meaning: 'week', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'settimane', isBeginner: true },
  { lemma: 'ora', meaning: 'hour', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'ore', isBeginner: true },
  { lemma: 'minuto', meaning: 'minute', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'minuti', isBeginner: true },
  { lemma: 'secondo', meaning: 'second', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'secondi', isBeginner: true },
  { lemma: 'casa', meaning: 'house, home', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'case', isBeginner: true },
  { lemma: 'appartamento', meaning: 'apartment', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'appartamenti', isBeginner: true },
  { lemma: 'camera', meaning: 'room', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'camere', isBeginner: true },
  { lemma: 'letto', meaning: 'bed', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'letti', isBeginner: true },
  { lemma: 'porta', meaning: 'door', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'porte', isBeginner: true },
  { lemma: 'finestra', meaning: 'window', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'finestre', isBeginner: true },
  { lemma: 'sedia', meaning: 'chair', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'sedie', isBeginner: true },
  { lemma: 'tavolo', meaning: 'table', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'tavoli', isBeginner: true },
  { lemma: 'bagno', meaning: 'bathroom', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'bagni', isBeginner: true },
  { lemma: 'cucina', meaning: 'kitchen', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'cucine', isBeginner: true },
  { lemma: 'scuola', meaning: 'school', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'scuole', isBeginner: true },
  { lemma: 'università', meaning: 'university', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'università', isBeginner: true },
  { lemma: 'lavoro', meaning: 'work, job', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'lavori', isBeginner: true },
  { lemma: 'strada', meaning: 'street', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'strade', isBeginner: true },
  { lemma: 'città', meaning: 'city', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'città', isBeginner: true },
  { lemma: 'paese', meaning: 'country, village', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'paesi', isBeginner: true },
  { lemma: 'negozio', meaning: 'shop, store', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'negozi', isBeginner: true },
  { lemma: 'mercato', meaning: 'market', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'mercati', isBeginner: true },
  { lemma: 'ospedale', meaning: 'hospital', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'ospedali', isBeginner: true },
  { lemma: 'farmacia', meaning: 'pharmacy', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'farmacie', isBeginner: true },
  { lemma: 'banca', meaning: 'bank', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'banche', isBeginner: true },
  { lemma: 'posta', meaning: 'post office', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'poste', isBeginner: true },
  { lemma: 'scuola', meaning: 'school', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'scuole', isBeginner: true },
  { lemma: 'macchina', meaning: 'car', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'macchine', isBeginner: true },
  { lemma: 'treno', meaning: 'train', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'treni', isBeginner: true },
  { lemma: 'aereo', meaning: 'airplane', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'aerei', isBeginner: true },
  { lemma: 'autobus', meaning: 'bus', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'autobus', isBeginner: true },
  { lemma: 'bicicletta', meaning: 'bicycle', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'biciclette', isBeginner: true },
  { lemma: 'pane', meaning: 'bread', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'pani', isBeginner: true },
  { lemma: 'acqua', meaning: 'water', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'acque', isBeginner: true },
  { lemma: 'vino', meaning: 'wine', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'vini', isBeginner: true },
  { lemma: 'latte', meaning: 'milk', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'latti', isBeginner: true },
  { lemma: 'caffè', meaning: 'coffee', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'caffè', isBeginner: true },
  { lemma: 'tè', meaning: 'tea', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'tè', isBeginner: true },
  { lemma: 'frutta', meaning: 'fruit', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'frutte', isBeginner: true },
  { lemma: 'verdura', meaning: 'vegetable', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'verdure', isBeginner: true },
  { lemma: 'carne', meaning: 'meat', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'carni', isBeginner: true },
  { lemma: 'pesce', meaning: 'fish', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'pesci', isBeginner: true },
  { lemma: 'formaggio', meaning: 'cheese', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'formaggi', isBeginner: true },
  { lemma: 'uovo', meaning: 'egg', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'uova', isBeginner: true },
  { lemma: 'zucchero', meaning: 'sugar', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'zuccheri', isBeginner: true },
  { lemma: 'sale', meaning: 'salt', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'sali', isBeginner: true },
  { lemma: 'piatto', meaning: 'plate, dish', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'piatti', isBeginner: true },
  { lemma: 'bicchiere', meaning: 'glass', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'bicchieri', isBeginner: true },
  { lemma: 'coltello', meaning: 'knife', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'coltelli', isBeginner: true },
  { lemma: 'forchetta', meaning: 'fork', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'forchette', isBeginner: true },
  { lemma: 'cucchiaio', meaning: 'spoon', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'cucchiai', isBeginner: true },
  { lemma: 'mano', meaning: 'hand', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'mani', isBeginner: true },
  { lemma: 'testa', meaning: 'head', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'teste', isBeginner: true },
  { lemma: 'occhio', meaning: 'eye', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'occhi', isBeginner: true },
  { lemma: 'bocca', meaning: 'mouth', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'bocche', isBeginner: true },
  { lemma: 'naso', meaning: 'nose', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'nasi', isBeginner: true },
  { lemma: 'orecchio', meaning: 'ear', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'orecchie', isBeginner: true },
  { lemma: 'piede', meaning: 'foot', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'piedi', isBeginner: true },
  { lemma: 'gamba', meaning: 'leg', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'gambe', isBeginner: true },
  { lemma: 'cuore', meaning: 'heart', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'cuori', isBeginner: true },
  { lemma: 'corpo', meaning: 'body', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'corpi', isBeginner: true },
  { lemma: 'faccia', meaning: 'face', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'facce', isBeginner: true },
  { lemma: 'capello', meaning: 'hair', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'capelli', isBeginner: true },
  { lemma: 'dente', meaning: 'tooth', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'denti', isBeginner: true },
  { lemma: 'occhio', meaning: 'eye', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'occhi', isBeginner: true },
  { lemma: 'lingua', meaning: 'tongue, language', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'lingue', isBeginner: true },
  { lemma: 'voce', meaning: 'voice', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'voci', isBeginner: true },
  { lemma: 'nome', meaning: 'name', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'nomi', isBeginner: true },
  { lemma: 'numero', meaning: 'number', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'numeri', isBeginner: true },
  { lemma: 'colore', meaning: 'color', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'colori', isBeginner: true },
  { lemma: 'soldi', meaning: 'money', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'soldi', isBeginner: true },
  { lemma: 'domanda', meaning: 'question', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'domande', isBeginner: true },
  { lemma: 'risposta', meaning: 'answer', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'risposte', isBeginner: true },
  { lemma: 'problema', meaning: 'problem', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'problemi', isBeginner: true },
  { lemma: 'idea', meaning: 'idea', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'idee', isBeginner: true },
  { lemma: 'storia', meaning: 'story, history', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'storie', isBeginner: true },
  { lemma: 'gioco', meaning: 'game', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'giochi', isBeginner: true },
  { lemma: 'musica', meaning: 'music', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'musiche', isBeginner: true },
  { lemma: 'film', meaning: 'movie', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'film', isBeginner: true },
  { lemma: 'foto', meaning: 'photo', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'foto', isBeginner: true },
  { lemma: 'telefono', meaning: 'phone', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'telefoni', isBeginner: true },
  { lemma: 'computer', meaning: 'computer', partOfSpeech: 'noun', gender: 'MASCULINE', plural: 'computer', isBeginner: true },
  { lemma: 'chiave', meaning: 'key', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'chiavi', isBeginner: true },
  { lemma: 'porta', meaning: 'door', partOfSpeech: 'noun', gender: 'FEMININE', plural: 'porte', isBeginner: true }
];
