// ~15 common Italian prepositions
export const prepositions = [
  { lemma: 'di', meaning: 'of', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'a', meaning: 'to, at', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'da', meaning: 'from, by', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'in', meaning: 'in', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'con', meaning: 'with', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'su', meaning: 'on', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'per', meaning: 'for', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'tra', meaning: 'between', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'fra', meaning: 'among', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'verso', meaning: 'towards', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'sopra', meaning: 'above', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'sotto', meaning: 'under', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'senza', meaning: 'without', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'dentro', meaning: 'inside', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'fuori', meaning: 'outside', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'durante', meaning: 'during', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'contro', meaning: 'against', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'dietro', meaning: 'behind', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'davanti', meaning: 'in front of', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'dopo', meaning: 'after', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'prima', meaning: 'before', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'secondo', meaning: 'according to', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'circa', meaning: 'about', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'entro', meaning: 'within', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'oltre', meaning: 'beyond', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'presso', meaning: 'at, near', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'lungo', meaning: 'along', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'tramite', meaning: 'through', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'attraverso', meaning: 'across', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'del', meaning: 'of the (m.s.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'dello', meaning: 'of the (m.s. s+cons)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'dell\'', meaning: 'of the (m./f.s. vowel)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'della', meaning: 'of the (f.s.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'dei', meaning: 'of the (m.p.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'degli', meaning: 'of the (m.p. special)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'delle', meaning: 'of the (f.p.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'al', meaning: 'to the (m.s.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'allo', meaning: 'to the (m.s. s+cons)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'all\'', meaning: 'to the (m./f.s. vowel)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'alla', meaning: 'to the (f.s.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'ai', meaning: 'to the (m.p.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'agli', meaning: 'to the (m.p. special)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'alle', meaning: 'to the (f.p.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'dal', meaning: 'from the (m.s.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'dallo', meaning: 'from the (m.s. s+cons)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'dall\'', meaning: 'from the (m./f.s. vowel)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'dalla', meaning: 'from the (f.s.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'dai', meaning: 'from the (m.p.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'dagli', meaning: 'from the (m.p. special)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'daglie', meaning: 'from the (f.p.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'nel', meaning: 'in the (m.s.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'nello', meaning: 'in the (m.s. s+cons)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'nell\'', meaning: 'in the (m./f.s. vowel)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'nella', meaning: 'in the (f.s.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'nei', meaning: 'in the (m.p.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'negli', meaning: 'in the (m.p. special)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'nelle', meaning: 'in the (f.p.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'sul', meaning: 'on the (m.s.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'sullo', meaning: 'on the (m.s. s+cons)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'sull\'', meaning: 'on the (m./f.s. vowel)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'sulla', meaning: 'on the (f.s.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'sui', meaning: 'on the (m.p.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'sugli', meaning: 'on the (m.p. special)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'sulle', meaning: 'on the (f.p.)', partOfSpeech: 'preposition', isBeginner: true },
  { lemma: 'col', meaning: 'with the (m.s.)', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'coi', meaning: 'with the (m.p.)', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'mediante', meaning: 'by means of', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'nonostante', meaning: 'despite', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'eccetto', meaning: 'except', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'tranne', meaning: 'except', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'salvo', meaning: 'except', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'accanto', meaning: 'next to', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'attorno', meaning: 'around', partOfSpeech: 'preposition', isBeginner: false },
  { lemma: 'fin', meaning: 'until', partOfSpeech: 'preposition', isBeginner: false }
];
