// ~360 essential Italian verbs for A1–C1 learners
export const verbs = [
	{ lemma: 'essere', meaning: 'to be', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'avere', meaning: 'to have', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'fare', meaning: 'to do, to make', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'andare', meaning: 'to go', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'venire', meaning: 'to come', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'potere', meaning: 'can, to be able to', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'volere', meaning: 'to want', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'dovere', meaning: 'must, to have to', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'sapere', meaning: 'to know (a fact)', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'stare', meaning: 'to stay, to be', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'dare', meaning: 'to give', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'dire', meaning: 'to say, to tell', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'vedere', meaning: 'to see', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'parlare', meaning: 'to speak', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'trovare', meaning: 'to find', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'lasciare', meaning: 'to leave', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'prendere', meaning: 'to take', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'mettere', meaning: 'to put', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'sentire', meaning: 'to hear, to feel', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'vivere', meaning: 'to live', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'chiedere', meaning: 'to ask', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'lavorare', meaning: 'to work', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'amare', meaning: 'to love', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'guardare', meaning: 'to watch, to look at', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'mangiare', meaning: 'to eat', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'bere', meaning: 'to drink', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'scrivere', meaning: 'to write', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'leggere', meaning: 'to read', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'dormire', meaning: 'to sleep', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'finire', meaning: 'to finish', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'capire', meaning: 'to understand', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'aprire', meaning: 'to open', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'chiudere', meaning: 'to close', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'correre', meaning: 'to run', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'giocare', meaning: 'to play', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'studiare', meaning: 'to study', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'comprare', meaning: 'to buy', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'pagare', meaning: 'to pay', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'guidare', meaning: 'to drive', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'viaggiare', meaning: 'to travel', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'arrivare', meaning: 'to arrive', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'partire', meaning: 'to leave, to depart', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'entrare', meaning: 'to enter', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'uscire', meaning: 'to go out', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'salire', meaning: 'to go up', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'scendere', meaning: 'to go down', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'restare', meaning: 'to stay', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'portare', meaning: 'to bring, to carry', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'incontrare', meaning: 'to meet', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'perdere', meaning: 'to lose', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'cercare', meaning: 'to search, to look for', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'spiegare', meaning: 'to explain', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'seguire', meaning: 'to follow', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'preferire', meaning: 'to prefer', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'costruire', meaning: 'to build', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'pulire', meaning: 'to clean', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'spedire', meaning: 'to send', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'morire', meaning: 'to die', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'ridere', meaning: 'to laugh', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'piangere', meaning: 'to cry', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'scegliere', meaning: 'to choose', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'diventare', meaning: 'to become', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'provare', meaning: 'to try', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'usare', meaning: 'to use', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'camminare', meaning: 'to walk', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'ballare', meaning: 'to dance', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'cantare', meaning: 'to sing', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'suonare', meaning: 'to play (instrument)', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'disegnare', meaning: 'to draw', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'dipingere', meaning: 'to paint', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'nuotare', meaning: 'to swim', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'volare', meaning: 'to fly', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'saltare', meaning: 'to jump', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'cadere', meaning: 'to fall', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'alzarsi', meaning: 'to get up', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'sedersi', meaning: 'to sit down', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'sdraiarsi', meaning: 'to lie down', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'fermarsi', meaning: 'to stop', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'muoversi', meaning: 'to move', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'girare', meaning: 'to turn', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'tornare', meaning: 'to return', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'ritornare', meaning: 'to return', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'aspettare', meaning: 'to wait', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'sperare', meaning: 'to hope', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'credere', meaning: 'to believe', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'pensare', meaning: 'to think', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'ricordare', meaning: 'to remember', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'dimenticare', meaning: 'to forget', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'imparare', meaning: 'to learn', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'insegnare', meaning: 'to teach', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'mostrare', meaning: 'to show', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'nascondere', meaning: 'to hide', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'permettere', meaning: 'to allow', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'vietare', meaning: 'to forbid', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'ordinare', meaning: 'to order', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'comandare', meaning: 'to command', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'obbedire', meaning: 'to obey', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'ribellarsi', meaning: 'to rebel', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'vincere', meaning: 'to win', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'perdere', meaning: 'to lose', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'battere', meaning: 'to beat, to hit', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'colpire', meaning: 'to strike, to hit', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'rompere', meaning: 'to break', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'riparare', meaning: 'to repair', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'aggiustare', meaning: 'to fix', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'costare', meaning: 'to cost', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'valere', meaning: 'to be worth', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'offrire', meaning: 'to offer', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'accettare', meaning: 'to accept', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'rifiutare', meaning: 'to refuse', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'ringraziare', meaning: 'to thank', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'scusarsi', meaning: 'to apologize', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'perdonare', meaning: 'to forgive', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'aiutare', meaning: 'to help', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'disturbare', meaning: 'to disturb', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'promettere', meaning: 'to promise', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'mantenere', meaning: 'to maintain, to keep', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'cambiare', meaning: 'to change', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'trasformare', meaning: 'to transform', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'migliorare', meaning: 'to improve', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'peggiorare', meaning: 'to worsen', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'crescere', meaning: 'to grow', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'diminuire', meaning: 'to decrease', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'aumentare', meaning: 'to increase', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'nascere', meaning: 'to be born', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'vivere', meaning: 'to live', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'abitare', meaning: 'to live (dwell)', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'viaggiare', meaning: 'to travel', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'visitare', meaning: 'to visit', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'esplorare', meaning: 'to explore', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'scoprire', meaning: 'to discover', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'inventare', meaning: 'to invent', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'creare', meaning: 'to create', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'distruggere', meaning: 'to destroy', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'uccidere', meaning: 'to kill', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'salvare', meaning: 'to save', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'proteggere', meaning: 'to protect', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'difendere', meaning: 'to defend', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'attaccare', meaning: 'to attack', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'combattere', meaning: 'to fight', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'vincere', meaning: 'to win', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'arrendersi', meaning: 'to surrender', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'ridere', meaning: 'to laugh', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'sorridere', meaning: 'to smile', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'piangere', meaning: 'to cry', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'urlare', meaning: 'to scream', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'gridare', meaning: 'to shout', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'sussurrare', meaning: 'to whisper', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'tacere', meaning: 'to be silent', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'ascoltare', meaning: 'to listen', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'sentire', meaning: 'to hear/feel', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'odorare', meaning: 'to smell', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'toccare', meaning: 'to touch', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'assaggiare', meaning: 'to taste', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'gustare', meaning: 'to taste/enjoy', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'masticare', meaning: 'to chew', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'inghiottire', meaning: 'to swallow', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'digerire', meaning: 'to digest', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'respirare', meaning: 'to breathe', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'tossire', meaning: 'to cough', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'starnutire', meaning: 'to sneeze', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'sudare', meaning: 'to sweat', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'tremare', meaning: 'to tremble', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'dormire', meaning: 'to sleep', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'sognare', meaning: 'to dream', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'svegliarsi', meaning: 'to wake up', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'riposarsi', meaning: 'to rest', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'stancarsi', meaning: 'to get tired', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'lavarsi', meaning: 'to wash oneself', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'farsi la doccia', meaning: 'to take a shower', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'vestirsi', meaning: 'to get dressed', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'spogliarsi', meaning: 'to undress', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'pettinarsi', meaning: "to comb one's hair", partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'truccarsi', meaning: 'to put on makeup', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'radersi', meaning: 'to shave', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'cucinare', meaning: 'to cook', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'preparare', meaning: 'to prepare', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'apparecchiare', meaning: 'to set the table', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'sparecchiare', meaning: 'to clear the table', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'pulire', meaning: 'to clean', partOfSpeech: 'verb', isBeginner: true },
	{
		lemma: 'lavare i piatti',
		meaning: 'to wash the dishes',
		partOfSpeech: 'verb',
		isBeginner: true
	},
	{ lemma: 'spazzare', meaning: 'to sweep', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'stirare', meaning: 'to iron', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'ordinare', meaning: 'to tidy up', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'comprare', meaning: 'to buy', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'vendere', meaning: 'to sell', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'pagare', meaning: 'to pay', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'spendere', meaning: 'to spend', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'risparmiare', meaning: 'to save money', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'guadagnare', meaning: 'to earn', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'lavorare', meaning: 'to work', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'studiare', meaning: 'to study', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'scrivere', meaning: 'to write', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'leggere', meaning: 'to read', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'contare', meaning: 'to count', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'calcolare', meaning: 'to calculate', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'misurare', meaning: 'to measure', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'pesare', meaning: 'to weigh', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'pensare', meaning: 'to think', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'ragionare', meaning: 'to reason', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'immaginare', meaning: 'to imagine', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'supporre', meaning: 'to suppose', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'capire', meaning: 'to understand', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'comprendere', meaning: 'to comprehend', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'sapere', meaning: 'to know', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'conoscere', meaning: 'to know (person/place)', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'riconoscere', meaning: 'to recognize', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'decidere', meaning: 'to decide', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'scegliere', meaning: 'to choose', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'preferire', meaning: 'to prefer', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'amare', meaning: 'to love', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'odiare', meaning: 'to hate', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'detestare', meaning: 'to detest', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'piacere', meaning: 'to like', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'dispiacere', meaning: 'to be sorry', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'divertirsi', meaning: 'to have fun', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'annoiarsi', meaning: 'to be bored', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'interessarsi', meaning: 'to be interested', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'preoccuparsi', meaning: 'to worry', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'spaventarsi', meaning: 'to be frightened', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'sorprendersi', meaning: 'to be surprised', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'meravigliarsi', meaning: 'to wonder', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'arrabbiarsi', meaning: 'to get angry', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'offendersi', meaning: 'to take offense', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'vergognarsi', meaning: 'to be ashamed', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'pentirsi', meaning: 'to repent', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'confidare', meaning: 'to trust/confide', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'fidarsi', meaning: 'to trust', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'dubitare', meaning: 'to doubt', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'sospettare', meaning: 'to suspect', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'giudicare', meaning: 'to judge', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'criticare', meaning: 'to criticize', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'lodare', meaning: 'to praise', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'ammirare', meaning: 'to admire', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'rispettare', meaning: 'to respect', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'insultare', meaning: 'to insult', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'minacciare', meaning: 'to threaten', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'punire', meaning: 'to punish', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'premiare', meaning: 'to reward', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'celebrare', meaning: 'to celebrate', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'festeggiare', meaning: 'to celebrate', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'invitare', meaning: 'to invite', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'ospitare', meaning: 'to host', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'partecipare', meaning: 'to participate', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'incontrare', meaning: 'to meet', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'conoscere', meaning: 'to get to know', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'frequentare', meaning: 'to frequent/attend', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'lasciare', meaning: 'to leave', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'abbandonare', meaning: 'to abandon', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'perdere', meaning: 'to lose', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'ritrovare', meaning: 'to find again', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'cercare', meaning: 'to look for', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'trovare', meaning: 'to find', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'ottenere', meaning: 'to obtain', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'ricevere', meaning: 'to receive', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'mandare', meaning: 'to send', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'inviare', meaning: 'to send', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'consegnare', meaning: 'to deliver', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'restituire', meaning: 'to return (object)', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'prestare', meaning: 'to lend', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'prendere in prestito', meaning: 'to borrow', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'rubare', meaning: 'to steal', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'togliere', meaning: 'to take away', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'aggiungere', meaning: 'to add', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'unire', meaning: 'to unite', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'dividere', meaning: 'to divide', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'separare', meaning: 'to separate', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'mescolare', meaning: 'to mix', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'riempire', meaning: 'to fill', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'svuotare', meaning: 'to empty', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'aprire', meaning: 'to open', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'chiudere', meaning: 'to close', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'accendere', meaning: 'to turn on', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'spegnere', meaning: 'to turn off', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'alzare', meaning: 'to raise', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'abbassare', meaning: 'to lower', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'spingere', meaning: 'to push', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'tirare', meaning: 'to pull', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'portare', meaning: 'to bring', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'trasportare', meaning: 'to transport', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'sollevare', meaning: 'to lift', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'appoggiare', meaning: 'to lean/put down', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'cadere', meaning: 'to fall', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'scivolare', meaning: 'to slip', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'volare', meaning: 'to fly', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'nuotare', meaning: 'to swim', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'guidare', meaning: 'to drive', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'cavalcare', meaning: 'to ride', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'pedalare', meaning: 'to pedal', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'viaggiare', meaning: 'to travel', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'navigare', meaning: 'to navigate/surf', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'comunicare', meaning: 'to communicate', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'telefonare', meaning: 'to call', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'chattare', meaning: 'to chat', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'cliccare', meaning: 'to click', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'digitare', meaning: 'to type', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'stampare', meaning: 'to print', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'salvare', meaning: 'to save (file)', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'cancellare', meaning: 'to delete', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'copiare', meaning: 'to copy', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'incollare', meaning: 'to paste', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'tagliare', meaning: 'to cut', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'cucire', meaning: 'to sew', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'costruire', meaning: 'to build', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'demolire', meaning: 'to demolish', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'produrre', meaning: 'to produce', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'consumare', meaning: 'to consume', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'usare', meaning: 'to use', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'utilizzare', meaning: 'to utilize', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'funzionare', meaning: 'to work/function', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'durare', meaning: 'to last', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'finire', meaning: 'to finish', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'cominciare', meaning: 'to begin', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'iniziare', meaning: 'to start', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'continuare', meaning: 'to continue', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'smettere', meaning: 'to stop', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'interrompere', meaning: 'to interrupt', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'ritardare', meaning: 'to delay', partOfSpeech: 'verb', isBeginner: false },
	{
		lemma: 'anticipare',
		meaning: 'to anticipate/advance',
		partOfSpeech: 'verb',
		isBeginner: false
	},
	{ lemma: 'accadere', meaning: 'to happen', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'succedere', meaning: 'to happen', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'sembrare', meaning: 'to seem', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'apparire', meaning: 'to appear', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'sparire', meaning: 'to disappear', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'esistere', meaning: 'to exist', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'mancare', meaning: 'to miss/lack', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'bastare', meaning: 'to be enough', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'servire', meaning: 'to serve/be useful', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'bisognare', meaning: 'to be necessary', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'importare', meaning: 'to matter', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'interessare', meaning: 'to interest', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'occuparsi', meaning: 'to deal with', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'preoccuparsi', meaning: 'to worry', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'stancarsi', meaning: 'to get tired', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'annoiarsi', meaning: 'to be bored', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'divertirsi', meaning: 'to have fun', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'innamorarsi', meaning: 'to fall in love', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'sposarsi', meaning: 'to get married', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'divorziare', meaning: 'to divorce', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'nascere', meaning: 'to be born', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'crescere', meaning: 'to grow', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'invecchiare', meaning: 'to get old', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'morire', meaning: 'to die', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'seppellire', meaning: 'to bury', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'piantare', meaning: 'to plant', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'innaffiare', meaning: 'to water', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'raccogliere', meaning: 'to collect/harvest', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'pescare', meaning: 'to fish', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'cacciare', meaning: 'to hunt', partOfSpeech: 'verb', isBeginner: false },
	{
		lemma: 'allevare',
		meaning: 'to raise (animals/children)',
		partOfSpeech: 'verb',
		isBeginner: false
	},
	{ lemma: 'addestrare', meaning: 'to train (animals)', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'allenarsi', meaning: 'to train/practice', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'gareggiare', meaning: 'to compete', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'scommettere', meaning: 'to bet', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'rischiare', meaning: 'to risk', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'evitare', meaning: 'to avoid', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'scappare', meaning: 'to escape', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'fuggire', meaning: 'to flee', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'inseguire', meaning: 'to chase', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'catturare', meaning: 'to capture', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'liberare', meaning: 'to free', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'legare', meaning: 'to tie', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'sciogliere', meaning: 'to melt/untie', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'bruciare', meaning: 'to burn', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'scaldare', meaning: 'to heat', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'raffreddare', meaning: 'to cool', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'ghiacciare', meaning: 'to freeze', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'bollire', meaning: 'to boil', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'cuocere', meaning: 'to cook/bake', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'friggere', meaning: 'to fry', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'arrostire', meaning: 'to roast', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'aggiungere', meaning: 'to add', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'dividere', meaning: 'to divide', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'moltiplicare', meaning: 'to multiply', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'sottrarre', meaning: 'to subtract', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'calcolare', meaning: 'to calculate', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'misurare', meaning: 'to measure', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'pesare', meaning: 'to weigh', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'valutare', meaning: 'to evaluate', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'giudicare', meaning: 'to judge', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'criticare', meaning: 'to criticize', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'lodare', meaning: 'to praise', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'ammirare', meaning: 'to admire', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'rispettare', meaning: 'to respect', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'onorare', meaning: 'to honor', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'celebrare', meaning: 'to celebrate', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'festeggiare', meaning: 'to celebrate', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'ricordare', meaning: 'to remember', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'dimenticare', meaning: 'to forget', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'ignorare', meaning: 'to ignore', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'trascurare', meaning: 'to neglect', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'abbandonare', meaning: 'to abandon', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'lasciare', meaning: 'to leave', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'perdere', meaning: 'to lose', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'ritrovare', meaning: 'to find again', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'cercare', meaning: 'to look for', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'trovare', meaning: 'to find', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'scoprire', meaning: 'to discover', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'inventare', meaning: 'to invent', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'creare', meaning: 'to create', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'distruggere', meaning: 'to destroy', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'costruire', meaning: 'to build', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'demolire', meaning: 'to demolish', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'riparare', meaning: 'to repair', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'aggiustare', meaning: 'to fix', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'rompere', meaning: 'to break', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'spezzare', meaning: 'to snap/break', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'tagliare', meaning: 'to cut', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'cucire', meaning: 'to sew', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'legare', meaning: 'to tie', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'sciogliere', meaning: 'to melt/untie', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'unire', meaning: 'to unite', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'separare', meaning: 'to separate', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'mescolare', meaning: 'to mix', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'dividere', meaning: 'to divide', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'condividere', meaning: 'to share', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'partecipare', meaning: 'to participate', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'collaborare', meaning: 'to collaborate', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'aiutare', meaning: 'to help', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'sostenere', meaning: 'to support', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'difendere', meaning: 'to defend', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'proteggere', meaning: 'to protect', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'salvare', meaning: 'to save', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'liberare', meaning: 'to free', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'catturare', meaning: 'to capture', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'arrestare', meaning: 'to arrest', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'punire', meaning: 'to punish', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'premiare', meaning: 'to reward', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'perdonare', meaning: 'to forgive', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'scusare', meaning: 'to excuse', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'accusare', meaning: 'to accuse', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'difendersi', meaning: 'to defend oneself', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'arrendersi', meaning: 'to surrender', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'combattere', meaning: 'to fight', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'lottare', meaning: 'to struggle', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'vincere', meaning: 'to win', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'perdere', meaning: 'to lose', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'gareggiare', meaning: 'to compete', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'scommettere', meaning: 'to bet', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'rischiare', meaning: 'to risk', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'osare', meaning: 'to dare', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'provare', meaning: 'to try', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'tentare', meaning: 'to attempt', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'riuscire', meaning: 'to succeed', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'fallire', meaning: 'to fail', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'sbagliare', meaning: 'to make a mistake', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'correggere', meaning: 'to correct', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'migliorare', meaning: 'to improve', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'peggiorare', meaning: 'to worsen', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'cambiare', meaning: 'to change', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'trasformare', meaning: 'to transform', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'mantenere', meaning: 'to keep', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'conservare', meaning: 'to preserve', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'buttare', meaning: 'to throw away', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'gettare', meaning: 'to throw', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'lanciare', meaning: 'to throw/launch', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'prendere', meaning: 'to take', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'afferrare', meaning: 'to grab', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'tenere', meaning: 'to hold', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'lasciare', meaning: 'to let go', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'tirare', meaning: 'to pull', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'spingere', meaning: 'to push', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'sollevare', meaning: 'to lift', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'abbassare', meaning: 'to lower', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'alzare', meaning: 'to raise', partOfSpeech: 'verb', isBeginner: true },
	{ lemma: 'appoggiare', meaning: 'to lean/put down', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'posare', meaning: 'to put down', partOfSpeech: 'verb', isBeginner: false },
	{ lemma: 'mettere', meaning: 'to put', partOfSpeech: 'verb', isBeginner: true }
];
