// ~60 essential Italian verbs for A1–B1 learners
// Gender/plural not needed for verbs
export const verbs = [
  { lemma: 'essere', meaning: 'to be', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'avere', meaning: 'to have', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'fare', meaning: 'to do, to make', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'andare', meaning: 'to go', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'venire', meaning: 'to come', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'potere', meaning: 'can, to be able to', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'volere', meaning: 'to want', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'dovere', meaning: 'must, to have to', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'sapere', meaning: 'to know (a fact)', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'stare', meaning: 'to stay, to be', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'dare', meaning: 'to give', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'dire', meaning: 'to say, to tell', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'vedere', meaning: 'to see', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'parlare', meaning: 'to speak', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'trovare', meaning: 'to find', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'lasciare', meaning: 'to leave', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'prendere', meaning: 'to take', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'mettere', meaning: 'to put', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'sentire', meaning: 'to hear, to feel', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'vivere', meaning: 'to live', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'chiedere', meaning: 'to ask', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'lavorare', meaning: 'to work', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'amare', meaning: 'to love', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'guardare', meaning: 'to watch, to look at', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'mangiare', meaning: 'to eat', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'bere', meaning: 'to drink', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'scrivere', meaning: 'to write', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'leggere', meaning: 'to read', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'dormire', meaning: 'to sleep', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'finire', meaning: 'to finish', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'capire', meaning: 'to understand', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'aprire', meaning: 'to open', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'chiudere', meaning: 'to close', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'correre', meaning: 'to run', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'giocare', meaning: 'to play', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'studiare', meaning: 'to study', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'comprare', meaning: 'to buy', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'pagare', meaning: 'to pay', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'guidare', meaning: 'to drive', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'viaggiare', meaning: 'to travel', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'arrivare', meaning: 'to arrive', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'partire', meaning: 'to leave, to depart', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'entrare', meaning: 'to enter', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'uscire', meaning: 'to go out', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'salire', meaning: 'to go up', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'scendere', meaning: 'to go down', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'restare', meaning: 'to stay', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'portare', meaning: 'to bring, to carry', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'incontrare', meaning: 'to meet', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'perdere', meaning: 'to lose', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'cercare', meaning: 'to search, to look for', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'spiegare', meaning: 'to explain', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'seguire', meaning: 'to follow', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'sentire', meaning: 'to hear, to feel', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'preferire', meaning: 'to prefer', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'costruire', meaning: 'to build', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'pulire', meaning: 'to clean', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'spedire', meaning: 'to send', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'vivere', meaning: 'to live', partOfSpeech: 'verb', isBeginner: true },
  { lemma: 'morire', meaning: 'to die', partOfSpeech: 'verb', isBeginner: false },
  { lemma: 'ridere', meaning: 'to laugh', partOfSpeech: 'verb', isBeginner: false },
  { lemma: 'piangere', meaning: 'to cry', partOfSpeech: 'verb', isBeginner: false },
  { lemma: 'scegliere', meaning: 'to choose', partOfSpeech: 'verb', isBeginner: false },
  { lemma: 'diventare', meaning: 'to become', partOfSpeech: 'verb', isBeginner: false },
  { lemma: 'provare', meaning: 'to try', partOfSpeech: 'verb', isBeginner: false },
  { lemma: 'usare', meaning: 'to use', partOfSpeech: 'verb', isBeginner: false },
  { lemma: 'camminare', meaning: 'to walk', partOfSpeech: 'verb', isBeginner: false },
  { lemma: 'ballare', meaning: 'to dance', partOfSpeech: 'verb', isBeginner: false }
];
