export const adjectives = [
  // Size/Quantity
  { lemma: 'grand', meaning: 'big/tall', isBeginner: true },
  { lemma: 'petit', meaning: 'small/short', isBeginner: true },
  { lemma: 'gros', meaning: 'fat/big', isBeginner: true },
  { lemma: 'énorme', meaning: 'enormous' },
  { lemma: 'minuscule', meaning: 'tiny' },
  { lemma: 'long', meaning: 'long', isBeginner: true },
  { lemma: 'court', meaning: 'short', isBeginner: true },
  { lemma: 'large', meaning: 'wide' },
  { lemma: 'étroit', meaning: 'narrow' },
  { lemma: 'haut', meaning: 'high/tall' },
  { lemma: 'bas', meaning: 'low' },
  { lemma: 'profond', meaning: 'deep' },
  { lemma: 'épais', meaning: 'thick' },
  { lemma: 'mince', meaning: 'thin/slim' },
  { lemma: 'immense', meaning: 'immense' },
  { lemma: 'vaste', meaning: 'vast' },
  { lemma: 'nombreux', meaning: 'numerous' },
  { lemma: 'plein', meaning: 'full', isBeginner: true },
  { lemma: 'vide', meaning: 'empty' },

  // Quality
  { lemma: 'bon', meaning: 'good', isBeginner: true },
  { lemma: 'mauvais', meaning: 'bad', isBeginner: true },
  { lemma: 'beau', meaning: 'beautiful/handsome', isBeginner: true },
  { lemma: 'joli', meaning: 'pretty', isBeginner: true },
  { lemma: 'laid', meaning: 'ugly' },
  { lemma: 'nouveau', meaning: 'new', isBeginner: true },
  { lemma: 'vieux', meaning: 'old', isBeginner: true },
  { lemma: 'jeune', meaning: 'young', isBeginner: true },
  { lemma: 'ancien', meaning: 'old/former' },
  { lemma: 'moderne', meaning: 'modern' },
  { lemma: 'parfait', meaning: 'perfect' },
  { lemma: 'excellent', meaning: 'excellent' },
  { lemma: 'magnifique', meaning: 'magnificent' },
  { lemma: 'merveilleux', meaning: 'marvelous' },
  { lemma: 'terrible', meaning: 'terrible' },
  { lemma: 'horrible', meaning: 'horrible' },
  { lemma: 'affreux', meaning: 'dreadful' },
  { lemma: 'superbe', meaning: 'superb' },

  // Color
  { lemma: 'rouge', meaning: 'red', isBeginner: true },
  { lemma: 'bleu', meaning: 'blue', isBeginner: true },
  { lemma: 'vert', meaning: 'green', isBeginner: true },
  { lemma: 'jaune', meaning: 'yellow', isBeginner: true },
  { lemma: 'noir', meaning: 'black', isBeginner: true },
  { lemma: 'blanc', meaning: 'white', isBeginner: true },
  { lemma: 'gris', meaning: 'gray', isBeginner: true },
  { lemma: 'marron', meaning: 'brown', isBeginner: true },
  { lemma: 'rose', meaning: 'pink', isBeginner: true },
  { lemma: 'orange', meaning: 'orange', isBeginner: true },
  { lemma: 'violet', meaning: 'purple', isBeginner: true },
  { lemma: 'clair', meaning: 'light/bright' },
  { lemma: 'foncé', meaning: 'dark' },

  // Temperature/Weather
  { lemma: 'chaud', meaning: 'hot/warm', isBeginner: true },
  { lemma: 'froid', meaning: 'cold', isBeginner: true },
  { lemma: 'frais', meaning: 'cool/fresh' },
  { lemma: 'sec', meaning: 'dry' },
  { lemma: 'humide', meaning: 'humid/damp' },
  { lemma: 'doux', meaning: 'soft/mild/sweet' },
  { lemma: 'tiède', meaning: 'lukewarm' },
  { lemma: 'glacé', meaning: 'icy/frozen' },
  { lemma: 'brûlant', meaning: 'burning hot' },
  { lemma: 'ensoleillé', meaning: 'sunny' },
  { lemma: 'nuageux', meaning: 'cloudy' },
  { lemma: 'pluvieux', meaning: 'rainy' },

  // Personality
  { lemma: 'gentil', meaning: 'kind/nice', isBeginner: true },
  { lemma: 'méchant', meaning: 'mean/naughty', isBeginner: true },
  { lemma: 'intelligent', meaning: 'intelligent', isBeginner: true },
  { lemma: 'drôle', meaning: 'funny' },
  { lemma: 'sérieux', meaning: 'serious' },
  { lemma: 'timide', meaning: 'shy' },
  { lemma: 'courageux', meaning: 'brave/courageous' },
  { lemma: 'paresseux', meaning: 'lazy' },
  { lemma: 'généreux', meaning: 'generous' },
  { lemma: 'honnête', meaning: 'honest' },
  { lemma: 'poli', meaning: 'polite' },
  { lemma: 'impoli', meaning: 'impolite/rude' },
  { lemma: 'curieux', meaning: 'curious' },
  { lemma: 'patient', meaning: 'patient' },
  { lemma: 'impatient', meaning: 'impatient' },
  { lemma: 'fidèle', meaning: 'faithful/loyal' },
  { lemma: 'jaloux', meaning: 'jealous' },
  { lemma: 'fier', meaning: 'proud' },
  { lemma: 'modeste', meaning: 'modest' },
  { lemma: 'sage', meaning: 'wise/well-behaved' },
  { lemma: 'fou', meaning: 'crazy/mad' },
  { lemma: 'bizarre', meaning: 'strange/weird' },
  { lemma: 'sympathique', meaning: 'nice/likeable', isBeginner: true },
  { lemma: 'désagréable', meaning: 'unpleasant' },
  { lemma: 'agréable', meaning: 'pleasant' },

  // Physical
  { lemma: 'fort', meaning: 'strong', isBeginner: true },
  { lemma: 'faible', meaning: 'weak' },
  { lemma: 'rapide', meaning: 'fast/quick' },
  { lemma: 'lent', meaning: 'slow' },
  { lemma: 'lourd', meaning: 'heavy' },
  { lemma: 'léger', meaning: 'light/lightweight' },
  { lemma: 'dur', meaning: 'hard/tough' },
  { lemma: 'mou', meaning: 'soft/limp' },
  { lemma: 'propre', meaning: 'clean/own' },
  { lemma: 'sale', meaning: 'dirty' },
  { lemma: 'mouillé', meaning: 'wet' },
  { lemma: 'solide', meaning: 'solid/sturdy' },
  { lemma: 'fragile', meaning: 'fragile' },
  { lemma: 'souple', meaning: 'flexible/supple' },
  { lemma: 'raide', meaning: 'stiff' },
  { lemma: 'rond', meaning: 'round' },
  { lemma: 'carré', meaning: 'square' },
  { lemma: 'droit', meaning: 'straight/right' },
  { lemma: 'plat', meaning: 'flat' },

  // Emotion
  { lemma: 'heureux', meaning: 'happy', isBeginner: true },
  { lemma: 'triste', meaning: 'sad', isBeginner: true },
  { lemma: 'content', meaning: 'happy/pleased', isBeginner: true },
  { lemma: 'fâché', meaning: 'angry', isBeginner: true },
  { lemma: 'surpris', meaning: 'surprised' },
  { lemma: 'inquiet', meaning: 'worried' },
  { lemma: 'calme', meaning: 'calm' },
  { lemma: 'nerveux', meaning: 'nervous' },
  { lemma: 'fatigué', meaning: 'tired', isBeginner: true },
  { lemma: 'amoureux', meaning: 'in love' },
  { lemma: 'déçu', meaning: 'disappointed' },
  { lemma: 'satisfait', meaning: 'satisfied' },
  { lemma: 'ému', meaning: 'moved/emotional' },
  { lemma: 'confus', meaning: 'confused' },
  { lemma: 'furieux', meaning: 'furious' },
  { lemma: 'anxieux', meaning: 'anxious' },
  { lemma: 'enthousiaste', meaning: 'enthusiastic' },
  { lemma: 'reconnaissant', meaning: 'grateful' },
  { lemma: 'désolé', meaning: 'sorry' },

  // Evaluative
  { lemma: 'important', meaning: 'important', isBeginner: true },
  { lemma: 'difficile', meaning: 'difficult', isBeginner: true },
  { lemma: 'facile', meaning: 'easy', isBeginner: true },
  { lemma: 'possible', meaning: 'possible' },
  { lemma: 'impossible', meaning: 'impossible' },
  { lemma: 'nécessaire', meaning: 'necessary' },
  { lemma: 'utile', meaning: 'useful' },
  { lemma: 'inutile', meaning: 'useless' },
  { lemma: 'simple', meaning: 'simple' },
  { lemma: 'compliqué', meaning: 'complicated' },
  { lemma: 'normal', meaning: 'normal' },
  { lemma: 'spécial', meaning: 'special' },
  { lemma: 'principal', meaning: 'main/principal' },
  { lemma: 'essentiel', meaning: 'essential' },
  { lemma: 'évident', meaning: 'obvious' },
  { lemma: 'certain', meaning: 'certain/sure' },
  { lemma: 'exact', meaning: 'exact/correct' },
  { lemma: 'faux', meaning: 'false/wrong' },
  { lemma: 'vrai', meaning: 'true', isBeginner: true },
  { lemma: 'juste', meaning: 'fair/just/right' },
  { lemma: 'correct', meaning: 'correct' },
  { lemma: 'grave', meaning: 'serious/grave' },
  { lemma: 'légitime', meaning: 'legitimate' },
  { lemma: 'suffisant', meaning: 'sufficient' },

  // Common Descriptive
  { lemma: 'intéressant', meaning: 'interesting' },
  { lemma: 'ennuyeux', meaning: 'boring/annoying' },
  { lemma: 'différent', meaning: 'different' },
  { lemma: 'même', meaning: 'same' },
  { lemma: 'seul', meaning: 'alone/only' },
  { lemma: 'autre', meaning: 'other', isBeginner: true },
  { lemma: 'premier', meaning: 'first', isBeginner: true },
  { lemma: 'dernier', meaning: 'last', isBeginner: true },
  { lemma: 'prochain', meaning: 'next' },
  { lemma: 'suivant', meaning: 'following' },
  { lemma: 'précédent', meaning: 'previous' },
  { lemma: 'cher', meaning: 'dear/expensive', isBeginner: true },
  { lemma: 'gratuit', meaning: 'free (no cost)' },
  { lemma: 'favori', meaning: 'favorite' },
  { lemma: 'célèbre', meaning: 'famous' },
  { lemma: 'connu', meaning: 'known/well-known' },
  { lemma: 'inconnu', meaning: 'unknown' },
  { lemma: 'commun', meaning: 'common' },
  { lemma: 'rare', meaning: 'rare' },
  { lemma: 'typique', meaning: 'typical' },
  { lemma: 'habituel', meaning: 'usual' },
  { lemma: 'quotidien', meaning: 'daily' },
  { lemma: 'actuel', meaning: 'current' },
  { lemma: 'réel', meaning: 'real' },
  { lemma: 'naturel', meaning: 'natural' },
  { lemma: 'public', meaning: 'public' },
  { lemma: 'privé', meaning: 'private' },
  { lemma: 'libre', meaning: 'free' },
  { lemma: 'ouvert', meaning: 'open' },
  { lemma: 'fermé', meaning: 'closed' },
  { lemma: 'prêt', meaning: 'ready', isBeginner: true },
  { lemma: 'vivant', meaning: 'alive/living' },
  { lemma: 'mort', meaning: 'dead' },
  { lemma: 'entier', meaning: 'whole/entire' },
  { lemma: 'complet', meaning: 'complete' },
  { lemma: 'général', meaning: 'general' },
  { lemma: 'particulier', meaning: 'particular' },
  { lemma: 'semblable', meaning: 'similar' },
  { lemma: 'pareil', meaning: 'the same/similar' },
  { lemma: 'capable', meaning: 'capable' },
  { lemma: 'responsable', meaning: 'responsible' },
  { lemma: 'disponible', meaning: 'available' },
  { lemma: 'proche', meaning: 'near/close' },
  { lemma: 'lointain', meaning: 'distant/far' },
  { lemma: 'étranger', meaning: 'foreign' },
  { lemma: 'national', meaning: 'national' },
  { lemma: 'international', meaning: 'international' },
  { lemma: 'politique', meaning: 'political' },
  { lemma: 'économique', meaning: 'economic' },
  { lemma: 'social', meaning: 'social' },
  { lemma: 'culturel', meaning: 'cultural' },
  { lemma: 'religieux', meaning: 'religious' },
  { lemma: 'militaire', meaning: 'military' },
  { lemma: 'scientifique', meaning: 'scientific' },
  { lemma: 'technique', meaning: 'technical' },
  { lemma: 'professionnel', meaning: 'professional' },
  { lemma: 'personnel', meaning: 'personal' }
];
