export const adjectives = [
	// Size/Quantity
	{ word: 'grand', translation: 'big/tall', isBeginner: true },
	{ word: 'petit', translation: 'small/short', isBeginner: true },
	{ word: 'gros', translation: 'fat/big', isBeginner: true },
	{ word: 'énorme', translation: 'enormous' },
	{ word: 'minuscule', translation: 'tiny' },
	{ word: 'long', translation: 'long', isBeginner: true },
	{ word: 'court', translation: 'short', isBeginner: true },
	{ word: 'large', translation: 'wide' },
	{ word: 'étroit', translation: 'narrow' },
	{ word: 'haut', translation: 'high/tall' },
	{ word: 'bas', translation: 'low' },
	{ word: 'profond', translation: 'deep' },
	{ word: 'épais', translation: 'thick' },
	{ word: 'mince', translation: 'thin/slim' },
	{ word: 'immense', translation: 'immense' },
	{ word: 'vaste', translation: 'vast' },
	{ word: 'nombreux', translation: 'numerous' },
	{ word: 'plein', translation: 'full', isBeginner: true },
	{ word: 'vide', translation: 'empty' },

	// Quality
	{ word: 'bon', translation: 'good', isBeginner: true },
	{ word: 'mauvais', translation: 'bad', isBeginner: true },
	{ word: 'beau', translation: 'beautiful/handsome', isBeginner: true },
	{ word: 'joli', translation: 'pretty', isBeginner: true },
	{ word: 'laid', translation: 'ugly' },
	{ word: 'nouveau', translation: 'new', isBeginner: true },
	{ word: 'vieux', translation: 'old', isBeginner: true },
	{ word: 'jeune', translation: 'young', isBeginner: true },
	{ word: 'ancien', translation: 'old/former' },
	{ word: 'moderne', translation: 'modern' },
	{ word: 'parfait', translation: 'perfect' },
	{ word: 'excellent', translation: 'excellent' },
	{ word: 'magnifique', translation: 'magnificent' },
	{ word: 'merveilleux', translation: 'marvelous' },
	{ word: 'terrible', translation: 'terrible' },
	{ word: 'horrible', translation: 'horrible' },
	{ word: 'affreux', translation: 'dreadful' },
	{ word: 'superbe', translation: 'superb' },

	// Color
	{ word: 'rouge', translation: 'red', isBeginner: true },
	{ word: 'bleu', translation: 'blue', isBeginner: true },
	{ word: 'vert', translation: 'green', isBeginner: true },
	{ word: 'jaune', translation: 'yellow', isBeginner: true },
	{ word: 'noir', translation: 'black', isBeginner: true },
	{ word: 'blanc', translation: 'white', isBeginner: true },
	{ word: 'gris', translation: 'gray', isBeginner: true },
	{ word: 'marron', translation: 'brown', isBeginner: true },
	{ word: 'rose', translation: 'pink', isBeginner: true },
	{ word: 'orange', translation: 'orange', isBeginner: true },
	{ word: 'violet', translation: 'purple', isBeginner: true },
	{ word: 'clair', translation: 'light/bright' },
	{ word: 'foncé', translation: 'dark' },

	// Temperature/Weather
	{ word: 'chaud', translation: 'hot/warm', isBeginner: true },
	{ word: 'froid', translation: 'cold', isBeginner: true },
	{ word: 'frais', translation: 'cool/fresh' },
	{ word: 'sec', translation: 'dry' },
	{ word: 'humide', translation: 'humid/damp' },
	{ word: 'doux', translation: 'soft/mild/sweet' },
	{ word: 'tiède', translation: 'lukewarm' },
	{ word: 'glacé', translation: 'icy/frozen' },
	{ word: 'brûlant', translation: 'burning hot' },
	{ word: 'ensoleillé', translation: 'sunny' },
	{ word: 'nuageux', translation: 'cloudy' },
	{ word: 'pluvieux', translation: 'rainy' },

	// Personality
	{ word: 'gentil', translation: 'kind/nice', isBeginner: true },
	{ word: 'méchant', translation: 'mean/naughty', isBeginner: true },
	{ word: 'intelligent', translation: 'intelligent', isBeginner: true },
	{ word: 'drôle', translation: 'funny' },
	{ word: 'sérieux', translation: 'serious' },
	{ word: 'timide', translation: 'shy' },
	{ word: 'courageux', translation: 'brave/courageous' },
	{ word: 'paresseux', translation: 'lazy' },
	{ word: 'généreux', translation: 'generous' },
	{ word: 'honnête', translation: 'honest' },
	{ word: 'poli', translation: 'polite' },
	{ word: 'impoli', translation: 'impolite/rude' },
	{ word: 'curieux', translation: 'curious' },
	{ word: 'patient', translation: 'patient' },
	{ word: 'impatient', translation: 'impatient' },
	{ word: 'fidèle', translation: 'faithful/loyal' },
	{ word: 'jaloux', translation: 'jealous' },
	{ word: 'fier', translation: 'proud' },
	{ word: 'modeste', translation: 'modest' },
	{ word: 'sage', translation: 'wise/well-behaved' },
	{ word: 'fou', translation: 'crazy/mad' },
	{ word: 'bizarre', translation: 'strange/weird' },
	{ word: 'sympathique', translation: 'nice/likeable', isBeginner: true },
	{ word: 'désagréable', translation: 'unpleasant' },
	{ word: 'agréable', translation: 'pleasant' },

	// Physical
	{ word: 'fort', translation: 'strong', isBeginner: true },
	{ word: 'faible', translation: 'weak' },
	{ word: 'rapide', translation: 'fast/quick' },
	{ word: 'lent', translation: 'slow' },
	{ word: 'lourd', translation: 'heavy' },
	{ word: 'léger', translation: 'light/lightweight' },
	{ word: 'dur', translation: 'hard/tough' },
	{ word: 'mou', translation: 'soft/limp' },
	{ word: 'propre', translation: 'clean/own' },
	{ word: 'sale', translation: 'dirty' },
	{ word: 'mouillé', translation: 'wet' },
	{ word: 'solide', translation: 'solid/sturdy' },
	{ word: 'fragile', translation: 'fragile' },
	{ word: 'souple', translation: 'flexible/supple' },
	{ word: 'raide', translation: 'stiff' },
	{ word: 'rond', translation: 'round' },
	{ word: 'carré', translation: 'square' },
	{ word: 'droit', translation: 'straight/right' },
	{ word: 'plat', translation: 'flat' },

	// Emotion
	{ word: 'heureux', translation: 'happy', isBeginner: true },
	{ word: 'triste', translation: 'sad', isBeginner: true },
	{ word: 'content', translation: 'happy/pleased', isBeginner: true },
	{ word: 'fâché', translation: 'angry', isBeginner: true },
	{ word: 'surpris', translation: 'surprised' },
	{ word: 'inquiet', translation: 'worried' },
	{ word: 'calme', translation: 'calm' },
	{ word: 'nerveux', translation: 'nervous' },
	{ word: 'fatigué', translation: 'tired', isBeginner: true },
	{ word: 'amoureux', translation: 'in love' },
	{ word: 'déçu', translation: 'disappointed' },
	{ word: 'satisfait', translation: 'satisfied' },
	{ word: 'ému', translation: 'moved/emotional' },
	{ word: 'confus', translation: 'confused' },
	{ word: 'furieux', translation: 'furious' },
	{ word: 'anxieux', translation: 'anxious' },
	{ word: 'enthousiaste', translation: 'enthusiastic' },
	{ word: 'reconnaissant', translation: 'grateful' },
	{ word: 'désolé', translation: 'sorry' },

	// Evaluative
	{ word: 'important', translation: 'important', isBeginner: true },
	{ word: 'difficile', translation: 'difficult', isBeginner: true },
	{ word: 'facile', translation: 'easy', isBeginner: true },
	{ word: 'possible', translation: 'possible' },
	{ word: 'impossible', translation: 'impossible' },
	{ word: 'nécessaire', translation: 'necessary' },
	{ word: 'utile', translation: 'useful' },
	{ word: 'inutile', translation: 'useless' },
	{ word: 'simple', translation: 'simple' },
	{ word: 'compliqué', translation: 'complicated' },
	{ word: 'normal', translation: 'normal' },
	{ word: 'spécial', translation: 'special' },
	{ word: 'principal', translation: 'main/principal' },
	{ word: 'essentiel', translation: 'essential' },
	{ word: 'évident', translation: 'obvious' },
	{ word: 'certain', translation: 'certain/sure' },
	{ word: 'exact', translation: 'exact/correct' },
	{ word: 'faux', translation: 'false/wrong' },
	{ word: 'vrai', translation: 'true', isBeginner: true },
	{ word: 'juste', translation: 'fair/just/right' },
	{ word: 'correct', translation: 'correct' },
	{ word: 'grave', translation: 'serious/grave' },
	{ word: 'légitime', translation: 'legitimate' },
	{ word: 'suffisant', translation: 'sufficient' },

	// Common Descriptive
	{ word: 'intéressant', translation: 'interesting' },
	{ word: 'ennuyeux', translation: 'boring/annoying' },
	{ word: 'différent', translation: 'different' },
	{ word: 'même', translation: 'same' },
	{ word: 'seul', translation: 'alone/only' },
	{ word: 'autre', translation: 'other', isBeginner: true },
	{ word: 'premier', translation: 'first', isBeginner: true },
	{ word: 'dernier', translation: 'last', isBeginner: true },
	{ word: 'prochain', translation: 'next' },
	{ word: 'suivant', translation: 'following' },
	{ word: 'précédent', translation: 'previous' },
	{ word: 'cher', translation: 'dear/expensive', isBeginner: true },
	{ word: 'gratuit', translation: 'free (no cost)' },
	{ word: 'favori', translation: 'favorite' },
	{ word: 'célèbre', translation: 'famous' },
	{ word: 'connu', translation: 'known/well-known' },
	{ word: 'inconnu', translation: 'unknown' },
	{ word: 'commun', translation: 'common' },
	{ word: 'rare', translation: 'rare' },
	{ word: 'typique', translation: 'typical' },
	{ word: 'habituel', translation: 'usual' },
	{ word: 'quotidien', translation: 'daily' },
	{ word: 'actuel', translation: 'current' },
	{ word: 'réel', translation: 'real' },
	{ word: 'naturel', translation: 'natural' },
	{ word: 'public', translation: 'public' },
	{ word: 'privé', translation: 'private' },
	{ word: 'libre', translation: 'free' },
	{ word: 'ouvert', translation: 'open' },
	{ word: 'fermé', translation: 'closed' },
	{ word: 'prêt', translation: 'ready', isBeginner: true },
	{ word: 'vivant', translation: 'alive/living' },
	{ word: 'mort', translation: 'dead' },
	{ word: 'entier', translation: 'whole/entire' },
	{ word: 'complet', translation: 'complete' },
	{ word: 'général', translation: 'general' },
	{ word: 'particulier', translation: 'particular' },
	{ word: 'semblable', translation: 'similar' },
	{ word: 'pareil', translation: 'the same/similar' },
	{ word: 'capable', translation: 'capable' },
	{ word: 'responsable', translation: 'responsible' },
	{ word: 'disponible', translation: 'available' },
	{ word: 'proche', translation: 'near/close' },
	{ word: 'lointain', translation: 'distant/far' },
	{ word: 'étranger', translation: 'foreign' },
	{ word: 'national', translation: 'national' },
	{ word: 'international', translation: 'international' },
	{ word: 'politique', translation: 'political' },
	{ word: 'économique', translation: 'economic' },
	{ word: 'social', translation: 'social' },
	{ word: 'culturel', translation: 'cultural' },
	{ word: 'religieux', translation: 'religious' },
	{ word: 'militaire', translation: 'military' },
	{ word: 'scientifique', translation: 'scientific' },
	{ word: 'technique', translation: 'technical' },
	{ word: 'professionnel', translation: 'professional' },
	{ word: 'personnel', translation: 'personal' },
];
