export const adverbs = [
	// Manner
	{ lemma: 'bien', meaning: 'well', isBeginner: true },
	{ lemma: 'mal', meaning: 'badly', isBeginner: true },
	{ lemma: 'vite', meaning: 'quickly', isBeginner: true },
	{ lemma: 'lentement', meaning: 'slowly', isBeginner: true },
	{ lemma: 'doucement', meaning: 'gently / softly' },
	{ lemma: 'facilement', meaning: 'easily' },
	{ lemma: 'difficilement', meaning: 'with difficulty' },
	{ lemma: 'ensemble', meaning: 'together', isBeginner: true },
	{ lemma: 'seulement', meaning: 'only' },
	{ lemma: 'surtout', meaning: 'especially' },
	{ lemma: 'exactement', meaning: 'exactly' },
	{ lemma: 'heureusement', meaning: 'fortunately' },
	{ lemma: 'malheureusement', meaning: 'unfortunately' },
	{ lemma: 'tranquillement', meaning: 'quietly / calmly' },
	{ lemma: 'rapidement', meaning: 'rapidly' },
	{ lemma: 'correctement', meaning: 'correctly' },
	{ lemma: 'simplement', meaning: 'simply' },
	{ lemma: 'naturellement', meaning: 'naturally' },
	{ lemma: 'directement', meaning: 'directly' },
	{ lemma: 'librement', meaning: 'freely' },
	{ lemma: 'silencieusement', meaning: 'silently' },
	{ lemma: 'poliment', meaning: 'politely' },
	{ lemma: 'fort', meaning: 'loudly / strongly' },

	// Time
	{ lemma: 'maintenant', meaning: 'now', isBeginner: true },
	{ lemma: "aujourd'hui", meaning: 'today', isBeginner: true },
	{ lemma: 'hier', meaning: 'yesterday', isBeginner: true },
	{ lemma: 'demain', meaning: 'tomorrow', isBeginner: true },
	{ lemma: 'toujours', meaning: 'always', isBeginner: true },
	{ lemma: 'jamais', meaning: 'never', isBeginner: true },
	{ lemma: 'souvent', meaning: 'often', isBeginner: true },
	{ lemma: 'parfois', meaning: 'sometimes', isBeginner: true },
	{ lemma: 'déjà', meaning: 'already', isBeginner: true },
	{ lemma: 'encore', meaning: 'still / again', isBeginner: true },
	{ lemma: 'bientôt', meaning: 'soon', isBeginner: true },
	{ lemma: 'tôt', meaning: 'early', isBeginner: true },
	{ lemma: 'tard', meaning: 'late', isBeginner: true },
	{ lemma: 'longtemps', meaning: 'for a long time' },
	{ lemma: 'récemment', meaning: 'recently' },
	{ lemma: 'aussitôt', meaning: 'immediately' },
	{ lemma: 'enfin', meaning: 'finally' },
	{ lemma: 'ensuite', meaning: 'then / next' },
	{ lemma: "d'abord", meaning: 'first / at first' },
	{ lemma: 'avant', meaning: 'before', isBeginner: true },
	{ lemma: 'après', meaning: 'after', isBeginner: true },
	{ lemma: 'pendant', meaning: 'during' },
	{ lemma: 'depuis', meaning: 'since' },
	{ lemma: 'autrefois', meaning: 'formerly / in the past' },
	{ lemma: 'désormais', meaning: 'from now on' },
	{ lemma: 'dorénavant', meaning: 'henceforth' },
	{ lemma: 'tout de suite', meaning: 'right away' },

	// Place
	{ lemma: 'ici', meaning: 'here', isBeginner: true },
	{ lemma: 'là', meaning: 'there', isBeginner: true },
	{ lemma: 'là-bas', meaning: 'over there', isBeginner: true },
	{ lemma: 'partout', meaning: 'everywhere' },
	{ lemma: 'nulle part', meaning: 'nowhere' },
	{ lemma: 'dehors', meaning: 'outside' },
	{ lemma: 'dedans', meaning: 'inside' },
	{ lemma: 'devant', meaning: 'in front', isBeginner: true },
	{ lemma: 'derrière', meaning: 'behind', isBeginner: true },
	{ lemma: 'dessus', meaning: 'on top / above' },
	{ lemma: 'dessous', meaning: 'underneath / below' },
	{ lemma: 'loin', meaning: 'far' },
	{ lemma: 'près', meaning: 'near', isBeginner: true },
	{ lemma: 'ailleurs', meaning: 'elsewhere' },
	{ lemma: 'autour', meaning: 'around' },
	{ lemma: 'en haut', meaning: 'up / upstairs' },
	{ lemma: 'en bas', meaning: 'down / downstairs' },

	// Quantity / Degree
	{ lemma: 'très', meaning: 'very', isBeginner: true },
	{ lemma: 'trop', meaning: 'too much', isBeginner: true },
	{ lemma: 'assez', meaning: 'enough / quite', isBeginner: true },
	{ lemma: 'beaucoup', meaning: 'a lot', isBeginner: true },
	{ lemma: 'peu', meaning: 'little / not much', isBeginner: true },
	{ lemma: 'plus', meaning: 'more', isBeginner: true },
	{ lemma: 'moins', meaning: 'less', isBeginner: true },
	{ lemma: 'autant', meaning: 'as much' },
	{ lemma: 'plutôt', meaning: 'rather' },
	{ lemma: 'environ', meaning: 'approximately' },
	{ lemma: 'presque', meaning: 'almost' },
	{ lemma: 'tout à fait', meaning: 'completely / entirely' },
	{ lemma: 'à peine', meaning: 'barely / hardly' },
	{ lemma: 'tellement', meaning: 'so much' },
	{ lemma: 'davantage', meaning: 'more / further' },
	{ lemma: 'au moins', meaning: 'at least' },
	{ lemma: 'au plus', meaning: 'at most' },
	{ lemma: 'un peu', meaning: 'a little', isBeginner: true },

	// Frequency
	{ lemma: 'rarement', meaning: 'rarely' },
	{ lemma: 'quelquefois', meaning: 'sometimes' },
	{ lemma: 'habituellement', meaning: 'usually' },
	{ lemma: 'généralement', meaning: 'generally' },
	{ lemma: 'fréquemment', meaning: 'frequently' },
	{ lemma: 'quotidiennement', meaning: 'daily' },
	{ lemma: 'régulièrement', meaning: 'regularly' },
	{ lemma: 'de temps en temps', meaning: 'from time to time' },

	// Affirmation / Negation
	{ lemma: 'oui', meaning: 'yes', isBeginner: true },
	{ lemma: 'non', meaning: 'no', isBeginner: true },
	{ lemma: 'peut-être', meaning: 'maybe / perhaps', isBeginner: true },
	{ lemma: 'certainement', meaning: 'certainly' },
	{ lemma: 'probablement', meaning: 'probably' },
	{ lemma: 'sûrement', meaning: 'surely' },
	{ lemma: 'absolument', meaning: 'absolutely' },
	{ lemma: 'vraiment', meaning: 'really', isBeginner: true },
	{ lemma: 'évidemment', meaning: 'obviously' },
	{ lemma: 'sans doute', meaning: 'without a doubt' },
	{ lemma: 'bien sûr', meaning: 'of course', isBeginner: true },
	{ lemma: 'pas du tout', meaning: 'not at all' },
	{ lemma: 'aussi', meaning: 'also / too', isBeginner: true },
	{ lemma: 'ne...pas', meaning: 'not', isBeginner: true },
	{ lemma: 'ne...plus', meaning: 'no longer' },
	{ lemma: 'ne...rien', meaning: 'nothing' },
	{ lemma: 'ne...jamais', meaning: 'never' },

	// Interrogative
	{ lemma: 'comment', meaning: 'how', isBeginner: true },
	{ lemma: 'pourquoi', meaning: 'why', isBeginner: true },
	{ lemma: 'quand', meaning: 'when', isBeginner: true },
	{ lemma: 'où', meaning: 'where', isBeginner: true },
	{ lemma: 'combien', meaning: 'how much / how many', isBeginner: true }
];
