export const adverbs = [
	// Manner
	{ word: 'bien', translation: 'well', isBeginner: true },
	{ word: 'mal', translation: 'badly', isBeginner: true },
	{ word: 'vite', translation: 'quickly', isBeginner: true },
	{ word: 'lentement', translation: 'slowly', isBeginner: true },
	{ word: 'doucement', translation: 'gently / softly' },
	{ word: 'facilement', translation: 'easily' },
	{ word: 'difficilement', translation: 'with difficulty' },
	{ word: 'ensemble', translation: 'together', isBeginner: true },
	{ word: 'seulement', translation: 'only' },
	{ word: 'surtout', translation: 'especially' },
	{ word: 'exactement', translation: 'exactly' },
	{ word: 'heureusement', translation: 'fortunately' },
	{ word: 'malheureusement', translation: 'unfortunately' },
	{ word: 'tranquillement', translation: 'quietly / calmly' },
	{ word: 'rapidement', translation: 'rapidly' },
	{ word: 'correctement', translation: 'correctly' },
	{ word: 'simplement', translation: 'simply' },
	{ word: 'naturellement', translation: 'naturally' },
	{ word: 'directement', translation: 'directly' },
	{ word: 'librement', translation: 'freely' },
	{ word: 'silencieusement', translation: 'silently' },
	{ word: 'poliment', translation: 'politely' },
	{ word: 'fort', translation: 'loudly / strongly' },

	// Time
	{ word: 'maintenant', translation: 'now', isBeginner: true },
	{ word: "aujourd'hui", translation: 'today', isBeginner: true },
	{ word: 'hier', translation: 'yesterday', isBeginner: true },
	{ word: 'demain', translation: 'tomorrow', isBeginner: true },
	{ word: 'toujours', translation: 'always', isBeginner: true },
	{ word: 'jamais', translation: 'never', isBeginner: true },
	{ word: 'souvent', translation: 'often', isBeginner: true },
	{ word: 'parfois', translation: 'sometimes', isBeginner: true },
	{ word: 'déjà', translation: 'already', isBeginner: true },
	{ word: 'encore', translation: 'still / again', isBeginner: true },
	{ word: 'bientôt', translation: 'soon', isBeginner: true },
	{ word: 'tôt', translation: 'early', isBeginner: true },
	{ word: 'tard', translation: 'late', isBeginner: true },
	{ word: 'longtemps', translation: 'for a long time' },
	{ word: 'récemment', translation: 'recently' },
	{ word: 'aussitôt', translation: 'immediately' },
	{ word: 'enfin', translation: 'finally' },
	{ word: 'ensuite', translation: 'then / next' },
	{ word: "d'abord", translation: 'first / at first' },
	{ word: 'avant', translation: 'before', isBeginner: true },
	{ word: 'après', translation: 'after', isBeginner: true },
	{ word: 'pendant', translation: 'during' },
	{ word: 'depuis', translation: 'since' },
	{ word: 'autrefois', translation: 'formerly / in the past' },
	{ word: 'désormais', translation: 'from now on' },
	{ word: 'dorénavant', translation: 'henceforth' },
	{ word: 'tout de suite', translation: 'right away' },

	// Place
	{ word: 'ici', translation: 'here', isBeginner: true },
	{ word: 'là', translation: 'there', isBeginner: true },
	{ word: 'là-bas', translation: 'over there', isBeginner: true },
	{ word: 'partout', translation: 'everywhere' },
	{ word: 'nulle part', translation: 'nowhere' },
	{ word: 'dehors', translation: 'outside' },
	{ word: 'dedans', translation: 'inside' },
	{ word: 'devant', translation: 'in front', isBeginner: true },
	{ word: 'derrière', translation: 'behind', isBeginner: true },
	{ word: 'dessus', translation: 'on top / above' },
	{ word: 'dessous', translation: 'underneath / below' },
	{ word: 'loin', translation: 'far' },
	{ word: 'près', translation: 'near', isBeginner: true },
	{ word: 'ailleurs', translation: 'elsewhere' },
	{ word: 'autour', translation: 'around' },
	{ word: 'en haut', translation: 'up / upstairs' },
	{ word: 'en bas', translation: 'down / downstairs' },

	// Quantity / Degree
	{ word: 'très', translation: 'very', isBeginner: true },
	{ word: 'trop', translation: 'too much', isBeginner: true },
	{ word: 'assez', translation: 'enough / quite', isBeginner: true },
	{ word: 'beaucoup', translation: 'a lot', isBeginner: true },
	{ word: 'peu', translation: 'little / not much', isBeginner: true },
	{ word: 'plus', translation: 'more', isBeginner: true },
	{ word: 'moins', translation: 'less', isBeginner: true },
	{ word: 'autant', translation: 'as much' },
	{ word: 'plutôt', translation: 'rather' },
	{ word: 'environ', translation: 'approximately' },
	{ word: 'presque', translation: 'almost' },
	{ word: 'tout à fait', translation: 'completely / entirely' },
	{ word: 'à peine', translation: 'barely / hardly' },
	{ word: 'tellement', translation: 'so much' },
	{ word: 'davantage', translation: 'more / further' },
	{ word: 'au moins', translation: 'at least' },
	{ word: 'au plus', translation: 'at most' },
	{ word: 'un peu', translation: 'a little', isBeginner: true },

	// Frequency
	{ word: 'rarement', translation: 'rarely' },
	{ word: 'quelquefois', translation: 'sometimes' },
	{ word: 'habituellement', translation: 'usually' },
	{ word: 'généralement', translation: 'generally' },
	{ word: 'fréquemment', translation: 'frequently' },
	{ word: 'quotidiennement', translation: 'daily' },
	{ word: 'régulièrement', translation: 'regularly' },
	{ word: 'de temps en temps', translation: 'from time to time' },

	// Affirmation / Negation
	{ word: 'oui', translation: 'yes', isBeginner: true },
	{ word: 'non', translation: 'no', isBeginner: true },
	{ word: 'peut-être', translation: 'maybe / perhaps', isBeginner: true },
	{ word: 'certainement', translation: 'certainly' },
	{ word: 'probablement', translation: 'probably' },
	{ word: 'sûrement', translation: 'surely' },
	{ word: 'absolument', translation: 'absolutely' },
	{ word: 'vraiment', translation: 'really', isBeginner: true },
	{ word: 'évidemment', translation: 'obviously' },
	{ word: 'sans doute', translation: 'without a doubt' },
	{ word: 'bien sûr', translation: 'of course', isBeginner: true },
	{ word: 'pas du tout', translation: 'not at all' },
	{ word: 'aussi', translation: 'also / too', isBeginner: true },
	{ word: 'ne...pas', translation: 'not', isBeginner: true },
	{ word: 'ne...plus', translation: 'no longer' },
	{ word: 'ne...rien', translation: 'nothing' },
	{ word: 'ne...jamais', translation: 'never' },

	// Interrogative
	{ word: 'comment', translation: 'how', isBeginner: true },
	{ word: 'pourquoi', translation: 'why', isBeginner: true },
	{ word: 'quand', translation: 'when', isBeginner: true },
	{ word: 'où', translation: 'where', isBeginner: true },
	{ word: 'combien', translation: 'how much / how many', isBeginner: true },
];
