export const interjections = [
	{ word: 'oh', translation: 'oh', isBeginner: true },
	{ word: 'ah', translation: 'ah', isBeginner: true },
	{ word: 'salut', translation: 'hi/bye', isBeginner: true },
	{ word: 'bonjour', translation: 'hello/good day', isBeginner: true },
	{ word: 'au revoir', translation: 'goodbye', isBeginner: true },
	{ word: 'merci', translation: 'thank you', isBeginner: true },
	{ word: "s'il vous plaît", translation: 'please (formal)', isBeginner: true },
	{ word: 'pardon', translation: 'pardon/sorry', isBeginner: true },
	{ word: 'excusez-moi', translation: 'excuse me', isBeginner: true },
	{ word: 'bravo', translation: 'bravo/well done', isBeginner: true },
	{ word: 'eh', translation: 'hey/eh', isBeginner: false },
	{ word: 'aïe', translation: 'ouch', isBeginner: false },
	{ word: 'ouf', translation: 'phew', isBeginner: false },
	{ word: 'zut', translation: 'darn/shoot', isBeginner: false },
	{ word: 'mince', translation: 'shoot/blast (mild expletive)', isBeginner: false },
	{ word: 'hélas', translation: 'alas/unfortunately', isBeginner: false },
	{ word: 'tiens', translation: 'well/look here/hey', isBeginner: false },
	{ word: 'voyons', translation: "let's see/come on", isBeginner: false },
	{ word: 'allons', translation: "let's go/come on", isBeginner: false },
	{ word: 'bof', translation: "meh/so-so (expression of indifference)", isBeginner: false },
	{ word: 'chut', translation: 'shh/hush', isBeginner: false },
	{ word: 'hop', translation: 'hop/up you go (expression of action)', isBeginner: false },
	{ word: 'hein', translation: 'huh/right/eh', isBeginner: false },
	{ word: 'bah', translation: 'bah/well (expression of resignation)', isBeginner: false },
	{ word: 'chouette', translation: 'great/cool', isBeginner: false },
	{ word: 'super', translation: 'super/great', isBeginner: false },
	{ word: 'génial', translation: 'brilliant/awesome', isBeginner: false },
	{ word: 'félicitations', translation: 'congratulations', isBeginner: false },
	{ word: 'attention', translation: 'watch out/careful', isBeginner: false },
];
