export const interjections = [
	{ lemma: 'oh', meaning: 'oh', isBeginner: true },
	{ lemma: 'ah', meaning: 'ah', isBeginner: true },
	{ lemma: 'salut', meaning: 'hi/bye', isBeginner: true },
	{ lemma: 'bonjour', meaning: 'hello/good day', isBeginner: true },
	{ lemma: 'au revoir', meaning: 'goodbye', isBeginner: true },
	{ lemma: 'merci', meaning: 'thank you', isBeginner: true },
	{ lemma: "s'il vous plaît", meaning: 'please (formal)', isBeginner: true },
	{ lemma: 'pardon', meaning: 'pardon/sorry', isBeginner: true },
	{ lemma: 'excusez-moi', meaning: 'excuse me', isBeginner: true },
	{ lemma: 'bravo', meaning: 'bravo/well done', isBeginner: true },
	{ lemma: 'eh', meaning: 'hey/eh', isBeginner: false },
	{ lemma: 'aïe', meaning: 'ouch', isBeginner: false },
	{ lemma: 'ouf', meaning: 'phew', isBeginner: false },
	{ lemma: 'zut', meaning: 'darn/shoot', isBeginner: false },
	{ lemma: 'mince', meaning: 'shoot/blast (mild expletive)', isBeginner: false },
	{ lemma: 'hélas', meaning: 'alas/unfortunately', isBeginner: false },
	{ lemma: 'tiens', meaning: 'well/look here/hey', isBeginner: false },
	{ lemma: 'voyons', meaning: "let's see/come on", isBeginner: false },
	{ lemma: 'allons', meaning: "let's go/come on", isBeginner: false },
	{ lemma: 'bof', meaning: 'meh/so-so (expression of indifference)', isBeginner: false },
	{ lemma: 'chut', meaning: 'shh/hush', isBeginner: false },
	{ lemma: 'hop', meaning: 'hop/up you go (expression of action)', isBeginner: false },
	{ lemma: 'hein', meaning: 'huh/right/eh', isBeginner: false },
	{ lemma: 'bah', meaning: 'bah/well (expression of resignation)', isBeginner: false },
	{ lemma: 'chouette', meaning: 'great/cool', isBeginner: false },
	{ lemma: 'super', meaning: 'super/great', isBeginner: false },
	{ lemma: 'génial', meaning: 'brilliant/awesome', isBeginner: false },
	{ lemma: 'félicitations', meaning: 'congratulations', isBeginner: false },
	{ lemma: 'attention', meaning: 'watch out/careful', isBeginner: false }
];
