export const nouns = [
	// ===== People / Family =====
	{ lemma: 'homme', meaning: 'man', isBeginner: true },
	{ lemma: 'femme', meaning: 'woman', isBeginner: true },
	{ lemma: 'enfant', meaning: 'child', isBeginner: true },
	{ lemma: 'père', meaning: 'father', isBeginner: true },
	{ lemma: 'mère', meaning: 'mother', isBeginner: true },
	{ lemma: 'fils', meaning: 'son', isBeginner: true },
	{ lemma: 'fille', meaning: 'daughter', isBeginner: true },
	{ lemma: 'frère', meaning: 'brother', isBeginner: true },
	{ lemma: 'soeur', meaning: 'sister', isBeginner: true },
	{ lemma: 'ami', meaning: 'friend', isBeginner: true },
	{ lemma: 'famille', meaning: 'family', isBeginner: true },
	{ lemma: 'bébé', meaning: 'baby', isBeginner: true },
	{ lemma: 'garçon', meaning: 'boy', isBeginner: true },
	{ lemma: 'mari', meaning: 'husband' },
	{ lemma: 'épouse', meaning: 'wife' },
	{ lemma: 'voisin', meaning: 'neighbor' },
	{ lemma: 'oncle', meaning: 'uncle' },
	{ lemma: 'tante', meaning: 'aunt' },
	{ lemma: 'cousin', meaning: 'cousin' },
	{ lemma: 'grand-père', meaning: 'grandfather' },
	{ lemma: 'grand-mère', meaning: 'grandmother' },
	{ lemma: 'personne', meaning: 'person', isBeginner: true },
	{ lemma: 'gens', meaning: 'people' },
	{ lemma: 'monsieur', meaning: 'sir', isBeginner: true },
	{ lemma: 'madame', meaning: 'madam', isBeginner: true },

	// ===== Body =====
	{ lemma: 'tête', meaning: 'head', isBeginner: true },
	{ lemma: 'main', meaning: 'hand', isBeginner: true },
	{ lemma: 'oeil', meaning: 'eye', isBeginner: true },
	{ lemma: 'bouche', meaning: 'mouth', isBeginner: true },
	{ lemma: 'coeur', meaning: 'heart' },
	{ lemma: 'bras', meaning: 'arm' },
	{ lemma: 'jambe', meaning: 'leg' },
	{ lemma: 'dos', meaning: 'back' },
	{ lemma: 'pied', meaning: 'foot', isBeginner: true },
	{ lemma: 'doigt', meaning: 'finger' },
	{ lemma: 'nez', meaning: 'nose', isBeginner: true },
	{ lemma: 'oreille', meaning: 'ear' },
	{ lemma: 'cheveux', meaning: 'hair' },
	{ lemma: 'visage', meaning: 'face' },
	{ lemma: 'corps', meaning: 'body' },
	{ lemma: 'dent', meaning: 'tooth' },
	{ lemma: 'ventre', meaning: 'stomach' },
	{ lemma: 'épaule', meaning: 'shoulder' },
	{ lemma: 'genou', meaning: 'knee' },
	{ lemma: 'sang', meaning: 'blood' },

	// ===== Food / Drink =====
	{ lemma: 'pain', meaning: 'bread', isBeginner: true },
	{ lemma: 'eau', meaning: 'water', isBeginner: true },
	{ lemma: 'lait', meaning: 'milk', isBeginner: true },
	{ lemma: 'fromage', meaning: 'cheese', isBeginner: true },
	{ lemma: 'viande', meaning: 'meat' },
	{ lemma: 'légume', meaning: 'vegetable' },
	{ lemma: 'fruit', meaning: 'fruit', isBeginner: true },
	{ lemma: 'café', meaning: 'coffee', isBeginner: true },
	{ lemma: 'vin', meaning: 'wine' },
	{ lemma: 'bière', meaning: 'beer' },
	{ lemma: 'thé', meaning: 'tea', isBeginner: true },
	{ lemma: 'sucre', meaning: 'sugar' },
	{ lemma: 'sel', meaning: 'salt' },
	{ lemma: 'beurre', meaning: 'butter' },
	{ lemma: 'oeuf', meaning: 'egg', isBeginner: true },
	{ lemma: 'pomme', meaning: 'apple', isBeginner: true },
	{ lemma: 'poulet', meaning: 'chicken' },
	{ lemma: 'poisson', meaning: 'fish', isBeginner: true },
	{ lemma: 'riz', meaning: 'rice' },
	{ lemma: 'salade', meaning: 'salad' },
	{ lemma: 'soupe', meaning: 'soup' },
	{ lemma: 'gâteau', meaning: 'cake' },
	{ lemma: 'repas', meaning: 'meal' },
	{ lemma: 'petit-déjeuner', meaning: 'breakfast' },
	{ lemma: 'déjeuner', meaning: 'lunch' },
	{ lemma: 'dîner', meaning: 'dinner' },
	{ lemma: 'nourriture', meaning: 'food' },
	{ lemma: 'boisson', meaning: 'drink' },

	// ===== House / Furniture =====
	{ lemma: 'maison', meaning: 'house', isBeginner: true },
	{ lemma: 'chambre', meaning: 'bedroom', isBeginner: true },
	{ lemma: 'cuisine', meaning: 'kitchen', isBeginner: true },
	{ lemma: 'salon', meaning: 'living room' },
	{ lemma: 'table', meaning: 'table', isBeginner: true },
	{ lemma: 'chaise', meaning: 'chair', isBeginner: true },
	{ lemma: 'lit', meaning: 'bed', isBeginner: true },
	{ lemma: 'porte', meaning: 'door', isBeginner: true },
	{ lemma: 'fenêtre', meaning: 'window', isBeginner: true },
	{ lemma: 'mur', meaning: 'wall' },
	{ lemma: 'sol', meaning: 'floor' },
	{ lemma: 'escalier', meaning: 'staircase' },
	{ lemma: 'jardin', meaning: 'garden' },
	{ lemma: 'salle de bain', meaning: 'bathroom' },
	{ lemma: 'appartement', meaning: 'apartment' },
	{ lemma: 'étage', meaning: 'floor/story' },
	{ lemma: 'toit', meaning: 'roof' },
	{ lemma: 'clé', meaning: 'key' },
	{ lemma: 'armoire', meaning: 'wardrobe' },
	{ lemma: 'canapé', meaning: 'sofa' },
	{ lemma: 'miroir', meaning: 'mirror' },
	{ lemma: 'lampe', meaning: 'lamp' },

	// ===== City / Transport =====
	{ lemma: 'ville', meaning: 'city', isBeginner: true },
	{ lemma: 'rue', meaning: 'street', isBeginner: true },
	{ lemma: 'route', meaning: 'road' },
	{ lemma: 'pont', meaning: 'bridge' },
	{ lemma: 'gare', meaning: 'train station' },
	{ lemma: 'aéroport', meaning: 'airport' },
	{ lemma: 'bus', meaning: 'bus', isBeginner: true },
	{ lemma: 'train', meaning: 'train', isBeginner: true },
	{ lemma: 'métro', meaning: 'subway' },
	{ lemma: 'voiture', meaning: 'car', isBeginner: true },
	{ lemma: 'vélo', meaning: 'bicycle', isBeginner: true },
	{ lemma: 'avion', meaning: 'airplane' },
	{ lemma: 'place', meaning: 'square/place' },
	{ lemma: 'magasin', meaning: 'shop', isBeginner: true },
	{ lemma: 'restaurant', meaning: 'restaurant', isBeginner: true },
	{ lemma: 'hôpital', meaning: 'hospital' },
	{ lemma: 'église', meaning: 'church' },
	{ lemma: 'parc', meaning: 'park' },
	{ lemma: 'boulangerie', meaning: 'bakery' },
	{ lemma: 'pharmacie', meaning: 'pharmacy' },
	{ lemma: 'hôtel', meaning: 'hotel' },
	{ lemma: 'musée', meaning: 'museum' },
	{ lemma: 'bibliothèque', meaning: 'library' },
	{ lemma: 'marché', meaning: 'market' },

	// ===== Nature / Weather =====
	{ lemma: 'arbre', meaning: 'tree' },
	{ lemma: 'fleur', meaning: 'flower' },
	{ lemma: 'montagne', meaning: 'mountain' },
	{ lemma: 'mer', meaning: 'sea' },
	{ lemma: 'rivière', meaning: 'river' },
	{ lemma: 'soleil', meaning: 'sun', isBeginner: true },
	{ lemma: 'pluie', meaning: 'rain' },
	{ lemma: 'neige', meaning: 'snow' },
	{ lemma: 'vent', meaning: 'wind' },
	{ lemma: 'ciel', meaning: 'sky' },
	{ lemma: 'terre', meaning: 'earth/land' },
	{ lemma: 'lac', meaning: 'lake' },
	{ lemma: 'forêt', meaning: 'forest' },
	{ lemma: 'plage', meaning: 'beach' },
	{ lemma: 'île', meaning: 'island' },
	{ lemma: 'étoile', meaning: 'star' },
	{ lemma: 'lune', meaning: 'moon' },
	{ lemma: 'nuage', meaning: 'cloud' },
	{ lemma: 'feu', meaning: 'fire' },
	{ lemma: 'pierre', meaning: 'stone' },
	{ lemma: 'herbe', meaning: 'grass' },
	{ lemma: 'feuille', meaning: 'leaf' },

	// ===== School / Work =====
	{ lemma: 'école', meaning: 'school', isBeginner: true },
	{ lemma: 'classe', meaning: 'class', isBeginner: true },
	{ lemma: 'livre', meaning: 'book', isBeginner: true },
	{ lemma: 'cahier', meaning: 'notebook' },
	{ lemma: 'stylo', meaning: 'pen', isBeginner: true },
	{ lemma: 'crayon', meaning: 'pencil', isBeginner: true },
	{ lemma: 'bureau', meaning: 'desk/office' },
	{ lemma: 'travail', meaning: 'work', isBeginner: true },
	{ lemma: 'entreprise', meaning: 'company' },
	{ lemma: 'patron', meaning: 'boss' },
	{ lemma: 'professeur', meaning: 'teacher', isBeginner: true },
	{ lemma: 'élève', meaning: 'student', isBeginner: true },
	{ lemma: 'université', meaning: 'university' },
	{ lemma: 'examen', meaning: 'exam' },
	{ lemma: 'leçon', meaning: 'lesson' },
	{ lemma: 'devoir', meaning: 'homework' },
	{ lemma: 'page', meaning: 'page' },
	{ lemma: 'mot', meaning: 'word' },
	{ lemma: 'phrase', meaning: 'sentence' },
	{ lemma: 'lettre', meaning: 'letter' },
	{ lemma: 'langue', meaning: 'language' },
	{ lemma: 'métier', meaning: 'profession' },
	{ lemma: 'médecin', meaning: 'doctor' },
	{ lemma: 'collègue', meaning: 'colleague' },
	{ lemma: 'réunion', meaning: 'meeting' },

	// ===== Time / Calendar =====
	{ lemma: 'jour', meaning: 'day', isBeginner: true },
	{ lemma: 'nuit', meaning: 'night', isBeginner: true },
	{ lemma: 'matin', meaning: 'morning', isBeginner: true },
	{ lemma: 'soir', meaning: 'evening', isBeginner: true },
	{ lemma: 'heure', meaning: 'hour', isBeginner: true },
	{ lemma: 'minute', meaning: 'minute' },
	{ lemma: 'semaine', meaning: 'week', isBeginner: true },
	{ lemma: 'mois', meaning: 'month', isBeginner: true },
	{ lemma: 'année', meaning: 'year', isBeginner: true },
	{ lemma: 'temps', meaning: 'time/weather' },
	{ lemma: 'moment', meaning: 'moment' },
	{ lemma: 'seconde', meaning: 'second' },
	{ lemma: 'date', meaning: 'date' },
	{ lemma: 'siècle', meaning: 'century' },
	{ lemma: 'fois', meaning: 'time (occurrence)' },
	{ lemma: 'hier', meaning: 'yesterday' },
	{ lemma: 'demain', meaning: 'tomorrow' },
	{ lemma: "aujourd'hui", meaning: 'today' },
	{ lemma: 'anniversaire', meaning: 'birthday' },
	{ lemma: 'vacances', meaning: 'vacation/holidays' },
	{ lemma: 'weekend', meaning: 'weekend' },

	// ===== Animals =====
	{ lemma: 'chat', meaning: 'cat', isBeginner: true },
	{ lemma: 'chien', meaning: 'dog', isBeginner: true },
	{ lemma: 'oiseau', meaning: 'bird', isBeginner: true },
	{ lemma: 'cheval', meaning: 'horse' },
	{ lemma: 'vache', meaning: 'cow' },
	{ lemma: 'cochon', meaning: 'pig' },
	{ lemma: 'mouton', meaning: 'sheep' },
	{ lemma: 'lapin', meaning: 'rabbit' },
	{ lemma: 'souris', meaning: 'mouse' },
	{ lemma: 'canard', meaning: 'duck' },
	{ lemma: 'poule', meaning: 'hen' },
	{ lemma: 'loup', meaning: 'wolf' },
	{ lemma: 'serpent', meaning: 'snake' },
	{ lemma: 'papillon', meaning: 'butterfly' },
	{ lemma: 'abeille', meaning: 'bee' },
	{ lemma: 'fourmi', meaning: 'ant' },
	{ lemma: 'lion', meaning: 'lion' },
	{ lemma: 'singe', meaning: 'monkey' },
	{ lemma: 'grenouille', meaning: 'frog' },
	{ lemma: 'tortue', meaning: 'turtle' },

	// ===== Clothing =====
	{ lemma: 'vêtement', meaning: 'clothing' },
	{ lemma: 'chemise', meaning: 'shirt' },
	{ lemma: 'pantalon', meaning: 'pants' },
	{ lemma: 'robe', meaning: 'dress' },
	{ lemma: 'chaussure', meaning: 'shoe' },
	{ lemma: 'chapeau', meaning: 'hat' },
	{ lemma: 'manteau', meaning: 'coat' },
	{ lemma: 'jupe', meaning: 'skirt' },
	{ lemma: 'pull', meaning: 'sweater' },
	{ lemma: 'cravate', meaning: 'tie' },
	{ lemma: 'chaussette', meaning: 'sock' },
	{ lemma: 'écharpe', meaning: 'scarf' },
	{ lemma: 'gant', meaning: 'glove' },
	{ lemma: 'poche', meaning: 'pocket' },
	{ lemma: 'bouton', meaning: 'button' },
	{ lemma: 'ceinture', meaning: 'belt' },
	{ lemma: 'sac', meaning: 'bag' },
	{ lemma: 'lunettes', meaning: 'glasses' },

	// ===== Abstract =====
	{ lemma: 'idée', meaning: 'idea' },
	{ lemma: 'problème', meaning: 'problem' },
	{ lemma: 'question', meaning: 'question', isBeginner: true },
	{ lemma: 'réponse', meaning: 'answer' },
	{ lemma: 'exemple', meaning: 'example' },
	{ lemma: 'raison', meaning: 'reason' },
	{ lemma: 'chose', meaning: 'thing', isBeginner: true },
	{ lemma: 'vie', meaning: 'life' },
	{ lemma: 'mort', meaning: 'death' },
	{ lemma: 'amour', meaning: 'love' },
	{ lemma: 'bonheur', meaning: 'happiness' },
	{ lemma: 'peur', meaning: 'fear' },
	{ lemma: 'joie', meaning: 'joy' },
	{ lemma: 'colère', meaning: 'anger' },
	{ lemma: 'espoir', meaning: 'hope' },
	{ lemma: 'liberté', meaning: 'freedom' },
	{ lemma: 'paix', meaning: 'peace' },
	{ lemma: 'guerre', meaning: 'war' },
	{ lemma: 'vérité', meaning: 'truth' },
	{ lemma: 'erreur', meaning: 'error/mistake' },
	{ lemma: 'histoire', meaning: 'story/history' },
	{ lemma: 'nom', meaning: 'name', isBeginner: true },
	{ lemma: 'nombre', meaning: 'number' },
	{ lemma: 'pays', meaning: 'country', isBeginner: true },
	{ lemma: 'monde', meaning: 'world' },
	{ lemma: 'droit', meaning: 'right/law' },
	{ lemma: 'loi', meaning: 'law' },
	{ lemma: 'force', meaning: 'strength' },
	{ lemma: 'pouvoir', meaning: 'power' },
	{ lemma: 'partie', meaning: 'part' },
	{ lemma: 'côté', meaning: 'side' },
	{ lemma: 'besoin', meaning: 'need' },
	{ lemma: 'aide', meaning: 'help' },
	{ lemma: 'rêve', meaning: 'dream' },
	{ lemma: 'secret', meaning: 'secret' },
	{ lemma: 'silence', meaning: 'silence' },
	{ lemma: 'différence', meaning: 'difference' },
	{ lemma: 'sens', meaning: 'meaning/sense' },
	{ lemma: 'forme', meaning: 'shape/form' },

	// ===== Technology / Media =====
	{ lemma: 'téléphone', meaning: 'telephone', isBeginner: true },
	{ lemma: 'ordinateur', meaning: 'computer', isBeginner: true },
	{ lemma: 'internet', meaning: 'internet' },
	{ lemma: 'film', meaning: 'film/movie' },
	{ lemma: 'musique', meaning: 'music', isBeginner: true },
	{ lemma: 'journal', meaning: 'newspaper' },
	{ lemma: 'photo', meaning: 'photo' },
	{ lemma: 'télévision', meaning: 'television' },
	{ lemma: 'radio', meaning: 'radio' },
	{ lemma: 'chanson', meaning: 'song' },
	{ lemma: 'image', meaning: 'image/picture' },
	{ lemma: 'écran', meaning: 'screen' },
	{ lemma: 'message', meaning: 'message' },
	{ lemma: 'jeu', meaning: 'game' },
	{ lemma: 'carte', meaning: 'card/map' },
	{ lemma: 'programme', meaning: 'program' },
	{ lemma: 'site', meaning: 'website' },
	{ lemma: 'réseau', meaning: 'network' },

	// ===== Miscellaneous =====
	{ lemma: 'argent', meaning: 'money/silver' },
	{ lemma: 'prix', meaning: 'price/prize' },
	{ lemma: 'couleur', meaning: 'color', isBeginner: true },
	{ lemma: 'lumière', meaning: 'light' },
	{ lemma: 'bruit', meaning: 'noise' },
	{ lemma: 'voix', meaning: 'voice' },
	{ lemma: 'air', meaning: 'air' },
	{ lemma: 'chemin', meaning: 'path/way' },
	{ lemma: 'plan', meaning: 'plan/map' },
	{ lemma: 'projet', meaning: 'project' },
	{ lemma: 'groupe', meaning: 'group' },
	{ lemma: 'état', meaning: 'state/condition' },
	{ lemma: 'situation', meaning: 'situation' },
	{ lemma: 'santé', meaning: 'health' },
	{ lemma: 'sport', meaning: 'sport' },
	{ lemma: 'match', meaning: 'match/game' },
	{ lemma: 'cadeau', meaning: 'gift' },
	{ lemma: 'fête', meaning: 'party/celebration' },
	{ lemma: 'voyage', meaning: 'trip/travel' },
	{ lemma: 'valise', meaning: 'suitcase' },
	{ lemma: 'billet', meaning: 'ticket' },
	{ lemma: 'endroit', meaning: 'place/spot' },
	{ lemma: 'coin', meaning: 'corner' },
	{ lemma: 'sort', meaning: 'fate' },
	{ lemma: 'effort', meaning: 'effort' },
	{ lemma: 'succès', meaning: 'success' }
];
