export const nouns = [
	// ===== People / Family =====
	{ word: 'homme', translation: 'man', isBeginner: true },
	{ word: 'femme', translation: 'woman', isBeginner: true },
	{ word: 'enfant', translation: 'child', isBeginner: true },
	{ word: 'père', translation: 'father', isBeginner: true },
	{ word: 'mère', translation: 'mother', isBeginner: true },
	{ word: 'fils', translation: 'son', isBeginner: true },
	{ word: 'fille', translation: 'daughter', isBeginner: true },
	{ word: 'frère', translation: 'brother', isBeginner: true },
	{ word: 'soeur', translation: 'sister', isBeginner: true },
	{ word: 'ami', translation: 'friend', isBeginner: true },
	{ word: 'famille', translation: 'family', isBeginner: true },
	{ word: 'bébé', translation: 'baby', isBeginner: true },
	{ word: 'garçon', translation: 'boy', isBeginner: true },
	{ word: 'mari', translation: 'husband' },
	{ word: 'épouse', translation: 'wife' },
	{ word: 'voisin', translation: 'neighbor' },
	{ word: 'oncle', translation: 'uncle' },
	{ word: 'tante', translation: 'aunt' },
	{ word: 'cousin', translation: 'cousin' },
	{ word: 'grand-père', translation: 'grandfather' },
	{ word: 'grand-mère', translation: 'grandmother' },
	{ word: 'personne', translation: 'person', isBeginner: true },
	{ word: 'gens', translation: 'people' },
	{ word: 'monsieur', translation: 'sir', isBeginner: true },
	{ word: 'madame', translation: 'madam', isBeginner: true },

	// ===== Body =====
	{ word: 'tête', translation: 'head', isBeginner: true },
	{ word: 'main', translation: 'hand', isBeginner: true },
	{ word: 'oeil', translation: 'eye', isBeginner: true },
	{ word: 'bouche', translation: 'mouth', isBeginner: true },
	{ word: 'coeur', translation: 'heart' },
	{ word: 'bras', translation: 'arm' },
	{ word: 'jambe', translation: 'leg' },
	{ word: 'dos', translation: 'back' },
	{ word: 'pied', translation: 'foot', isBeginner: true },
	{ word: 'doigt', translation: 'finger' },
	{ word: 'nez', translation: 'nose', isBeginner: true },
	{ word: 'oreille', translation: 'ear' },
	{ word: 'cheveux', translation: 'hair' },
	{ word: 'visage', translation: 'face' },
	{ word: 'corps', translation: 'body' },
	{ word: 'dent', translation: 'tooth' },
	{ word: 'ventre', translation: 'stomach' },
	{ word: 'épaule', translation: 'shoulder' },
	{ word: 'genou', translation: 'knee' },
	{ word: 'sang', translation: 'blood' },

	// ===== Food / Drink =====
	{ word: 'pain', translation: 'bread', isBeginner: true },
	{ word: 'eau', translation: 'water', isBeginner: true },
	{ word: 'lait', translation: 'milk', isBeginner: true },
	{ word: 'fromage', translation: 'cheese', isBeginner: true },
	{ word: 'viande', translation: 'meat' },
	{ word: 'légume', translation: 'vegetable' },
	{ word: 'fruit', translation: 'fruit', isBeginner: true },
	{ word: 'café', translation: 'coffee', isBeginner: true },
	{ word: 'vin', translation: 'wine' },
	{ word: 'bière', translation: 'beer' },
	{ word: 'thé', translation: 'tea', isBeginner: true },
	{ word: 'sucre', translation: 'sugar' },
	{ word: 'sel', translation: 'salt' },
	{ word: 'beurre', translation: 'butter' },
	{ word: 'oeuf', translation: 'egg', isBeginner: true },
	{ word: 'pomme', translation: 'apple', isBeginner: true },
	{ word: 'poulet', translation: 'chicken' },
	{ word: 'poisson', translation: 'fish', isBeginner: true },
	{ word: 'riz', translation: 'rice' },
	{ word: 'salade', translation: 'salad' },
	{ word: 'soupe', translation: 'soup' },
	{ word: 'gâteau', translation: 'cake' },
	{ word: 'repas', translation: 'meal' },
	{ word: 'petit-déjeuner', translation: 'breakfast' },
	{ word: 'déjeuner', translation: 'lunch' },
	{ word: 'dîner', translation: 'dinner' },
	{ word: 'nourriture', translation: 'food' },
	{ word: 'boisson', translation: 'drink' },

	// ===== House / Furniture =====
	{ word: 'maison', translation: 'house', isBeginner: true },
	{ word: 'chambre', translation: 'bedroom', isBeginner: true },
	{ word: 'cuisine', translation: 'kitchen', isBeginner: true },
	{ word: 'salon', translation: 'living room' },
	{ word: 'table', translation: 'table', isBeginner: true },
	{ word: 'chaise', translation: 'chair', isBeginner: true },
	{ word: 'lit', translation: 'bed', isBeginner: true },
	{ word: 'porte', translation: 'door', isBeginner: true },
	{ word: 'fenêtre', translation: 'window', isBeginner: true },
	{ word: 'mur', translation: 'wall' },
	{ word: 'sol', translation: 'floor' },
	{ word: 'escalier', translation: 'staircase' },
	{ word: 'jardin', translation: 'garden' },
	{ word: 'salle de bain', translation: 'bathroom' },
	{ word: 'appartement', translation: 'apartment' },
	{ word: 'étage', translation: 'floor/story' },
	{ word: 'toit', translation: 'roof' },
	{ word: 'clé', translation: 'key' },
	{ word: 'armoire', translation: 'wardrobe' },
	{ word: 'canapé', translation: 'sofa' },
	{ word: 'miroir', translation: 'mirror' },
	{ word: 'lampe', translation: 'lamp' },

	// ===== City / Transport =====
	{ word: 'ville', translation: 'city', isBeginner: true },
	{ word: 'rue', translation: 'street', isBeginner: true },
	{ word: 'route', translation: 'road' },
	{ word: 'pont', translation: 'bridge' },
	{ word: 'gare', translation: 'train station' },
	{ word: 'aéroport', translation: 'airport' },
	{ word: 'bus', translation: 'bus', isBeginner: true },
	{ word: 'train', translation: 'train', isBeginner: true },
	{ word: 'métro', translation: 'subway' },
	{ word: 'voiture', translation: 'car', isBeginner: true },
	{ word: 'vélo', translation: 'bicycle', isBeginner: true },
	{ word: 'avion', translation: 'airplane' },
	{ word: 'place', translation: 'square/place' },
	{ word: 'magasin', translation: 'shop', isBeginner: true },
	{ word: 'restaurant', translation: 'restaurant', isBeginner: true },
	{ word: 'hôpital', translation: 'hospital' },
	{ word: 'église', translation: 'church' },
	{ word: 'parc', translation: 'park' },
	{ word: 'boulangerie', translation: 'bakery' },
	{ word: 'pharmacie', translation: 'pharmacy' },
	{ word: 'hôtel', translation: 'hotel' },
	{ word: 'musée', translation: 'museum' },
	{ word: 'bibliothèque', translation: 'library' },
	{ word: 'marché', translation: 'market' },

	// ===== Nature / Weather =====
	{ word: 'arbre', translation: 'tree' },
	{ word: 'fleur', translation: 'flower' },
	{ word: 'montagne', translation: 'mountain' },
	{ word: 'mer', translation: 'sea' },
	{ word: 'rivière', translation: 'river' },
	{ word: 'soleil', translation: 'sun', isBeginner: true },
	{ word: 'pluie', translation: 'rain' },
	{ word: 'neige', translation: 'snow' },
	{ word: 'vent', translation: 'wind' },
	{ word: 'ciel', translation: 'sky' },
	{ word: 'terre', translation: 'earth/land' },
	{ word: 'lac', translation: 'lake' },
	{ word: 'forêt', translation: 'forest' },
	{ word: 'plage', translation: 'beach' },
	{ word: 'île', translation: 'island' },
	{ word: 'étoile', translation: 'star' },
	{ word: 'lune', translation: 'moon' },
	{ word: 'nuage', translation: 'cloud' },
	{ word: 'feu', translation: 'fire' },
	{ word: 'pierre', translation: 'stone' },
	{ word: 'herbe', translation: 'grass' },
	{ word: 'feuille', translation: 'leaf' },

	// ===== School / Work =====
	{ word: 'école', translation: 'school', isBeginner: true },
	{ word: 'classe', translation: 'class', isBeginner: true },
	{ word: 'livre', translation: 'book', isBeginner: true },
	{ word: 'cahier', translation: 'notebook' },
	{ word: 'stylo', translation: 'pen', isBeginner: true },
	{ word: 'crayon', translation: 'pencil', isBeginner: true },
	{ word: 'bureau', translation: 'desk/office' },
	{ word: 'travail', translation: 'work', isBeginner: true },
	{ word: 'entreprise', translation: 'company' },
	{ word: 'patron', translation: 'boss' },
	{ word: 'professeur', translation: 'teacher', isBeginner: true },
	{ word: 'élève', translation: 'student', isBeginner: true },
	{ word: 'université', translation: 'university' },
	{ word: 'examen', translation: 'exam' },
	{ word: 'leçon', translation: 'lesson' },
	{ word: 'devoir', translation: 'homework' },
	{ word: 'page', translation: 'page' },
	{ word: 'mot', translation: 'word' },
	{ word: 'phrase', translation: 'sentence' },
	{ word: 'lettre', translation: 'letter' },
	{ word: 'langue', translation: 'language' },
	{ word: 'métier', translation: 'profession' },
	{ word: 'médecin', translation: 'doctor' },
	{ word: 'collègue', translation: 'colleague' },
	{ word: 'réunion', translation: 'meeting' },

	// ===== Time / Calendar =====
	{ word: 'jour', translation: 'day', isBeginner: true },
	{ word: 'nuit', translation: 'night', isBeginner: true },
	{ word: 'matin', translation: 'morning', isBeginner: true },
	{ word: 'soir', translation: 'evening', isBeginner: true },
	{ word: 'heure', translation: 'hour', isBeginner: true },
	{ word: 'minute', translation: 'minute' },
	{ word: 'semaine', translation: 'week', isBeginner: true },
	{ word: 'mois', translation: 'month', isBeginner: true },
	{ word: 'année', translation: 'year', isBeginner: true },
	{ word: 'temps', translation: 'time/weather' },
	{ word: 'moment', translation: 'moment' },
	{ word: 'seconde', translation: 'second' },
	{ word: 'date', translation: 'date' },
	{ word: 'siècle', translation: 'century' },
	{ word: 'fois', translation: 'time (occurrence)' },
	{ word: 'hier', translation: 'yesterday' },
	{ word: 'demain', translation: 'tomorrow' },
	{ word: "aujourd'hui", translation: 'today' },
	{ word: 'anniversaire', translation: 'birthday' },
	{ word: 'vacances', translation: 'vacation/holidays' },
	{ word: 'weekend', translation: 'weekend' },

	// ===== Animals =====
	{ word: 'chat', translation: 'cat', isBeginner: true },
	{ word: 'chien', translation: 'dog', isBeginner: true },
	{ word: 'oiseau', translation: 'bird', isBeginner: true },
	{ word: 'cheval', translation: 'horse' },
	{ word: 'vache', translation: 'cow' },
	{ word: 'cochon', translation: 'pig' },
	{ word: 'mouton', translation: 'sheep' },
	{ word: 'lapin', translation: 'rabbit' },
	{ word: 'souris', translation: 'mouse' },
	{ word: 'canard', translation: 'duck' },
	{ word: 'poule', translation: 'hen' },
	{ word: 'loup', translation: 'wolf' },
	{ word: 'serpent', translation: 'snake' },
	{ word: 'papillon', translation: 'butterfly' },
	{ word: 'abeille', translation: 'bee' },
	{ word: 'fourmi', translation: 'ant' },
	{ word: 'lion', translation: 'lion' },
	{ word: 'singe', translation: 'monkey' },
	{ word: 'grenouille', translation: 'frog' },
	{ word: 'tortue', translation: 'turtle' },

	// ===== Clothing =====
	{ word: 'vêtement', translation: 'clothing' },
	{ word: 'chemise', translation: 'shirt' },
	{ word: 'pantalon', translation: 'pants' },
	{ word: 'robe', translation: 'dress' },
	{ word: 'chaussure', translation: 'shoe' },
	{ word: 'chapeau', translation: 'hat' },
	{ word: 'manteau', translation: 'coat' },
	{ word: 'jupe', translation: 'skirt' },
	{ word: 'pull', translation: 'sweater' },
	{ word: 'cravate', translation: 'tie' },
	{ word: 'chaussette', translation: 'sock' },
	{ word: 'écharpe', translation: 'scarf' },
	{ word: 'gant', translation: 'glove' },
	{ word: 'poche', translation: 'pocket' },
	{ word: 'bouton', translation: 'button' },
	{ word: 'ceinture', translation: 'belt' },
	{ word: 'sac', translation: 'bag' },
	{ word: 'lunettes', translation: 'glasses' },

	// ===== Abstract =====
	{ word: 'idée', translation: 'idea' },
	{ word: 'problème', translation: 'problem' },
	{ word: 'question', translation: 'question', isBeginner: true },
	{ word: 'réponse', translation: 'answer' },
	{ word: 'exemple', translation: 'example' },
	{ word: 'raison', translation: 'reason' },
	{ word: 'chose', translation: 'thing', isBeginner: true },
	{ word: 'vie', translation: 'life' },
	{ word: 'mort', translation: 'death' },
	{ word: 'amour', translation: 'love' },
	{ word: 'bonheur', translation: 'happiness' },
	{ word: 'peur', translation: 'fear' },
	{ word: 'joie', translation: 'joy' },
	{ word: 'colère', translation: 'anger' },
	{ word: 'espoir', translation: 'hope' },
	{ word: 'liberté', translation: 'freedom' },
	{ word: 'paix', translation: 'peace' },
	{ word: 'guerre', translation: 'war' },
	{ word: 'vérité', translation: 'truth' },
	{ word: 'erreur', translation: 'error/mistake' },
	{ word: 'histoire', translation: 'story/history' },
	{ word: 'nom', translation: 'name', isBeginner: true },
	{ word: 'nombre', translation: 'number' },
	{ word: 'pays', translation: 'country', isBeginner: true },
	{ word: 'monde', translation: 'world' },
	{ word: 'droit', translation: 'right/law' },
	{ word: 'loi', translation: 'law' },
	{ word: 'force', translation: 'strength' },
	{ word: 'pouvoir', translation: 'power' },
	{ word: 'partie', translation: 'part' },
	{ word: 'côté', translation: 'side' },
	{ word: 'besoin', translation: 'need' },
	{ word: 'aide', translation: 'help' },
	{ word: 'rêve', translation: 'dream' },
	{ word: 'secret', translation: 'secret' },
	{ word: 'silence', translation: 'silence' },
	{ word: 'différence', translation: 'difference' },
	{ word: 'sens', translation: 'meaning/sense' },
	{ word: 'forme', translation: 'shape/form' },

	// ===== Technology / Media =====
	{ word: 'téléphone', translation: 'telephone', isBeginner: true },
	{ word: 'ordinateur', translation: 'computer', isBeginner: true },
	{ word: 'internet', translation: 'internet' },
	{ word: 'film', translation: 'film/movie' },
	{ word: 'musique', translation: 'music', isBeginner: true },
	{ word: 'journal', translation: 'newspaper' },
	{ word: 'photo', translation: 'photo' },
	{ word: 'télévision', translation: 'television' },
	{ word: 'radio', translation: 'radio' },
	{ word: 'chanson', translation: 'song' },
	{ word: 'image', translation: 'image/picture' },
	{ word: 'écran', translation: 'screen' },
	{ word: 'message', translation: 'message' },
	{ word: 'jeu', translation: 'game' },
	{ word: 'carte', translation: 'card/map' },
	{ word: 'programme', translation: 'program' },
	{ word: 'site', translation: 'website' },
	{ word: 'réseau', translation: 'network' },

	// ===== Miscellaneous =====
	{ word: 'argent', translation: 'money/silver' },
	{ word: 'prix', translation: 'price/prize' },
	{ word: 'couleur', translation: 'color', isBeginner: true },
	{ word: 'lumière', translation: 'light' },
	{ word: 'bruit', translation: 'noise' },
	{ word: 'voix', translation: 'voice' },
	{ word: 'air', translation: 'air' },
	{ word: 'chemin', translation: 'path/way' },
	{ word: 'plan', translation: 'plan/map' },
	{ word: 'projet', translation: 'project' },
	{ word: 'groupe', translation: 'group' },
	{ word: 'état', translation: 'state/condition' },
	{ word: 'situation', translation: 'situation' },
	{ word: 'santé', translation: 'health' },
	{ word: 'sport', translation: 'sport' },
	{ word: 'match', translation: 'match/game' },
	{ word: 'cadeau', translation: 'gift' },
	{ word: 'fête', translation: 'party/celebration' },
	{ word: 'voyage', translation: 'trip/travel' },
	{ word: 'valise', translation: 'suitcase' },
	{ word: 'billet', translation: 'ticket' },
	{ word: 'endroit', translation: 'place/spot' },
	{ word: 'coin', translation: 'corner' },
	{ word: 'sort', translation: 'fate' },
	{ word: 'effort', translation: 'effort' },
	{ word: 'succès', translation: 'success' },
];
