export const prepositions = [
	// Simple prepositions
	{ word: 'à', translation: 'at/to', isBeginner: true },
	{ word: 'de', translation: 'of/from', isBeginner: true },
	{ word: 'en', translation: 'in/to', isBeginner: true },
	{ word: 'dans', translation: 'in/inside', isBeginner: true },
	{ word: 'sur', translation: 'on/upon', isBeginner: true },
	{ word: 'sous', translation: 'under/beneath' },
	{ word: 'avec', translation: 'with', isBeginner: true },
	{ word: 'sans', translation: 'without', isBeginner: true },
	{ word: 'pour', translation: 'for', isBeginner: true },
	{ word: 'par', translation: 'by/through' },
	{ word: 'vers', translation: 'toward/around' },
	{ word: 'chez', translation: 'at the home of/at', isBeginner: true },
	{ word: 'entre', translation: 'between/among' },
	{ word: 'contre', translation: 'against' },
	{ word: 'devant', translation: 'in front of/before' },
	{ word: 'derrière', translation: 'behind' },
	{ word: 'avant', translation: 'before (time)' },
	{ word: 'après', translation: 'after' },
	{ word: 'pendant', translation: 'during' },
	{ word: 'depuis', translation: 'since/for (duration)' },
	{ word: "jusqu'à", translation: 'until/up to' },
	{ word: 'malgré', translation: 'despite/in spite of' },
	{ word: 'selon', translation: 'according to' },
	{ word: 'sauf', translation: 'except' },
	{ word: 'hormis', translation: 'apart from/except for' },
	{ word: 'parmi', translation: 'among/amongst' },

	// Compound prepositions
	{ word: 'à côté de', translation: 'next to/beside' },
	{ word: 'en face de', translation: 'across from/opposite' },
	{ word: 'au-dessus de', translation: 'above/over' },
	{ word: 'au-dessous de', translation: 'below/underneath' },
	{ word: 'à travers', translation: 'through/across' },
	{ word: 'au lieu de', translation: 'instead of' },
	{ word: 'grâce à', translation: 'thanks to' },
	{ word: 'à cause de', translation: 'because of' },
	{ word: 'en dehors de', translation: 'outside of' },
	{ word: 'au milieu de', translation: 'in the middle of' },
	{ word: 'autour de', translation: 'around' },
	{ word: 'le long de', translation: 'along' },
	{ word: 'loin de', translation: 'far from' },
	{ word: 'près de', translation: 'near/close to' },
	{ word: 'à propos de', translation: 'about/regarding' },
	{ word: 'quant à', translation: 'as for/regarding' },
	{ word: 'au bout de', translation: 'at the end of/after' },
	{ word: 'à partir de', translation: 'from/starting from' },
	{ word: 'en dépit de', translation: 'in spite of/despite' },
	{ word: 'faute de', translation: 'for lack of/due to lack of' },
];
