export const prepositions = [
  // Simple prepositions
  { lemma: 'à', meaning: 'at/to', isBeginner: true },
  { lemma: 'de', meaning: 'of/from', isBeginner: true },
  { lemma: 'en', meaning: 'in/to', isBeginner: true },
  { lemma: 'dans', meaning: 'in/inside', isBeginner: true },
  { lemma: 'sur', meaning: 'on/upon', isBeginner: true },
  { lemma: 'sous', meaning: 'under/beneath' },
  { lemma: 'avec', meaning: 'with', isBeginner: true },
  { lemma: 'sans', meaning: 'without', isBeginner: true },
  { lemma: 'pour', meaning: 'for', isBeginner: true },
  { lemma: 'par', meaning: 'by/through' },
  { lemma: 'vers', meaning: 'toward/around' },
  { lemma: 'chez', meaning: 'at the home of/at', isBeginner: true },
  { lemma: 'entre', meaning: 'between/among' },
  { lemma: 'contre', meaning: 'against' },
  { lemma: 'devant', meaning: 'in front of/before' },
  { lemma: 'derrière', meaning: 'behind' },
  { lemma: 'avant', meaning: 'before (time)' },
  { lemma: 'après', meaning: 'after' },
  { lemma: 'pendant', meaning: 'during' },
  { lemma: 'depuis', meaning: 'since/for (duration)' },
  { lemma: "jusqu'à", meaning: 'until/up to' },
  { lemma: 'malgré', meaning: 'despite/in spite of' },
  { lemma: 'selon', meaning: 'according to' },
  { lemma: 'sauf', meaning: 'except' },
  { lemma: 'hormis', meaning: 'apart from/except for' },
  { lemma: 'parmi', meaning: 'among/amongst' },

  // Compound prepositions
  { lemma: 'à côté de', meaning: 'next to/beside' },
  { lemma: 'en face de', meaning: 'across from/opposite' },
  { lemma: 'au-dessus de', meaning: 'above/over' },
  { lemma: 'au-dessous de', meaning: 'below/underneath' },
  { lemma: 'à travers', meaning: 'through/across' },
  { lemma: 'au lieu de', meaning: 'instead of' },
  { lemma: 'grâce à', meaning: 'thanks to' },
  { lemma: 'à cause de', meaning: 'because of' },
  { lemma: 'en dehors de', meaning: 'outside of' },
  { lemma: 'au milieu de', meaning: 'in the middle of' },
  { lemma: 'autour de', meaning: 'around' },
  { lemma: 'le long de', meaning: 'along' },
  { lemma: 'loin de', meaning: 'far from' },
  { lemma: 'près de', meaning: 'near/close to' },
  { lemma: 'à propos de', meaning: 'about/regarding' },
  { lemma: 'quant à', meaning: 'as for/regarding' },
  { lemma: 'au bout de', meaning: 'at the end of/after' },
  { lemma: 'à partir de', meaning: 'from/starting from' },
  { lemma: 'en dépit de', meaning: 'in spite of/despite' },
  { lemma: 'faute de', meaning: 'for lack of/due to lack of' }
];
