export const verbs = [
	// Essential verbs
	{ word: 'être', translation: 'to be', isBeginner: true },
	{ word: 'avoir', translation: 'to have', isBeginner: true },
	{ word: 'aller', translation: 'to go', isBeginner: true },
	{ word: 'faire', translation: 'to do/make', isBeginner: true },
	{ word: 'dire', translation: 'to say/tell', isBeginner: true },
	{ word: 'pouvoir', translation: 'can/to be able to', isBeginner: true },
	{ word: 'vouloir', translation: 'to want', isBeginner: true },
	{ word: 'savoir', translation: 'to know (a fact)', isBeginner: true },
	{ word: 'devoir', translation: 'to have to/must', isBeginner: true },
	{ word: 'falloir', translation: 'to be necessary', isBeginner: true },
	{ word: 'voir', translation: 'to see', isBeginner: true },
	{ word: 'prendre', translation: 'to take', isBeginner: true },
	{ word: 'donner', translation: 'to give', isBeginner: true },
	{ word: 'mettre', translation: 'to put/place', isBeginner: true },
	{ word: 'tenir', translation: 'to hold', isBeginner: true },

	// Movement verbs
	{ word: 'venir', translation: 'to come', isBeginner: true },
	{ word: 'partir', translation: 'to leave/depart', isBeginner: true },
	{ word: 'arriver', translation: 'to arrive', isBeginner: true },
	{ word: 'sortir', translation: 'to go out', isBeginner: true },
	{ word: 'entrer', translation: 'to enter', isBeginner: true },
	{ word: 'monter', translation: 'to go up/climb', isBeginner: true },
	{ word: 'descendre', translation: 'to go down/descend', isBeginner: true },
	{ word: 'tomber', translation: 'to fall', isBeginner: true },
	{ word: 'courir', translation: 'to run', isBeginner: true },
	{ word: 'marcher', translation: 'to walk', isBeginner: true },
	{ word: 'revenir', translation: 'to come back' },
	{ word: 'retourner', translation: 'to return/go back' },
	{ word: 'passer', translation: 'to pass/spend (time)', isBeginner: true },
	{ word: 'traverser', translation: 'to cross' },
	{ word: 'se promener', translation: 'to take a walk' },
	{ word: 'nager', translation: 'to swim' },
	{ word: 'voler', translation: 'to fly/steal' },
	{ word: 'glisser', translation: 'to slide/slip' },
	{ word: 'reculer', translation: 'to step back/reverse' },
	{ word: 'avancer', translation: 'to move forward/advance' },
	{ word: 'se dépêcher', translation: 'to hurry' },

	// Communication verbs
	{ word: 'parler', translation: 'to speak/talk', isBeginner: true },
	{ word: 'écrire', translation: 'to write', isBeginner: true },
	{ word: 'lire', translation: 'to read', isBeginner: true },
	{ word: 'écouter', translation: 'to listen', isBeginner: true },
	{ word: 'répondre', translation: 'to answer/reply', isBeginner: true },
	{ word: 'demander', translation: 'to ask', isBeginner: true },
	{ word: 'appeler', translation: 'to call', isBeginner: true },
	{ word: 'expliquer', translation: 'to explain' },
	{ word: 'raconter', translation: 'to tell/narrate' },
	{ word: 'discuter', translation: 'to discuss' },
	{ word: 'annoncer', translation: 'to announce' },
	{ word: 'décrire', translation: 'to describe' },
	{ word: 'murmurer', translation: 'to whisper/murmur' },
	{ word: 'crier', translation: 'to shout/scream' },
	{ word: 'prononcer', translation: 'to pronounce' },
	{ word: 'traduire', translation: 'to translate' },
	{ word: 'répéter', translation: 'to repeat', isBeginner: true },
	{ word: 'suggérer', translation: 'to suggest' },
	{ word: 'promettre', translation: 'to promise' },
	{ word: 'avouer', translation: 'to confess/admit' },

	// Daily life verbs
	{ word: 'manger', translation: 'to eat', isBeginner: true },
	{ word: 'boire', translation: 'to drink', isBeginner: true },
	{ word: 'dormir', translation: 'to sleep', isBeginner: true },
	{ word: 'travailler', translation: 'to work', isBeginner: true },
	{ word: 'jouer', translation: 'to play', isBeginner: true },
	{ word: 'regarder', translation: 'to watch/look at', isBeginner: true },
	{ word: 'chercher', translation: 'to look for/search', isBeginner: true },
	{ word: 'trouver', translation: 'to find', isBeginner: true },
	{ word: 'acheter', translation: 'to buy', isBeginner: true },
	{ word: 'vendre', translation: 'to sell' },
	{ word: 'payer', translation: 'to pay', isBeginner: true },
	{ word: 'cuisiner', translation: 'to cook' },
	{ word: 'se lever', translation: 'to get up', isBeginner: true },
	{ word: 'se coucher', translation: 'to go to bed', isBeginner: true },
	{ word: 'se laver', translation: 'to wash oneself', isBeginner: true },
	{ word: "s'habiller", translation: 'to get dressed', isBeginner: true },
	{ word: 'conduire', translation: 'to drive' },
	{ word: 'nettoyer', translation: 'to clean' },
	{ word: 'ranger', translation: 'to tidy up/put away' },
	{ word: 'porter', translation: 'to carry/wear', isBeginner: true },
	{ word: 'ouvrir', translation: 'to open', isBeginner: true },
	{ word: 'fermer', translation: 'to close', isBeginner: true },
	{ word: 'habiter', translation: 'to live (reside)', isBeginner: true },
	{ word: 'vivre', translation: 'to live (be alive)' },
	{ word: 'utiliser', translation: 'to use' },
	{ word: 'préparer', translation: 'to prepare' },
	{ word: 'commencer', translation: 'to begin/start', isBeginner: true },
	{ word: 'finir', translation: 'to finish', isBeginner: true },
	{ word: 'attendre', translation: 'to wait', isBeginner: true },
	{ word: 'se réveiller', translation: 'to wake up' },

	// Cognition verbs
	{ word: 'penser', translation: 'to think', isBeginner: true },
	{ word: 'croire', translation: 'to believe' },
	{ word: 'comprendre', translation: 'to understand', isBeginner: true },
	{ word: 'connaître', translation: 'to know (person/place)', isBeginner: true },
	{ word: 'oublier', translation: 'to forget' },
	{ word: 'se souvenir', translation: 'to remember' },
	{ word: 'apprendre', translation: 'to learn', isBeginner: true },
	{ word: 'étudier', translation: 'to study', isBeginner: true },
	{ word: 'reconnaître', translation: 'to recognize' },
	{ word: 'réfléchir', translation: 'to reflect/think about' },
	{ word: 'imaginer', translation: 'to imagine' },
	{ word: 'douter', translation: 'to doubt' },
	{ word: 'supposer', translation: 'to suppose/assume' },
	{ word: 'deviner', translation: 'to guess' },
	{ word: 'remarquer', translation: 'to notice' },
	{ word: 'se rendre compte', translation: 'to realize' },
	{ word: 'juger', translation: 'to judge' },
	{ word: 'considérer', translation: 'to consider' },

	// Emotion verbs
	{ word: 'aimer', translation: 'to love/like', isBeginner: true },
	{ word: 'détester', translation: 'to hate' },
	{ word: 'préférer', translation: 'to prefer', isBeginner: true },
	{ word: 'espérer', translation: 'to hope' },
	{ word: 'craindre', translation: 'to fear' },
	{ word: 'regretter', translation: 'to regret' },
	{ word: "s'inquiéter", translation: 'to worry' },
	{ word: 'adorer', translation: 'to adore', isBeginner: true },
	{ word: "s'ennuyer", translation: 'to be bored' },
	{ word: 'se fâcher', translation: 'to get angry' },
	{ word: 'pleurer', translation: 'to cry' },
	{ word: 'rire', translation: 'to laugh' },
	{ word: 'sourire', translation: 'to smile' },
	{ word: 'souffrir', translation: 'to suffer' },
	{ word: 'profiter', translation: 'to enjoy/take advantage' },
	{ word: "s'amuser", translation: 'to have fun' },
	{ word: 'se sentir', translation: 'to feel' },
	{ word: 'surprendre', translation: 'to surprise' },

	// Creation verbs
	{ word: 'créer', translation: 'to create' },
	{ word: 'construire', translation: 'to build/construct' },
	{ word: 'produire', translation: 'to produce' },
	{ word: 'développer', translation: 'to develop' },
	{ word: 'inventer', translation: 'to invent' },
	{ word: 'dessiner', translation: 'to draw' },
	{ word: 'peindre', translation: 'to paint' },
	{ word: 'fabriquer', translation: 'to manufacture/make' },
	{ word: 'composer', translation: 'to compose' },
	{ word: 'concevoir', translation: 'to design/conceive' },
	{ word: 'réaliser', translation: 'to achieve/realize' },
	{ word: 'établir', translation: 'to establish' },
	{ word: 'fonder', translation: 'to found/establish' },

	// Change verbs
	{ word: 'changer', translation: 'to change' },
	{ word: 'devenir', translation: 'to become' },
	{ word: 'grandir', translation: 'to grow (up)' },
	{ word: 'améliorer', translation: 'to improve' },
	{ word: 'transformer', translation: 'to transform' },
	{ word: 'augmenter', translation: 'to increase' },
	{ word: 'diminuer', translation: 'to decrease/diminish' },
	{ word: 'modifier', translation: 'to modify' },
	{ word: 'remplacer', translation: 'to replace' },
	{ word: 'adapter', translation: 'to adapt' },
	{ word: 'évoluer', translation: 'to evolve' },
	{ word: 'disparaître', translation: 'to disappear' },
	{ word: 'apparaître', translation: 'to appear' },

	// Social verbs
	{ word: 'rencontrer', translation: 'to meet' },
	{ word: 'inviter', translation: 'to invite' },
	{ word: 'aider', translation: 'to help', isBeginner: true },
	{ word: 'partager', translation: 'to share' },
	{ word: 'accompagner', translation: 'to accompany' },
	{ word: 'suivre', translation: 'to follow' },
	{ word: 'présenter', translation: 'to introduce/present', isBeginner: true },
	{ word: 'remercier', translation: 'to thank' },
	{ word: 'féliciter', translation: 'to congratulate' },
	{ word: 'accueillir', translation: 'to welcome' },
	{ word: 'se marier', translation: 'to get married' },
	{ word: 'divorcer', translation: 'to divorce' },
	{ word: 'saluer', translation: 'to greet' },
	{ word: 'embrasser', translation: 'to kiss/hug' },
	{ word: 'quitter', translation: 'to leave (someone/place)' },

	// Common -er verbs (various levels)
	{ word: 'chanter', translation: 'to sing' },
	{ word: 'danser', translation: 'to dance' },
	{ word: 'voyager', translation: 'to travel' },
	{ word: 'visiter', translation: 'to visit (a place)' },
	{ word: 'compter', translation: 'to count' },
	{ word: 'essayer', translation: 'to try' },
	{ word: 'envoyer', translation: 'to send' },
	{ word: 'toucher', translation: 'to touch' },
	{ word: 'garder', translation: 'to keep/guard' },
	{ word: 'laisser', translation: 'to leave/let' },
	{ word: 'montrer', translation: 'to show', isBeginner: true },
	{ word: 'tirer', translation: 'to pull/shoot' },
	{ word: 'pousser', translation: 'to push' },
	{ word: 'jeter', translation: 'to throw' },
	{ word: 'lever', translation: 'to raise/lift' },
	{ word: 'poser', translation: 'to put down/ask (a question)' },
	{ word: 'arrêter', translation: 'to stop' },
	{ word: 'continuer', translation: 'to continue' },
	{ word: 'rester', translation: 'to stay/remain', isBeginner: true },
	{ word: 'manquer', translation: 'to miss/lack' },
	{ word: 'gagner', translation: 'to win/earn' },
	{ word: 'perdre', translation: 'to lose' },
	{ word: 'sauver', translation: 'to save/rescue' },
	{ word: 'occuper', translation: 'to occupy' },
	{ word: 'exister', translation: 'to exist' },
	{ word: 'représenter', translation: 'to represent' },
	{ word: 'accepter', translation: 'to accept' },
	{ word: 'refuser', translation: 'to refuse' },
	{ word: 'proposer', translation: 'to propose/suggest' },
	{ word: 'organiser', translation: 'to organize' },
	{ word: 'participer', translation: 'to participate' },
	{ word: 'séparer', translation: 'to separate' },
	{ word: 'retrouver', translation: 'to find again/meet up' },
	{ word: 'installer', translation: 'to install/settle' },
	{ word: 'vérifier', translation: 'to verify/check' },
	{ word: 'respecter', translation: 'to respect' },
	{ word: 'exprimer', translation: 'to express' },
	{ word: 'empêcher', translation: 'to prevent' },
	{ word: 'dépenser', translation: 'to spend (money)' },
	{ word: 'économiser', translation: 'to save (money)' },
	{ word: 'louer', translation: 'to rent' },
	{ word: 'déménager', translation: 'to move (house)' },
	{ word: 'protéger', translation: 'to protect' },
	{ word: 'brûler', translation: 'to burn' },
	{ word: 'casser', translation: 'to break' },
	{ word: 'couper', translation: 'to cut' },
	{ word: 'frapper', translation: 'to hit/knock' },
	{ word: 'ramasser', translation: 'to pick up/collect' },
	{ word: 'attraper', translation: 'to catch' },

	// Common -ir verbs (various levels)
	{ word: 'choisir', translation: 'to choose' },
	{ word: 'réussir', translation: 'to succeed' },
	{ word: 'remplir', translation: 'to fill' },
	{ word: 'obéir', translation: 'to obey' },
	{ word: 'punir', translation: 'to punish' },
	{ word: 'guérir', translation: 'to heal/cure' },
	{ word: 'réunir', translation: 'to gather/reunite' },
	{ word: 'nourrir', translation: 'to feed/nourish' },
	{ word: 'ralentir', translation: 'to slow down' },
	{ word: 'agir', translation: 'to act' },
	{ word: 'réagir', translation: 'to react' },
	{ word: 'offrir', translation: 'to offer/give (a gift)' },
	{ word: 'découvrir', translation: 'to discover' },
	{ word: 'couvrir', translation: 'to cover' },
	{ word: 'servir', translation: 'to serve' },
	{ word: 'sentir', translation: 'to feel/smell' },
	{ word: 'mentir', translation: 'to lie (untruth)' },
	{ word: 'obtenir', translation: 'to obtain' },
	{ word: 'appartenir', translation: 'to belong' },
	{ word: 'soutenir', translation: 'to support' },

	// Common -re verbs (various levels)
	{ word: 'entendre', translation: 'to hear' },
	{ word: 'rendre', translation: 'to give back/return' },
	{ word: 'défendre', translation: 'to defend/forbid' },
	{ word: 'plaire', translation: 'to please' },
	{ word: 'se plaindre', translation: 'to complain' },
	{ word: 'résoudre', translation: 'to solve/resolve' },
	{ word: 'conclure', translation: 'to conclude' },
	{ word: 'interrompre', translation: 'to interrupt' },
	{ word: 'battre', translation: 'to beat/hit' },
	{ word: 'rompre', translation: 'to break (off)' },
	{ word: 'mordre', translation: 'to bite' },
	{ word: 'coudre', translation: 'to sew' },
	{ word: 'naître', translation: 'to be born' },
	{ word: 'mourir', translation: 'to die' },
	{ word: 'paraître', translation: 'to appear/seem' },
	{ word: 'convaincre', translation: 'to convince' },
	{ word: 'vaincre', translation: 'to defeat/overcome' },
	{ word: 'joindre', translation: 'to join/attach' },
	{ word: 'éteindre', translation: 'to extinguish/turn off' },
];
