export const verbs = [
	// Essential verbs
	{ lemma: 'être', meaning: 'to be', isBeginner: true },
	{ lemma: 'avoir', meaning: 'to have', isBeginner: true },
	{ lemma: 'aller', meaning: 'to go', isBeginner: true },
	{ lemma: 'faire', meaning: 'to do/make', isBeginner: true },
	{ lemma: 'dire', meaning: 'to say/tell', isBeginner: true },
	{ lemma: 'pouvoir', meaning: 'can/to be able to', isBeginner: true },
	{ lemma: 'vouloir', meaning: 'to want', isBeginner: true },
	{ lemma: 'savoir', meaning: 'to know (a fact)', isBeginner: true },
	{ lemma: 'devoir', meaning: 'to have to/must', isBeginner: true },
	{ lemma: 'falloir', meaning: 'to be necessary', isBeginner: true },
	{ lemma: 'voir', meaning: 'to see', isBeginner: true },
	{ lemma: 'prendre', meaning: 'to take', isBeginner: true },
	{ lemma: 'donner', meaning: 'to give', isBeginner: true },
	{ lemma: 'mettre', meaning: 'to put/place', isBeginner: true },
	{ lemma: 'tenir', meaning: 'to hold', isBeginner: true },

	// Movement verbs
	{ lemma: 'venir', meaning: 'to come', isBeginner: true },
	{ lemma: 'partir', meaning: 'to leave/depart', isBeginner: true },
	{ lemma: 'arriver', meaning: 'to arrive', isBeginner: true },
	{ lemma: 'sortir', meaning: 'to go out', isBeginner: true },
	{ lemma: 'entrer', meaning: 'to enter', isBeginner: true },
	{ lemma: 'monter', meaning: 'to go up/climb', isBeginner: true },
	{ lemma: 'descendre', meaning: 'to go down/descend', isBeginner: true },
	{ lemma: 'tomber', meaning: 'to fall', isBeginner: true },
	{ lemma: 'courir', meaning: 'to run', isBeginner: true },
	{ lemma: 'marcher', meaning: 'to walk', isBeginner: true },
	{ lemma: 'revenir', meaning: 'to come back' },
	{ lemma: 'retourner', meaning: 'to return/go back' },
	{ lemma: 'passer', meaning: 'to pass/spend (time)', isBeginner: true },
	{ lemma: 'traverser', meaning: 'to cross' },
	{ lemma: 'se promener', meaning: 'to take a walk' },
	{ lemma: 'nager', meaning: 'to swim' },
	{ lemma: 'voler', meaning: 'to fly/steal' },
	{ lemma: 'glisser', meaning: 'to slide/slip' },
	{ lemma: 'reculer', meaning: 'to step back/reverse' },
	{ lemma: 'avancer', meaning: 'to move forward/advance' },
	{ lemma: 'se dépêcher', meaning: 'to hurry' },

	// Communication verbs
	{ lemma: 'parler', meaning: 'to speak/talk', isBeginner: true },
	{ lemma: 'écrire', meaning: 'to write', isBeginner: true },
	{ lemma: 'lire', meaning: 'to read', isBeginner: true },
	{ lemma: 'écouter', meaning: 'to listen', isBeginner: true },
	{ lemma: 'répondre', meaning: 'to answer/reply', isBeginner: true },
	{ lemma: 'demander', meaning: 'to ask', isBeginner: true },
	{ lemma: 'appeler', meaning: 'to call', isBeginner: true },
	{ lemma: 'expliquer', meaning: 'to explain' },
	{ lemma: 'raconter', meaning: 'to tell/narrate' },
	{ lemma: 'discuter', meaning: 'to discuss' },
	{ lemma: 'annoncer', meaning: 'to announce' },
	{ lemma: 'décrire', meaning: 'to describe' },
	{ lemma: 'murmurer', meaning: 'to whisper/murmur' },
	{ lemma: 'crier', meaning: 'to shout/scream' },
	{ lemma: 'prononcer', meaning: 'to pronounce' },
	{ lemma: 'traduire', meaning: 'to translate' },
	{ lemma: 'répéter', meaning: 'to repeat', isBeginner: true },
	{ lemma: 'suggérer', meaning: 'to suggest' },
	{ lemma: 'promettre', meaning: 'to promise' },
	{ lemma: 'avouer', meaning: 'to confess/admit' },

	// Daily life verbs
	{ lemma: 'manger', meaning: 'to eat', isBeginner: true },
	{ lemma: 'boire', meaning: 'to drink', isBeginner: true },
	{ lemma: 'dormir', meaning: 'to sleep', isBeginner: true },
	{ lemma: 'travailler', meaning: 'to work', isBeginner: true },
	{ lemma: 'jouer', meaning: 'to play', isBeginner: true },
	{ lemma: 'regarder', meaning: 'to watch/look at', isBeginner: true },
	{ lemma: 'chercher', meaning: 'to look for/search', isBeginner: true },
	{ lemma: 'trouver', meaning: 'to find', isBeginner: true },
	{ lemma: 'acheter', meaning: 'to buy', isBeginner: true },
	{ lemma: 'vendre', meaning: 'to sell' },
	{ lemma: 'payer', meaning: 'to pay', isBeginner: true },
	{ lemma: 'cuisiner', meaning: 'to cook' },
	{ lemma: 'se lever', meaning: 'to get up', isBeginner: true },
	{ lemma: 'se coucher', meaning: 'to go to bed', isBeginner: true },
	{ lemma: 'se laver', meaning: 'to wash oneself', isBeginner: true },
	{ lemma: "s'habiller", meaning: 'to get dressed', isBeginner: true },
	{ lemma: 'conduire', meaning: 'to drive' },
	{ lemma: 'nettoyer', meaning: 'to clean' },
	{ lemma: 'ranger', meaning: 'to tidy up/put away' },
	{ lemma: 'porter', meaning: 'to carry/wear', isBeginner: true },
	{ lemma: 'ouvrir', meaning: 'to open', isBeginner: true },
	{ lemma: 'fermer', meaning: 'to close', isBeginner: true },
	{ lemma: 'habiter', meaning: 'to live (reside)', isBeginner: true },
	{ lemma: 'vivre', meaning: 'to live (be alive)' },
	{ lemma: 'utiliser', meaning: 'to use' },
	{ lemma: 'préparer', meaning: 'to prepare' },
	{ lemma: 'commencer', meaning: 'to begin/start', isBeginner: true },
	{ lemma: 'finir', meaning: 'to finish', isBeginner: true },
	{ lemma: 'attendre', meaning: 'to wait', isBeginner: true },
	{ lemma: 'se réveiller', meaning: 'to wake up' },

	// Cognition verbs
	{ lemma: 'penser', meaning: 'to think', isBeginner: true },
	{ lemma: 'croire', meaning: 'to believe' },
	{ lemma: 'comprendre', meaning: 'to understand', isBeginner: true },
	{ lemma: 'connaître', meaning: 'to know (person/place)', isBeginner: true },
	{ lemma: 'oublier', meaning: 'to forget' },
	{ lemma: 'se souvenir', meaning: 'to remember' },
	{ lemma: 'apprendre', meaning: 'to learn', isBeginner: true },
	{ lemma: 'étudier', meaning: 'to study', isBeginner: true },
	{ lemma: 'reconnaître', meaning: 'to recognize' },
	{ lemma: 'réfléchir', meaning: 'to reflect/think about' },
	{ lemma: 'imaginer', meaning: 'to imagine' },
	{ lemma: 'douter', meaning: 'to doubt' },
	{ lemma: 'supposer', meaning: 'to suppose/assume' },
	{ lemma: 'deviner', meaning: 'to guess' },
	{ lemma: 'remarquer', meaning: 'to notice' },
	{ lemma: 'se rendre compte', meaning: 'to realize' },
	{ lemma: 'juger', meaning: 'to judge' },
	{ lemma: 'considérer', meaning: 'to consider' },

	// Emotion verbs
	{ lemma: 'aimer', meaning: 'to love/like', isBeginner: true },
	{ lemma: 'détester', meaning: 'to hate' },
	{ lemma: 'préférer', meaning: 'to prefer', isBeginner: true },
	{ lemma: 'espérer', meaning: 'to hope' },
	{ lemma: 'craindre', meaning: 'to fear' },
	{ lemma: 'regretter', meaning: 'to regret' },
	{ lemma: "s'inquiéter", meaning: 'to worry' },
	{ lemma: 'adorer', meaning: 'to adore', isBeginner: true },
	{ lemma: "s'ennuyer", meaning: 'to be bored' },
	{ lemma: 'se fâcher', meaning: 'to get angry' },
	{ lemma: 'pleurer', meaning: 'to cry' },
	{ lemma: 'rire', meaning: 'to laugh' },
	{ lemma: 'sourire', meaning: 'to smile' },
	{ lemma: 'souffrir', meaning: 'to suffer' },
	{ lemma: 'profiter', meaning: 'to enjoy/take advantage' },
	{ lemma: "s'amuser", meaning: 'to have fun' },
	{ lemma: 'se sentir', meaning: 'to feel' },
	{ lemma: 'surprendre', meaning: 'to surprise' },

	// Creation verbs
	{ lemma: 'créer', meaning: 'to create' },
	{ lemma: 'construire', meaning: 'to build/construct' },
	{ lemma: 'produire', meaning: 'to produce' },
	{ lemma: 'développer', meaning: 'to develop' },
	{ lemma: 'inventer', meaning: 'to invent' },
	{ lemma: 'dessiner', meaning: 'to draw' },
	{ lemma: 'peindre', meaning: 'to paint' },
	{ lemma: 'fabriquer', meaning: 'to manufacture/make' },
	{ lemma: 'composer', meaning: 'to compose' },
	{ lemma: 'concevoir', meaning: 'to design/conceive' },
	{ lemma: 'réaliser', meaning: 'to achieve/realize' },
	{ lemma: 'établir', meaning: 'to establish' },
	{ lemma: 'fonder', meaning: 'to found/establish' },

	// Change verbs
	{ lemma: 'changer', meaning: 'to change' },
	{ lemma: 'devenir', meaning: 'to become' },
	{ lemma: 'grandir', meaning: 'to grow (up)' },
	{ lemma: 'améliorer', meaning: 'to improve' },
	{ lemma: 'transformer', meaning: 'to transform' },
	{ lemma: 'augmenter', meaning: 'to increase' },
	{ lemma: 'diminuer', meaning: 'to decrease/diminish' },
	{ lemma: 'modifier', meaning: 'to modify' },
	{ lemma: 'remplacer', meaning: 'to replace' },
	{ lemma: 'adapter', meaning: 'to adapt' },
	{ lemma: 'évoluer', meaning: 'to evolve' },
	{ lemma: 'disparaître', meaning: 'to disappear' },
	{ lemma: 'apparaître', meaning: 'to appear' },

	// Social verbs
	{ lemma: 'rencontrer', meaning: 'to meet' },
	{ lemma: 'inviter', meaning: 'to invite' },
	{ lemma: 'aider', meaning: 'to help', isBeginner: true },
	{ lemma: 'partager', meaning: 'to share' },
	{ lemma: 'accompagner', meaning: 'to accompany' },
	{ lemma: 'suivre', meaning: 'to follow' },
	{ lemma: 'présenter', meaning: 'to introduce/present', isBeginner: true },
	{ lemma: 'remercier', meaning: 'to thank' },
	{ lemma: 'féliciter', meaning: 'to congratulate' },
	{ lemma: 'accueillir', meaning: 'to welcome' },
	{ lemma: 'se marier', meaning: 'to get married' },
	{ lemma: 'divorcer', meaning: 'to divorce' },
	{ lemma: 'saluer', meaning: 'to greet' },
	{ lemma: 'embrasser', meaning: 'to kiss/hug' },
	{ lemma: 'quitter', meaning: 'to leave (someone/place)' },

	// Common -er verbs (various levels)
	{ lemma: 'chanter', meaning: 'to sing' },
	{ lemma: 'danser', meaning: 'to dance' },
	{ lemma: 'voyager', meaning: 'to travel' },
	{ lemma: 'visiter', meaning: 'to visit (a place)' },
	{ lemma: 'compter', meaning: 'to count' },
	{ lemma: 'essayer', meaning: 'to try' },
	{ lemma: 'envoyer', meaning: 'to send' },
	{ lemma: 'toucher', meaning: 'to touch' },
	{ lemma: 'garder', meaning: 'to keep/guard' },
	{ lemma: 'laisser', meaning: 'to leave/let' },
	{ lemma: 'montrer', meaning: 'to show', isBeginner: true },
	{ lemma: 'tirer', meaning: 'to pull/shoot' },
	{ lemma: 'pousser', meaning: 'to push' },
	{ lemma: 'jeter', meaning: 'to throw' },
	{ lemma: 'lever', meaning: 'to raise/lift' },
	{ lemma: 'poser', meaning: 'to put down/ask (a question)' },
	{ lemma: 'arrêter', meaning: 'to stop' },
	{ lemma: 'continuer', meaning: 'to continue' },
	{ lemma: 'rester', meaning: 'to stay/remain', isBeginner: true },
	{ lemma: 'manquer', meaning: 'to miss/lack' },
	{ lemma: 'gagner', meaning: 'to win/earn' },
	{ lemma: 'perdre', meaning: 'to lose' },
	{ lemma: 'sauver', meaning: 'to save/rescue' },
	{ lemma: 'occuper', meaning: 'to occupy' },
	{ lemma: 'exister', meaning: 'to exist' },
	{ lemma: 'représenter', meaning: 'to represent' },
	{ lemma: 'accepter', meaning: 'to accept' },
	{ lemma: 'refuser', meaning: 'to refuse' },
	{ lemma: 'proposer', meaning: 'to propose/suggest' },
	{ lemma: 'organiser', meaning: 'to organize' },
	{ lemma: 'participer', meaning: 'to participate' },
	{ lemma: 'séparer', meaning: 'to separate' },
	{ lemma: 'retrouver', meaning: 'to find again/meet up' },
	{ lemma: 'installer', meaning: 'to install/settle' },
	{ lemma: 'vérifier', meaning: 'to verify/check' },
	{ lemma: 'respecter', meaning: 'to respect' },
	{ lemma: 'exprimer', meaning: 'to express' },
	{ lemma: 'empêcher', meaning: 'to prevent' },
	{ lemma: 'dépenser', meaning: 'to spend (money)' },
	{ lemma: 'économiser', meaning: 'to save (money)' },
	{ lemma: 'louer', meaning: 'to rent' },
	{ lemma: 'déménager', meaning: 'to move (house)' },
	{ lemma: 'protéger', meaning: 'to protect' },
	{ lemma: 'brûler', meaning: 'to burn' },
	{ lemma: 'casser', meaning: 'to break' },
	{ lemma: 'couper', meaning: 'to cut' },
	{ lemma: 'frapper', meaning: 'to hit/knock' },
	{ lemma: 'ramasser', meaning: 'to pick up/collect' },
	{ lemma: 'attraper', meaning: 'to catch' },

	// Common -ir verbs (various levels)
	{ lemma: 'choisir', meaning: 'to choose' },
	{ lemma: 'réussir', meaning: 'to succeed' },
	{ lemma: 'remplir', meaning: 'to fill' },
	{ lemma: 'obéir', meaning: 'to obey' },
	{ lemma: 'punir', meaning: 'to punish' },
	{ lemma: 'guérir', meaning: 'to heal/cure' },
	{ lemma: 'réunir', meaning: 'to gather/reunite' },
	{ lemma: 'nourrir', meaning: 'to feed/nourish' },
	{ lemma: 'ralentir', meaning: 'to slow down' },
	{ lemma: 'agir', meaning: 'to act' },
	{ lemma: 'réagir', meaning: 'to react' },
	{ lemma: 'offrir', meaning: 'to offer/give (a gift)' },
	{ lemma: 'découvrir', meaning: 'to discover' },
	{ lemma: 'couvrir', meaning: 'to cover' },
	{ lemma: 'servir', meaning: 'to serve' },
	{ lemma: 'sentir', meaning: 'to feel/smell' },
	{ lemma: 'mentir', meaning: 'to lie (untruth)' },
	{ lemma: 'obtenir', meaning: 'to obtain' },
	{ lemma: 'appartenir', meaning: 'to belong' },
	{ lemma: 'soutenir', meaning: 'to support' },

	// Common -re verbs (various levels)
	{ lemma: 'entendre', meaning: 'to hear' },
	{ lemma: 'rendre', meaning: 'to give back/return' },
	{ lemma: 'défendre', meaning: 'to defend/forbid' },
	{ lemma: 'plaire', meaning: 'to please' },
	{ lemma: 'se plaindre', meaning: 'to complain' },
	{ lemma: 'résoudre', meaning: 'to solve/resolve' },
	{ lemma: 'conclure', meaning: 'to conclude' },
	{ lemma: 'interrompre', meaning: 'to interrupt' },
	{ lemma: 'battre', meaning: 'to beat/hit' },
	{ lemma: 'rompre', meaning: 'to break (off)' },
	{ lemma: 'mordre', meaning: 'to bite' },
	{ lemma: 'coudre', meaning: 'to sew' },
	{ lemma: 'naître', meaning: 'to be born' },
	{ lemma: 'mourir', meaning: 'to die' },
	{ lemma: 'paraître', meaning: 'to appear/seem' },
	{ lemma: 'convaincre', meaning: 'to convince' },
	{ lemma: 'vaincre', meaning: 'to defeat/overcome' },
	{ lemma: 'joindre', meaning: 'to join/attach' },
	{ lemma: 'éteindre', meaning: 'to extinguish/turn off' }
];
