import { json } from '@sveltejs/kit';
import { prisma } from '$lib/server/prisma';
import { generateChatCompletion } from '$lib/server/llm';
import type { RequestEvent } from '@sveltejs/kit';

export async function POST({ locals }: RequestEvent) {
  if (!locals.user || locals.user.role !== 'ADMIN') {
    return json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const twentyFourHoursAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);

    const pendingWords = await prisma.vocabulary.findMany({
      where: {
        isAutoGenerated: true,
        createdAt: { lte: twentyFourHoursAgo }
      },
      include: { language: true, meanings: true }
    });

    if (pendingWords.length === 0) {
      return json({
        success: true,
        approvedCount: 0,
        rejectedCount: 0,
        message: 'No words older than 24 hours found.'
      });
    }

    const prompt = `You are a strict safety reviewer for an educational language learning app used by schools.
Your task is to review a list of submitted vocabulary words and approve or reject them.

Rules for approval:
1. The word MUST be a real, correctly spelled word in its respective language.
2. The word MUST be completely safe and appropriate to be broadcasted at a school assembly.
3. Reject any inappropriate slang, profanity, slurs, or suggestive content.
4. Actively look out for deceitful submissions, bypass attempts, or fake words designed to trick the system.
5. If you are unsure, reject it.

Please evaluate each word in the provided JSON array. Return a JSON object with a single key "results" mapping the ID of each word to a boolean (true for approve, false for reject).

Format: { "results": { "uuid1": true, "uuid2": false } }`;

    const wordsData = pendingWords.map((w) => ({
      id: w.id,
      language: w.language?.name,
      lemma: w.lemma,
      meaning: (w as any).meanings?.[0]?.value || null
    }));

    const response = await generateChatCompletion({
      userId: locals.user.id,
      messages: [{ role: 'user', content: JSON.stringify(wordsData) }],
      systemPrompt: prompt,
      jsonMode: true,
      temperature: 0.1
    });

    const rawContent = response.choices[0].message.content;
    const parsed = JSON.parse(rawContent);
    const results = parsed.results;

    if (!results || typeof results !== 'object') {
      throw new Error('Invalid LLM response format');
    }

    let approvedCount = 0;
    let rejectedCount = 0;

    for (const [id, isApproved] of Object.entries(results)) {
      if (isApproved === true) {
        const { count } = await prisma.vocabulary.updateMany({
          where: { id },
          data: { isAutoGenerated: false }
        });
        approvedCount += count;
      } else if (isApproved === false) {
        const { count } = await prisma.vocabulary.deleteMany({
          where: { id }
        });
        rejectedCount += count;
      }
    }

    return json({ success: true, approvedCount, rejectedCount });
  } catch (error) {
    console.error('Error during auto AI review:', error);
    return json({ error: 'Failed to perform auto AI review' }, { status: 500 });
  }
}
